version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      runtime-dependencies:
        applies-to: version-updates
        dependency-type: production
        patterns:
          - "*"
      development-dependencies:
        applies-to: version-updates
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
