// Слова, которые инструмент говорит человеку.
//
// Зачем отдельный модуль. Средство общего назначения не должно объясняться
// с чужим агентом на языке, который он не выбирал: строки, вшитые в код,
// делают язык интерфейса свойством инструмента, а не работы. Здесь
// поставляются два словаря; ролик может назвать язык сам (`lang`), иначе
// он берётся из окружения, иначе — английский.
//
// Английский умолчанием не из предпочтения, а потому, что он —
// единственный, который посторонний потребитель наверняка прочтёт.
// Русский поставляется и включается одним словом.
//
// Ключ сообщения — устойчивый идентификатор, а не фраза: по нему пишут
// проверки, и перевод не должен их ломать.
export type Lang = "en" | "ru";

type Dict = Record<string, string>;

const en: Dict = {
  "device.form": "device: expected «browser [url]», «phone» or JSON",
  "device.kind": "device.kind: expected {kinds}",
  "device.url": "device.url: expected text",
  "device.unknown": "device: expected {kinds}, got «{kind}»",
  "fit.form": "fit: expected contain, cover [x y] or {\"mode\",\"x\",\"y\"}",
  "fit.mode": "fit: expected contain or cover, got «{mode}»",
  "fit.coverPoint": "fit: only cover keeps a point in frame",
  "fit.share": "{field}: expected a share of the clip, 0…1",
  "speed.form": "speed: expected a JSON array of steps",
  "speed.nonEmpty": "speed: expected a non-empty JSON array of steps",
  "speed.holdKind": "hold",
  "speed.spanKind": "span",
  "speed.unknownProperty": "speed[{index}]: unknown property «{key}» for a {kind}",
  "speed.nonNegative": "{field}: expected a non-negative number of seconds",
  "speed.holdRange": "speed[{index}].hold: expected 0.5–12 seconds",
  "speed.number": "{field}: expected a number",
  "speed.rampSeconds": "speed[{index}].ramp: expected seconds of the source",
  "speed.rampHalf": "speed[{index}].ramp: at most half the span ({half} s)",
  "speed.interpolate": "speed[{index}].interpolate: expected true, \"motion\" or \"blend\"",
  "speed.from": "speed[{index}].from: expected a non-negative second",
  "speed.toAfterFrom": "speed[{index}]: to must be later than from",
  "speed.rateRange": "speed[{index}].rate: expected 0.2–4",
  "speed.rateOne": "speed[{index}].rate: 1 changes nothing",
  "speed.order": "speed[{index}]: steps must not overlap and must go in order",
  "speed.pastClip": "speed: step ends at {end}s, past the {duration}s clip",
  "effects.form": "{what}: expected anchors «b2 | 1.5s» or a JSON list",
  "effects.moment": "{where}: unexpected moment «{at}»; a beat (b2, b2.end+0.3), a share (40%) or seconds (1.5s)",
  "effects.range": "{where}: expected {lo}…{hi}",
  "look.unknown": "look: unknown «{name}»; available: {available}, or JSON",
  "look.form": "look: expected a name or a JSON object",
  "look.grade": "look.grade: expected {grades}",
  "look.share": "{field}: expected 0…1",
  "look.bars": "look.bars: expected an aspect ratio 1.5…3, e.g. 2.39",
  "format.unknown": "format: unknown «{name}»; available: {available}",
  "zone.unknown": "zone: unknown «{name}»; available: {available}",
  "marks.noFile": "no .marks.json beside the clip",
  "marks.unknown": "{where}: unknown mark @{name}; known: {known}",
  "transition.form": "transition: expected a kind name or a JSON object",
  "transition.unknownKind": "transition: unknown kind «{kind}»; available: {available}",
  "transition.dipColor": "transition.color: only a dip has a colour",
  "transition.cutDuration": "transition: a cut has no length; it joins the scenes edge to edge",
  "transition.morphElement": "transition.element: a morph names the element shared by both scenes, e.g. {\"kind\":\"morph\",\"element\":\"#total\"}",
  "transition.onlyMorphElement": "transition.element: only a morph moves an element",
  "transition.duration": "transition.duration: expected 0.2–2 seconds",
  "transition.sound": "transition.sound: expected an audio file",
  "transition.snap": "transition.snap: expected \"music\"",
  "transition.color": "transition.color: expected black, white or #rrggbb, got «{color}»",
  "overlay.nonNegativeTime": "{where}: at/hold must be a non-negative number of seconds",
  "overlay.badMoment": "{where}: at «{value}» is neither seconds nor a beat anchor (b2, b2+0.5, b2.end, 40%)",
  "overlay.unresolvedMoment": "{where}: at «{value}» is a beat anchor; it resolves where the scene's beats are known",
  "overlay.array": "{where}: expected an array",
  "overlay.object": "{where}: expected an object",
  "overlay.pointerOrder": "overlay.pointer: times must increase",
  "overlay.frameFraction": "{where}: expected a frame fraction from 0 to 1",
  "overlay.frameFractions": "{where}: expected {count} frame fractions from 0 to 1",
  "overlay.boolean": "{where}: expected a boolean",
  "overlay.trueFalse": "{where}: expected true or false",
  "overlay.textLength": "{where}: expected 1–{max} characters",
  "overlay.bodyLength": "{where}: expected at most 100 characters",
  "overlay.unknownPosition": "{where}: unknown position",
  "overlay.unknownMotion": "{where}: unknown motion",
  "overlay.unknownEdge": "{where}: unknown edge",
  "overlay.flyEdge": "{where}: only motion \"fly\" flies in from an edge",
  "overlay.options": "{where}: expected {options}",
  "overlay.enterExit": "{where}: expected 0.2–2.5 seconds",
  "overlay.readHold": "{where}: at least {minimum}s needed to read the text",
  "overlay.cardGap": "overlay.cards: leave 0.35s between cards",
  "overlay.cameraHold": "{where}: at least 0.8 seconds",
  "overlay.cssSelector": "{where}: expected a CSS selector",
  "overlay.cameraArea": "{where}: expected four frame fractions",
  "overlay.oneTargetArea": "{where}: name exactly one target or area",
  "overlay.outsideFrame": "{where}: outside the frame",
  "overlay.cameraScale": "{where}: expected 1–3 (1 highlights without a push-in)",
  "overlay.moveReturn": "{where}: move/return must be 0.35–4 seconds",
  "overlay.blur": "{where}: expected 0–24 points",
  "overlay.dim": "{where}: expected 0–1 of the theme's dimming",
  "overlay.follow": "{where}: expected \"cursor\"",
  "overlay.cameraChained": "overlay.camera: the move at {at}s starts during the hold of the kept move before it, which ends at {end}s; a kept move hands over after its hold",
  "overlay.cameraBack": "overlay.camera: the move at {at}s starts before the one before it is back at {end}s; leave 0.35s between moves — start it at {start}s or later",
  "overlay.oneAnchor": "{where}: name one of target, area or point",
  "overlay.anchorRequired": "{where}: name the subject with target, area or point",
  "overlay.itemGap": "{where}: leave 0.2s between items",
  "overlay.oneStickerKind": "{where}: name exactly one of emoji, image or text",
  "overlay.stickerSize": "{where}: expected 24–480 points",
  "overlay.rotate": "{where}: expected −45…45 degrees",
  "overlay.arrowFrom": "{where}: only an arrow starts somewhere",
  "overlay.twoFrameFractions": "{where}: expected two frame fractions from 0 to 1",
  "overlay.draw": "{where}: expected 0.2–4 seconds",
  "overlay.color": "{where}: expected #rrggbb",
  "overlay.wholeNumber": "{where}: expected a whole number",
  "overlay.count": "{where}: expected 4–300",
  "overlay.loupeScale": "{where}: expected 1.5–4",
  "overlay.loupeSize": "{where}: expected 0.08–0.5 of the frame width",
  "overlay.empty": "overlay: add a pointer, card, camera move, title, lower third, callout, sticker, mark, glint, burst or loupe",
  "spotlight.form": "spotlight: expected «target @ anchor | …» or JSON",
  "spotlight.jsonObject": "spotlight: expected a JSON object, got «{part}»",
  "spotlight.shortForm": "spotlight: expected «target @ anchor» or {…}, got «{part}»",
  "spotlight.empty": "spotlight: name at least one focus",
  "spotlight.anchor": "{where}: expected an anchor",
  "spotlight.slow": "{where}: expected 0.1–0.9 or \"stop\"",
  "spotlight.keepUntil": "{where}: keep stays pushed in and until returns to the overview; name one of them",
  "spotlight.card": "{where}: expected {\"title\":…}",
  "spotlight.videoArea": "spotlight[{index}]: a video scene is focused by area, not by a CSS target",
  "spotlight.overlayCollision": "spotlight collides with its overlay — {why}",
  "source.notFound": "source {path}: file not found",
  "source.error": "source {path}: {why}",
  "source.line": "line {line}: {why}",
  "source.noScenes": "the source has no scenes",
  "source.textOutside": "text outside a scene",
  "source.badHeader": "a scene header looks like «## s01 · slides.compare»",
  "source.noSpeech": "scene {id}: no speech",
  "source.required": "scene {id}: kind {kind} requires field {names}",
  "source.badField": "field «{key}» is not allowed for kind {kind}",
  "source.badFilmField": "unknown film field: {key}",
  "source.didYouMean": " — did you mean «{name}»?",
  "source.badAnchor": "«{anchor}» is not a time anchor; use b2, b2.end, b2+0.4, 40% or 1.2s",
  "source.beatOutOfRange": "anchor «{anchor}» points past the speech of scene {id}: it has {beats} beat(s)",
  "source.incompatible": "scene {id}: incompatible fields: {fields}; keep only one timing mechanism from each pair",
  "source.missingLanguage": "lang {lang}: the scenario has no {lang} text; write title.{lang}:, fields like overlay.{lang}: and a [{lang}] block of narration in each scene",
  "source.translationHeader": "a scenario with translations names its own language in the header: lang: en",
  "source.missingNarration": "scene {id}: no [{lang}] narration; each spoken scene is translated beat for beat",
  "source.translationBeats": "scene {id}: [{lang}] has {translated} beats, the original {original}; anchors like b2 name beats by number, so a translation keeps the same beats",
  "source.duration": "duration in {id} must be >0 and <=600 seconds",
  "source.trimFrom": "scene {id}: from must be a second of the clip or a take's @mark",
  "source.trimTo": "scene {id}: to must come after from ({from}s)",
  "source.sceneField": "scene {id} {field}",
  "source.sceneReason": "scene {id}: {why}",
  "source.sceneThemeReason": "scene {id}: theme: {why}",
  "source.markArea": "scene {id} {field}: area @{name} needs the element recorded with take.mark(\"{name}\", locator)",
  "source.markRecorded": "; recorded: {names}",
  "source.none": "none",
  "source.autoZoomMarks": "scene {id}: autoZoom needs the clicks recorded by agentic-screencast/capture ({file}.marks.json)",
  "source.stillMarkOnly": "scene {id} stills: a take's @mark works only on a video scene with its .marks.json",
  "source.stillsWhere": "scene {id} stills",
  "source.freezeAt": "freezeAt in {id} must be a non-negative second",
  "source.silentDuration": "silent scene {id} needs duration",
  "source.transitionSound": "transition.sound: file not found: {file}",
  "source.captionsPosition": "scene {id}: captions: expected {positions} — where this scene's subtitles stand",
  "source.speechAt": "scene {id}: speechAt: expected 0–10 seconds from the scene's start",
  "source.loudness": "loudness: expected a LUFS target from -30 to -8",
  "source.audio": "audio: expected false (a film without a sound track) or true",
  "source.motionBlurSamples": "motionBlur.samples: expected 2–16",
  "source.motionBlurShutter": "motionBlur.shutter: expected a share of the frame from 0 to 1",
  "source.emojiDir": "emoji: expected {\"dir\":\"<folder>\"}",
  "source.badFormat": "--format: {why}",
  "source.formatReframe": "--format {format}: the scenario is already {current}; only a landscape scenario is reframed",
  "source.letterboxReframe": "letterbox bars are not drawn in a {format} build of a landscape scenario",
  "source.lookBars": "look.bars: letterbox bars need a landscape frame, this film is {width}×{height}; use a look without bars, e.g. look: cinematic",
  "source.jsonObject": "{field}: expected a JSON object",
  "source.jsonList": "{field}: expected a JSON list",
  "source.unknownProperty": "{field}: unknown property «{key}»",
  "source.options": "{field}: expected {options}",
  "source.fadeRange": "fade{part}: expected 0–3 seconds",
  "source.fadeForm": "fade: expected none, seconds or {\"in\":…,\"out\":…}",
  "source.captionsLook": "captions.look: expected outline (white text with a dark outline, the default) or plate (a dense backing)",
  "source.captionsSize": "captions.size: expected a number from 0.8 to 1.6 (1 is the usual subtitle size)",
  "source.captionsStyle": "captions.style: expected bar | subtitle | karaoke",
  "source.booleanField": "{field}: expected true or false",
  "source.pipFile": "pip.file: expected a video file",
  "source.pipCorner": "pip.corner: expected bottom-right | bottom-left | top-right | top-left",
  "source.pipSize": "pip.size: expected 0.08–0.45 of the frame width",
  "source.pipTime": "pip.{field}: expected seconds of the film",
  "source.progressLabel": "progress.label: expected edge (beside the bar at the frame's edge) | zone (at the safe zone's edge)",
  "source.progressPosition": "progress.position: expected top | bottom",
  "source.musicFile": "music.file: expected an audio file",
  "source.fileMissing": "{field}: file not found: {file}",
  "source.range": "{field}: expected {low}…{high}",
  "source.musicMoment": "music.at: unexpected moment «{at}»; a beat (b2, b2.end+0.3), a share (40%) or seconds (1.5s)",
  "source.musicStop": "music.{field}: a stop plays nothing",
  "source.musicFileOrStop": "music.file: expected an audio file, or stop",
  "source.expectedObject": "{field}: expected an object",
  "source.unexpectedMoment": "{field}: unexpected moment «{at}»",
  "source.audioFile": "{field}: expected an audio file",
  "source.sfxGain": "{field}: expected -30…12 dB",
  "source.autoZoomFollow": "autoZoom.follow: expected \"cursor\"",
  "source.autoZoomScale": "autoZoom.scale: expected >1 and <=3",
  "source.autoZoomHold": "autoZoom.hold: expected 0.8–6 seconds",
  "source.autoZoomSize": "autoZoom.size: expected 0.1–0.8 of the frame",
  "stills.step": "{where}: «{at}» — the step is 0.25–10 seconds",
  "stills.moment": "{where}: «{at}» is not a moment; use b2, b2+0.5, b2.end, 80%, 1.5, @mark or every 1s",
  "stills.empty": "{where}: name at least one moment",
  "slides.imageMissing": "scene {id}: image not found: {file}",
  "slides.imageType": "scene {id}: image must be png, jpg, webp, gif, svg or avif: {file}",
  "slides.imageSize": "scene {id}: cannot read the size of {file}",
  "slides.where": "scene {id}: {field}",
  "slides.pair": "{where}: expected two numbers {low}–{high}, got «{value}»",
  "slides.column": "scene {id}: write a column as «Heading :: content»",
  "slides.dataMissing": "scene {id}: data file not found: {file}",
  "slides.chartRows": "scene {id}: data: a chart needs 2–24 rows «label,value», got {count}",
  "slides.chartRow": "scene {id}: data row {row}: expected «label,value», got «{value}»",
  "slides.chartValue": "scene {id}: data row {row}: a chart shows values from zero up, got {value}",
  "slides.options": "scene {id}: {field}: expected {options}",
  "slides.peak": "scene {id}: peak: expected max, none, a row number 1–{count} or a label from the data, got «{value}»",
  "slides.background": "scene {id}: background: unknown «{value}»{hint}; available: {available}",
  "slides.textStyle": "scene {id}: text: expected {options}, got «{value}»",
  "slides.textCount": "scene {id}: text: name at most two styles — for the title and for the body",
  "slides.codeMissing": "scene {id}: code file not found: {file}",
  "slides.cps": "scene {id}: cps: expected 5–400 characters per second",
  "slides.labels": "scene {id}: labels: expected two, «Before | After»",
  "slides.panelForm": "{where}: expected «x y w h @ depth», e.g. «0.05 0.1 0.4 0.5 @ 0.8»",
  "slides.panelOutside": "{where}: the panel lies outside the picture",
  "slides.panelDepth": "{where}: depth is 0–1, where 1 is nearest",
  "slides.panelCount": "scene {id}: panels: at most 8",
  "script.summary": "Scenes: {scenes}. Beats: {beats}. Words in narration: {words}.",
  "provider.unknown": "unknown provider «{name}»; known: {known}\n"
    + "declare an outside one in the film header: providers: {\"name\": \"command\"}",
  "provider.unknownKind": "provider «{provider}» does not know kind «{kind}»; it offers: {kinds}",
  "provider.notFound": "provider «{command}»: program not found",
  "provider.failed": "provider «{command}» failed (code {code}): {said}",
  "provider.notJson": "provider «{command}» answered {what} with non-JSON: {said}",
  "provider.noFile": "provider «{command}» did not name the page file",
  "provider.cannotDraw": "provider «{name}» cannot draw a page and named no ready file",
  "engine.unnamed": "no engine named in the voice data",
  "engine.notFound": "engine «{command}»: program not found",
  "engine.failed": "engine «{command}» failed (code {code}): {said}",
  "engine.notJson": "engine «{command}» answered {what} with non-JSON: {said}",
  "build.noPage": "no page: {path}",
  "build.noScene": "no scene «{id}» in this film",
  "build.sceneCached": "[{at}/{of}] {id}: taken from cache",
  "build.sceneRender": "[{at}/{of}] {id}: drawing {frames} frames…",
  "build.sceneVideo": "[{at}/{of}] {id}: bringing the clip to the film frame…",
  "build.done": "done: {out} — {secs} s, {w}×{h}, {fps} fps, {scenes} scene(s)",
  "build.unknownVoice": "unknown",
  "build.legible": "scene {id}: text of {target} is {px} px in the frame at {at}s, under the {min} px a phone reads; push in harder (scale), pan along a wide subject (pan), or magnify it with a loupe",
  "build.small": "scene {id}: text under the {min} px a phone reads — {lines}; shorten it or give it a scene of its own (a page with larger type)",
  "build.cut": "scene {id}: the frame cuts text of {target} at {at}s — {text}; lower the scale, pan along it (pan), or focus a smaller part",
  "build.overflow": "scene {id}: the slide does not fit its area by {px} px of the grid even shrunk to 72%; split it into two scenes or shorten the items",
  "build.stills": "{count} stills: {path}",
  "build.failed": "build failed: {said}",
  "build.encodedPeakExceeded": "final AAC true peak is {measured} dBTP, above the {limit} dBTP limit after correction",
  "build.auditIssue": "finished MP4 audit: {code} ({details})",
  "build.jobs": "AGENTIC_SCREENCAST_JOBS: expected a whole number from 1, got «{raw}»",
  "build.voicePitch": "voice.pitch: expected semitones from -12 to 12 (a lower voice is negative), not 0",
  "build.sceneError": "scene {id}: {why}",
  "build.speedHint": "; speed seconds count from the start of the piece (from: {from}s of the source), not from the start of the source",
  "build.trimPast": "scene {id}: from {from}s is past the end of the clip ({whole}s)",
  "build.autoZoomCollision": "scene {id}: autoZoom collides with its overlay — {why}",
  "build.loupeTarget": "scene {id}: a loupe over a clip names an area or a point, not a CSS target",
  "build.freezePast": "freezeAt is past the end of {id}",
  "build.cameraEmpty": "scene {id}: camera area [{area}] is nearly empty (contrast {contrast} < {minimum}); point it at the subject",
  "build.sfxTempo": "sfx at {at}: a music beat needs a tempo; no rhythm was heard in the music, so name music.bpm in the header",
  "build.morphVideo": "scene {id}: a morph joins two drawn scenes (slides or pages), not a clip",
  "build.morphElement": "scene {id}: morph element {element}: {why}",
  "frames.source": "source {path}: {why}",
  "frames.conflict": "--scene and --except cannot be used together",
  "frames.noScene": "no scene «{id}»; scenes: {scenes}",
  "frames.badAt": "--at {at}: expected a share of the scene (0.8 or 80%), seconds (2.4s) or a moment of the speech (b2, b2+0.5, b2.end)",
  "frames.badOut": "--out: the sheet is a PNG file; name it with .png, e.g. --out {example}",
  "frames.noFrame": "no frame written",
  "frames.empty": "a flat empty band {percent}% of the frame high at {at}s: the frame has no subject there; fill it with the product or its evidence, or let the content take the height (align, film craft 58)",
  "frames.emptyLine": "frames: {id}: {message}",
  "frames.sheetClip": "clip {at}s",
  "frames.sheetEstimated": "estimated beats",
  "speech.noRules": "no speech rules «{name}»: neither shipped nor at {path}",
  "record.notBuilt": "the recording page is not built: run npm run build in the tool directory",
  "record.noScene": "no scene {id}",
  "record.noRecording": "no recording",
  "record.unreadable": "the recording cannot be read: {why}",
  "record.noDuration": "the recording has no measurable duration",
  "record.noFile": "no such file",
  "record.started": "recording page: {url}",
  "record.store": "recording store: {path}",
  "record.stop": "stop: Ctrl+C",
  "lint.overloadedLine": "beat {beat} is {chars} characters — more than two subtitle lines ({limit}); split it into two beats",
  "lint.untranslatedFilm": "the film title has no {lang} translation; write title.{lang}: in the header",
  "lint.untranslatedScene": "line {line}: {field} is shown on screen and has no {lang} translation; write {field}.{lang}:",
  "lint.cardCaption": "card «{title}» at {at}s shares the frame with the caption; hold it on a camera push-in, or move the words into the narration",
  "lint.titleCard": "title «{title}» and card «{card}» are on screen together; give each its own moment",
  "lint.titleOverInterface": "title «{title}» sits at the top of an interface, over its own header; put it at the centre, where the frame dims under it",
  "lint.speedRangeSource": "speed ends at {end}s, but the clip the scene shows is {piece}s long; speed seconds count from the start of the piece (from: {from}s of the source), so write {local}s, not {end}s",
  "lint.speedRange": "speed ends at {end}s, but the clip the scene shows is {piece}s long; end the speed at {piece}s at the latest, or lengthen the piece (to)",
  "lint.captionsTopProgress": "subtitles stand at the top and so does the progress bar with the part label; put one of them at the bottom (progress.position or captions)",
  "lint.takeSmallRecorded": "the clip is {clip} and is enlarged {scale}× to fill the {frame} frame, so it goes soft; record it at the frame's size — recordTake({ viewport, scale }) records a phone layout in device pixels",
  "lint.takeSmallExternal": "the clip is {clip} and is enlarged {scale}× to fill the {frame} frame, so it goes soft; take a larger file of the same clip if the source has one",
  "lint.pieceCrossesMark": "the piece {from}–{end}s of the take runs past @{mark} ({at}s), which this scene does not name — the next shot starts there; end the piece at to: @{mark}",
  "lint.emptyArea": "in {percent}% of the scene's frames a third of the picture or more is one flat colour — an empty filler or a page that slid away; fill the frame with the real screen, move the subtitles instead of padding the content (film craft 53)",
  "lint.sceneJump": "the screen changes abruptly {at}s into the piece, where the take has no mark — a navigation inside the shot; end the piece at a mark placed before it (film craft 54)",
  "lint.firstTransition": "the first scene has no scene before it, so its transition is never played; move it to the second scene or remove it",
  "lint.takeThemeOld": "the take {file} was recorded before takes stored their theme, so its cursor, clicks and cards may not match the scene's {wanted}; to be sure, record it again with theme: {hint}",
  "lint.takeThemeMismatch": "the take {file} was recorded in {recorded}, the scene wears {wanted}; record it again with theme: {hint}",
  "lint.pushCrop": "the push-in at {at} scales ×{scale}, but its area stays whole in the frame only up to ×{fit}; drop scale to fit it or name a smaller area",
  "lint.loupeScale": "the loupe at {at}s magnifies ×{actual} instead of ×{asked}: its area does not fit a lens of the largest size at that scale; name a smaller area",
  "lint.stillPage": "the page stands still for {duration}s; add a camera move, a spotlight or a focus that follows the narration",
  "lint.stillVideo": "a frozen frame without a camera move or highlight reads as a pause; push in on what the narration names",
  "lint.stillHold": "spotlight[{index}] holds from {from}s for {hold}s while the clip stands still for {still}s; pass that stretch faster with speed: [{\"from\":{from},\"to\":{to},\"rate\":2}], or end the focus sooner with until",
  "lint.typingTooFast": "the {field} ({chars} characters) is typed from {from}s and must finish before the scene ends at {end}s — {pace}; make the scene at least {fits}s or shorten the {field}",
  "lint.typingNoTime": "no time is left",
  "lint.typingRate": "{rate} characters per second, faster than can be read",
  "lint.numberSource": "the {kind} slide shows numbers with no source and date under them; write note: <where the numbers come from>, <date or month and year> (film craft 12, 56)",
  "lint.longScene": "about {duration}s in one scene; split it into shots of one idea each (over {limit}s the viewer loses the thread)",
  "lint.clicheHit": "flash or shake in a film that is not a trailer: an impact without its genre reads as noise (film craft 63)",
  "lint.clicheGrain": "film grain on a film that is not a trailer: grain belongs over filmed footage in a trailer, and it multiplies the file size (film craft 63)",
  "lint.clicheSparkles": "{count} bursts and glints: more than two a film and they stop meaning success",
  "lint.clicheTransitions": "{count} kinds of transition ({kinds}): one or two a film, chosen for what the cut means (film craft 52)",
  "lint.clicheBackground": "an aurora, mesh, bokeh or particles background as depth: the AI-startup look; a quiet grid or none, unless the motion is the subject",
  "lint.clicheAddress": "a browser frame with no real address or a placeholder one: a frame is for the real address, a mockup is labelled as an illustration (film craft 60)",
  "lint.clicheKicker": "a kicker in capitals over the slide: capitals belong to a trailer card or the film's title; write kickers in sentence case",
  "lint.clicheEmoji": "emoji as feature icons: interchangeable icons are a template; one claim with its evidence, or a fact that sets each card apart",
  "lint.clicheEntrance": "every slide enters the same way ({enter}): the one entrance that matters is lost among the others",
  "lint.clicheVerdict": "four or more signs of a template: the film is average, not distinctive; turn each into a decision or drop it (docs/visual-design.md)",
  "lint.spotUntilEarly": "spotlight[{index}]: until {until}s comes before the camera arrives at {arrival}s; name a later until, or leave it out to hold to the end of the beat",
  "lint.spotGap": "spotlight[{index}] at {at}s holds until {hold}s and is back at {back}s, but spotlight[{next}] starts at {nextAt}s; the camera needs 0.35s between moves — start the next focus at {start}s or later, or leave out until so the camera goes straight on to the next focus",
  "lint.spotCardOverlap": "spotlight[{index}]: it needs until {until}s{card}, but the next focus starts at {nextAt}s; move the next anchor later, lengthen this beat, or shorten the card",
  "lint.spotCardReason": " for its card to be read",
  "lint.spotCameraChained": "spotlight collides with its overlay — overlay.camera: the move at {at}s starts during the hold of the kept move before it, which ends at {end}s; a kept move hands over after its hold",
  "lint.spotCameraBack": "spotlight collides with its overlay — overlay.camera: the move at {at}s starts before the one before it is back at {end}s; leave 0.35s between moves — start it at {start}s or later",
  "lint.themeUnnamed": "the scene's theme",
  "lint.themeOther": "another theme",
  "cli.fileSlides": "slide file",
  "cli.fileScenes": "scene file",
  "cli.fileScene": "scene file",
  "cli.fileMissing": "{what} not found: {path}",
  "cli.hintSource": "The tool input is a scenario file: agentic-screencast {cmd} --source story.md",
  "cli.hintScene": "Name an existing file: agentic-screencast {cmd} --scene scene.example.json",
  "schema.unknownKind": "unknown kind «{name}»; known: {known}",
  "snapshot.noVariable": "no variable {name}: put it in the environment or in the project's .env",
  "snapshot.duplicateId": "two screens share the id {id}: the second snapshot would overwrite the first",
  "snapshot.loginFailed": "login failed: HTTP {status} — there is nothing to snapshot",
  "verify.psnrFailed": "ffmpeg PSNR failed: {why}",
  "verify.psnrMissing": "ffmpeg did not report PSNR: {why}",
  "fonts.missing": "font file missing from the bundled set: {file}",
  "brand.colour": "expected a colour like #ff5a1f, got «{value}»",
  "brand.noImage": "image not found: {path}",
  "brand.unknownBase": "unknown base theme «{base}»; available: {available}",
  "brand.grey": "no brand colour found: the picture is grey; name the colours with --colors",
  "mix.silentMusic": "music: {file} decodes to no sound",
  "frames.usage": "frames.js <story.md> [--at 0.8|80%|2.4s|b2+0.5] [--scene id] [--out sheet.png]",
  "assemble.shortScene": "scene {id} is shorter than its transitions ({frames} frames, {in}+{out} taken)",
  "capture.webm": "Playwright screencast output must end in .webm",
  "capture.closed": "Cannot capture a closed page",
  "capture.viewport": "Capture requires a fixed page viewport or explicit size",
  "capture.clickStyle": "click: expected ripple | spot | echo",
  "capture.noBox": "Capture target has no visible bounding box",
  "capture.disabled": "Capture target is disabled",
  "capture.finished": "Capture already finished",
  "capture.pageError": "page error during the take: {why}",
  "capture.focusScale": "focus scale must be 1.2–3",
  "capture.nearFocus": "near-focus requires withFocusCard(target, card, action)",
  "capture.clickOutside": "clickAt({x}, {y}) is outside the {width}×{height} viewport",
  "capture.rangeFraction": "Range fraction must be between 0 and 1",
  "capture.rangeInput": "Capture range() requires input[type=range]",
  "capture.rangeBox": "Capture range has no visible bounding box",
  "capture.password": "Do not record password entry; authenticate before capture starts",
  "capture.cardBox": "Focus card target has no visible bounding box",
  "capture.markName": "mark name «{name}»: letters, digits, - and _",
  "capture.markBox": "mark {name}: the element has no visible bounding box",
  "capture.empty": "Empty screencast: {path}",
  "capture.scale": "recordTake scale: expected 1–4 device pixels per CSS pixel",
  "sheet.usage": "sheet.js <clip> [--count 12 | --every 2] [--from s --to s] [--out sheet.png]",
  "sheet.unreadable": "sheet: {clip} is not a readable video",
  "sheet.noDuration": "sheet: {clip} has no duration",
  "sheet.range": "sheet: --to must be later than --from, within the {length}s clip",
  "sheet.numbers": "sheet: --count and --every take numbers",
  "providerCheck.usage": "provider-check.js <program>\nexample: provider-check.js 'python3 /path/provider.py'",
  "audit.vttHeader": "WEBVTT header missing",
  "audit.vttCue": "cue {index} is malformed",
  "voiceCli.usage": "voice-cli.js voices|synth|probe|paths [--voice-json '{…}'] [--text …] [--out …]",
  "transition.colour": "transition colour «{value}» is not #rrggbb",
  "render.morphTarget": "morph target {selector}: expected one visible element, found {found}",
  "cli.unknownTopic": "Unknown help topic: {topic}",
  "cli.newUsage": "agentic-screencast new <genre> [--lang ru] [--format vertical|square] [--out story.md]\ngenres: {genres}",
  "cli.themeUsage": "agentic-screencast theme --from logo.png [--base neutral] | --colors \"#ff5a1f,#1f6fff\"",
  "cli.unknownCommand": "Unknown command: {cmd}",
  "orderCheck.usage": "order-check.js <scenes.json>",
  "audio.ffmpegFailed": "encoded audio: ffmpeg failed: {why}",
  "audio.unreadable": "encoded audio: cannot read AAC loudness and true peak from {file}",
  "audio.invalid": "encoded audio: invalid AAC loudness or true peak from {file}",
  "theme.incomplete": "a theme without a named base must write every token of the contract; missing {count}: {missing}. Start from a named theme instead: {\"preset\":\"neutral\",\"--acc\":\"#ff5a1f\"} (help themes)",
  "theme.unknown": "unknown theme «{name}»; available: {available}",
  "web.ssim": "SSIM of {file} could not be measured: {why}",
  "web.none": "no web format was written",
  "sticker.notFound": "sticker image not found: {file}",
  "sticker.type": "sticker image {file}: use svg, png, jpg, webp, gif or webm",
  "sticker.noFrames": "sticker image {file}: no frames decoded",
  "sticker.emojiFallback": "warning: {hint}; a neutral circle stands in for it",
  "sticker.sceneError": "scene {id}: {why}",
  "film.pipMissing": "pip.file not found: {file}",
  "code.lines": "lines: expected «3-14» or «7», got «{value}»",
  "code.linesOutside": "lines: {value} is outside the {count} lines of the code",
  "code.highlight": "highlight: expected line numbers like «5 7-9», got «{value}»",
  "recorded.unreadable": "the recording cannot be read: {file}\n{why}",
  "recorded.noDuration": "the recording's duration cannot be measured: {file}\n{why}",
  "slides.usage": "slides.js <slides.json> <output-dir>",
  "speechkit.refused": "SpeechKit refused ({status}): {detail}",
  "voice.noKey": "no key {name}: put it in the environment or in the project's .env",
  "stage.stickerImage": "sticker has no image: {target}",
  "stage.primitiveTarget": "overlay target not found on the page: {target}",
  "stage.cameraTarget": "camera target not found on the page: {target}",
};

const ru: Dict = {
  "device.form": "device: ожидается «browser [url]», «phone» или JSON",
  "device.kind": "device.kind: выберите {kinds}",
  "device.url": "device.url: ожидается текст",
  "device.unknown": "device: выберите {kinds}; получено «{kind}»",
  "fit.form": "fit: ожидается contain, cover [x y] или {\"mode\",\"x\",\"y\"}",
  "fit.mode": "fit: выберите contain или cover; получено «{mode}»",
  "fit.coverPoint": "fit: только cover удерживает точку в кадре",
  "fit.share": "{field}: ожидается доля клипа от 0 до 1",
  "speed.form": "speed: ожидается массив JSON с шагами",
  "speed.nonEmpty": "speed: ожидается непустой массив JSON с шагами",
  "speed.holdKind": "остановки",
  "speed.spanKind": "отрезка",
  "speed.unknownProperty": "speed[{index}]: неизвестное свойство «{key}» для {kind}",
  "speed.nonNegative": "{field}: ожидается неотрицательное число секунд",
  "speed.holdRange": "speed[{index}].hold: ожидается от 0,5 до 12 секунд",
  "speed.number": "{field}: ожидается число",
  "speed.rampSeconds": "speed[{index}].ramp: ожидается число секунд исходного клипа",
  "speed.rampHalf": "speed[{index}].ramp: не больше половины отрезка ({half} с)",
  "speed.interpolate": "speed[{index}].interpolate: выберите true, \"motion\" или \"blend\"",
  "speed.from": "speed[{index}].from: ожидается неотрицательная секунда",
  "speed.toAfterFrom": "speed[{index}]: to должно идти после from",
  "speed.rateRange": "speed[{index}].rate: ожидается от 0,2 до 4",
  "speed.rateOne": "speed[{index}].rate: значение 1 ничего не меняет",
  "speed.order": "speed[{index}]: шаги не должны пересекаться и должны идти по порядку",
  "speed.pastClip": "speed: шаг заканчивается в {end} с, за пределами клипа длительностью {duration} с",
  "effects.form": "{what}: ожидаются якоря «b2 | 1.5s» или список JSON",
  "effects.moment": "{where}: неизвестный момент «{at}»; используйте такт (b2, b2.end+0.3), долю (40%) или секунды (1.5s)",
  "effects.range": "{where}: ожидается от {lo} до {hi}",
  "look.unknown": "look: неизвестный вид «{name}»; доступны {available} или JSON",
  "look.form": "look: ожидается имя вида или объект JSON",
  "look.grade": "look.grade: выберите {grades}",
  "look.share": "{field}: ожидается от 0 до 1",
  "look.bars": "look.bars: ожидается соотношение сторон от 1,5 до 3, например 2.39",
  "format.unknown": "format: неизвестный формат «{name}»; доступны {available}",
  "zone.unknown": "zone: неизвестная зона «{name}»; доступны {available}",
  "marks.noFile": "рядом с клипом нет файла .marks.json",
  "marks.unknown": "{where}: неизвестная отметка @{name}; известны: {known}",
  "transition.form": "transition: ожидается имя перехода или объект JSON",
  "transition.unknownKind": "transition: неизвестный вид «{kind}»; доступны {available}",
  "transition.dipColor": "transition.color: цвет задаётся только переходу dip",
  "transition.cutDuration": "transition: у склейки cut нет длительности; она соединяет сцены встык",
  "transition.morphElement": "transition.element: переход morph требует элемент, общий для обеих сцен, например {\"kind\":\"morph\",\"element\":\"#total\"}",
  "transition.onlyMorphElement": "transition.element: только переход morph перемещает элемент",
  "transition.duration": "transition.duration: ожидается от 0,2 до 2 секунд",
  "transition.sound": "transition.sound: ожидается аудиофайл",
  "transition.snap": "transition.snap: ожидается \"music\"",
  "transition.color": "transition.color: выберите black, white или #rrggbb; получено «{color}»",
  "overlay.nonNegativeTime": "{where}: at/hold должны быть неотрицательным числом секунд",
  "overlay.badMoment": "{where}: at «{value}» не является секундой или якорем такта (b2, b2+0.5, b2.end, 40%)",
  "overlay.unresolvedMoment": "{where}: at «{value}» — якорь такта; он вычисляется, когда известны такты речи сцены",
  "overlay.array": "{where}: ожидается массив",
  "overlay.object": "{where}: ожидается объект",
  "overlay.pointerOrder": "overlay.pointer: моменты должны возрастать",
  "overlay.frameFraction": "{where}: ожидается доля кадра от 0 до 1",
  "overlay.frameFractions": "{where}: ожидаются {count} координаты в долях кадра от 0 до 1",
  "overlay.boolean": "{where}: ожидается логическое значение",
  "overlay.trueFalse": "{where}: ожидается true или false",
  "overlay.textLength": "{where}: ожидается текст длиной от 1 до {max} символов",
  "overlay.bodyLength": "{where}: текст должен содержать не более 100 символов",
  "overlay.unknownPosition": "{where}: неизвестное положение",
  "overlay.unknownMotion": "{where}: неизвестное движение",
  "overlay.unknownEdge": "{where}: неизвестный край кадра",
  "overlay.flyEdge": "{where}: вход с края доступен только при motion \"fly\"",
  "overlay.options": "{where}: выберите {options}",
  "overlay.enterExit": "{where}: ожидается от 0,2 до 2,5 секунды",
  "overlay.readHold": "{where}: для чтения текста требуется не меньше {minimum} с",
  "overlay.cardGap": "overlay.cards: оставьте между карточками 0,35 с",
  "overlay.cameraHold": "{where}: требуется не меньше 0,8 с",
  "overlay.cssSelector": "{where}: ожидается CSS-селектор",
  "overlay.cameraArea": "{where}: ожидаются четыре координаты в долях кадра",
  "overlay.oneTargetArea": "{where}: укажите ровно одно из полей target и area",
  "overlay.outsideFrame": "{where}: область выходит за пределы кадра",
  "overlay.cameraScale": "{where}: ожидается 1–3 (1 выделяет цель без наезда)",
  "overlay.moveReturn": "{where}: move/return должны быть от 0,35 до 4 секунд",
  "overlay.blur": "{where}: ожидается 0–24 точек",
  "overlay.dim": "{where}: ожидается доля затемнения темы от 0 до 1",
  "overlay.follow": "{where}: ожидается \"cursor\"",
  "overlay.cameraChained": "overlay.camera: движение в {at} с начинается во время удержания предыдущего наезда, которое кончается в {end} с; продолженный наезд передаёт камеру после удержания",
  "overlay.cameraBack": "overlay.camera: движение в {at} с начинается до возврата предыдущего наезда в {end} с; между движениями нужно 0,35 с — начните его не раньше {start} с",
  "overlay.oneAnchor": "{where}: укажите одно из полей target, area или point",
  "overlay.anchorRequired": "{where}: укажите предмет через target, area или point",
  "overlay.itemGap": "{where}: оставьте между элементами 0,2 с",
  "overlay.oneStickerKind": "{where}: укажите ровно одно из полей emoji, image или text",
  "overlay.stickerSize": "{where}: ожидается 24–480 точек",
  "overlay.rotate": "{where}: ожидается угол от −45 до 45 градусов",
  "overlay.arrowFrom": "{where}: начальную точку задают только стрелке",
  "overlay.twoFrameFractions": "{where}: ожидаются две координаты в долях кадра от 0 до 1",
  "overlay.draw": "{where}: ожидается от 0,2 до 4 секунд",
  "overlay.color": "{where}: ожидается цвет #rrggbb",
  "overlay.wholeNumber": "{where}: ожидается целое число",
  "overlay.count": "{where}: ожидается 4–300",
  "overlay.loupeScale": "{where}: ожидается 1,5–4",
  "overlay.loupeSize": "{where}: ожидается доля ширины кадра от 0,08 до 0,5",
  "overlay.empty": "overlay: добавьте pointer, cards, camera, titles, lower, callouts, stickers, marks, glints, bursts или loupe",
  "spotlight.form": "spotlight: ожидается запись «target @ anchor | …» или JSON",
  "spotlight.jsonObject": "spotlight: ожидается объект JSON, получено «{part}»",
  "spotlight.shortForm": "spotlight: ожидается «target @ anchor» или {…}, получено «{part}»",
  "spotlight.empty": "spotlight: укажите хотя бы один фокус",
  "spotlight.anchor": "{where}: ожидается якорь момента",
  "spotlight.slow": "{where}: ожидается 0,1–0,9 или \"stop\"",
  "spotlight.keepUntil": "{where}: keep оставляет приближение, а until возвращает общий план; укажите одно из них",
  "spotlight.card": "{where}: ожидается {\"title\":…}",
  "spotlight.videoArea": "spotlight[{index}]: в видеосцене фокус задаётся через area, а не через CSS-селектор target",
  "spotlight.overlayCollision": "фокус пересекается с накладкой — {why}",
  "source.notFound": "источник {path}: файл не найден",
  "source.error": "источник {path}: {why}",
  "source.line": "строка {line}: {why}",
  "source.noScenes": "в источнике нет ни одной сцены",
  "source.textOutside": "текст вне сцены",
  "source.badHeader": "заголовок сцены пишется как «## s01 · slides.compare»",
  "source.noSpeech": "сцена {id}: нет реплики",
  "source.required": "сцена {id}: у вида {kind} обязательно поле {names}",
  "source.badField": "поле «{key}» недопустимо у сцены вида {kind}",
  "source.badFilmField": "неизвестное поле ролика: {key}",
  "source.didYouMean": " — возможно, «{name}»?",
  "source.badAnchor": "«{anchor}» не якорь момента; пишут b2, b2.end, b2+0.4, 40% или 1.2s",
  "source.beatOutOfRange": "якорь «{anchor}» указывает дальше речи сцены {id}: в ней тактов {beats}",
  "source.incompatible": "сцена {id}: несовместимые поля: {fields}; оставьте один способ управления временем из каждой пары",
  "source.missingLanguage": "lang {lang}: в сценарии нет текста на языке {lang}; добавьте title.{lang}:, поля вроде overlay.{lang}: и блок реплики [{lang}] в каждой сцене",
  "source.translationHeader": "у сценария с переводами должен быть язык оригинала в шапке: lang: en",
  "source.missingNarration": "сцена {id}: нет реплики [{lang}]; перевод сохраняет число тактов каждой сцены",
  "source.translationBeats": "сцена {id}: в [{lang}] тактов {translated}, в оригинале {original}; якоря вроде b2 называют такт по номеру, поэтому перевод сохраняет число тактов",
  "source.duration": "длительность сцены {id} должна быть больше 0 и не больше 600 секунд",
  "source.trimFrom": "сцена {id}: from должно быть секундой клипа или отметкой дубля @имя",
  "source.trimTo": "сцена {id}: to должно идти после from ({from} с)",
  "source.sceneField": "сцена {id} {field}",
  "source.sceneReason": "сцена {id}: {why}",
  "source.sceneThemeReason": "сцена {id}: тема: {why}",
  "source.markArea": "сцена {id} {field}: для области @{name} запишите прямоугольник элемента через take.mark(\"{name}\", locator)",
  "source.markRecorded": "; записаны: {names}",
  "source.none": "нет",
  "source.autoZoomMarks": "сцена {id}: autoZoom нужны клики из agentic-screencast/capture ({file}.marks.json)",
  "source.stillMarkOnly": "сцена {id} stills: отметка дубля @имя работает только у видеосцены с файлом .marks.json",
  "source.stillsWhere": "сцена {id} stills",
  "source.freezeAt": "freezeAt в сцене {id} должно быть неотрицательной секундой",
  "source.silentDuration": "немой сцене {id} нужно поле duration",
  "source.transitionSound": "transition.sound: файл не найден: {file}",
  "source.captionsPosition": "сцена {id}: captions: выберите {positions} — место субтитров этой сцены",
  "source.speechAt": "сцена {id}: speechAt: ожидается 0–10 секунд от начала сцены",
  "source.loudness": "loudness: ожидается уровень LUFS от -30 до -8",
  "source.audio": "audio: ожидается false (ролик без звуковой дорожки) или true",
  "source.motionBlurSamples": "motionBlur.samples: ожидается 2–16",
  "source.motionBlurShutter": "motionBlur.shutter: ожидается доля кадра от 0 до 1",
  "source.emojiDir": "emoji: ожидается {\"dir\":\"<папка>\"}",
  "source.badFormat": "--format: {why}",
  "source.formatReframe": "--format {format}: сценарий уже имеет формат {current}; кадрировать можно только горизонтальный сценарий",
  "source.letterboxReframe": "полосы каше не рисуются при сборке горизонтального сценария в формате {format}",
  "source.lookBars": "look.bars: полосы каше требуют горизонтального кадра, этот ролик имеет размер {width}×{height}; выберите вид без полос, например look: cinematic",
  "source.jsonObject": "{field}: ожидается объект JSON",
  "source.jsonList": "{field}: ожидается список JSON",
  "source.unknownProperty": "{field}: неизвестное свойство «{key}»",
  "source.options": "{field}: выберите {options}",
  "source.fadeRange": "fade{part}: ожидается от 0 до 3 секунд",
  "source.fadeForm": "fade: ожидается none, число секунд или {\"in\":…,\"out\":…}",
  "source.captionsLook": "captions.look: выберите outline (текст с тёмной обводкой, по умолчанию) или plate (плотная плашка)",
  "source.captionsSize": "captions.size: ожидается число от 0,8 до 1,6 (обычный размер — 1)",
  "source.captionsStyle": "captions.style: ожидается bar | subtitle | karaoke",
  "source.booleanField": "{field}: ожидается true или false",
  "source.pipFile": "pip.file: ожидается видеофайл",
  "source.pipCorner": "pip.corner: ожидается bottom-right | bottom-left | top-right | top-left",
  "source.pipSize": "pip.size: ожидается доля ширины кадра от 0,08 до 0,45",
  "source.pipTime": "pip.{field}: ожидаются секунды ролика",
  "source.progressLabel": "progress.label: ожидается edge (рядом с полосой у края кадра) или zone (у края безопасной зоны)",
  "source.progressPosition": "progress.position: ожидается top или bottom",
  "source.musicFile": "music.file: ожидается аудиофайл",
  "source.fileMissing": "{field}: файл не найден: {file}",
  "source.range": "{field}: ожидается от {low} до {high}",
  "source.musicMoment": "music.at: неизвестный момент «{at}»; используйте такт (b2, b2.end+0.3), долю (40%) или секунды (1.5s)",
  "source.musicStop": "music.{field}: остановка ничего не воспроизводит",
  "source.musicFileOrStop": "music.file: ожидается аудиофайл или stop",
  "source.expectedObject": "{field}: ожидается объект",
  "source.unexpectedMoment": "{field}: неизвестный момент «{at}»",
  "source.audioFile": "{field}: ожидается аудиофайл",
  "source.sfxGain": "{field}: ожидается от -30 до 12 дБ",
  "source.autoZoomFollow": "autoZoom.follow: ожидается \"cursor\"",
  "source.autoZoomScale": "autoZoom.scale: ожидается больше 1 и не больше 3",
  "source.autoZoomHold": "autoZoom.hold: ожидается от 0,8 до 6 секунд",
  "source.autoZoomSize": "autoZoom.size: ожидается доля кадра от 0,1 до 0,8",
  "stills.step": "{where}: «{at}» — шаг должен быть от 0,25 до 10 секунд",
  "stills.moment": "{where}: «{at}» не является моментом; используйте b2, b2+0.5, b2.end, 80%, 1.5, @mark или every 1s",
  "stills.empty": "{where}: укажите хотя бы один момент",
  "slides.imageMissing": "сцена {id}: изображение не найдено: {file}",
  "slides.imageType": "сцена {id}: изображение должно быть png, jpg, webp, gif, svg или avif: {file}",
  "slides.imageSize": "сцена {id}: не удалось определить размер изображения {file}",
  "slides.where": "сцена {id}: {field}",
  "slides.pair": "{where}: ожидается два числа от {low} до {high}, получено «{value}»",
  "slides.column": "сцена {id}: колонка описывается как «Заголовок :: содержимое»",
  "slides.dataMissing": "сцена {id}: файл данных не найден: {file}",
  "slides.chartRows": "сцена {id}: data: для диаграммы нужно 2–24 строки «подпись,значение», получено {count}",
  "slides.chartRow": "сцена {id}: строка данных {row}: ожидается «подпись,значение», получено «{value}»",
  "slides.chartValue": "сцена {id}: строка данных {row}: диаграмма показывает значения от нуля, получено {value}",
  "slides.options": "сцена {id}: {field}: выберите {options}",
  "slides.peak": "сцена {id}: peak: выберите max, none, номер строки 1–{count} или подпись из данных, получено «{value}»",
  "slides.background": "сцена {id}: background: неизвестно «{value}»{hint}; доступны: {available}",
  "slides.textStyle": "сцена {id}: text: выберите {options}, получено «{value}»",
  "slides.textCount": "сцена {id}: text: укажите не больше двух стилей — для заголовка и основного текста",
  "slides.codeMissing": "сцена {id}: файл кода не найден: {file}",
  "slides.cps": "сцена {id}: cps: ожидается 5–400 знаков в секунду",
  "slides.labels": "сцена {id}: labels: ожидается две подписи «Before | After»",
  "slides.panelForm": "{where}: ожидается «x y w h @ глубина», например «0.05 0.1 0.4 0.5 @ 0.8»",
  "slides.panelOutside": "{where}: панель находится за пределами изображения",
  "slides.panelDepth": "{where}: depth должно быть от 0 до 1, где 1 — ближняя панель",
  "slides.panelCount": "сцена {id}: panels: не больше 8",
  "script.summary": "Сцен: {scenes}. Тактов: {beats}. Слов в репликах: {words}.",
  "provider.unknown": "неизвестный поставщик «{name}»; известны: {known}\n"
    + "посторонний объявляется в шапке ролика строкой providers: {\"имя\": \"команда\"}",
  "provider.unknownKind": "поставщик «{provider}» не знает вида «{kind}»; он предлагает: {kinds}",
  "provider.notFound": "поставщик «{command}»: программа не найдена",
  "provider.failed": "поставщик «{command}» отказал (код {code}): {said}",
  "provider.notJson": "поставщик «{command}» ответил на {what} не JSON: {said}",
  "provider.noFile": "поставщик «{command}» не назвал файл страницы",
  "provider.cannotDraw": "поставщик «{name}» не умеет порождать страницу и не назвал готовый файл",
  "engine.unnamed": "в данных голоса не назван движок",
  "engine.notFound": "движок «{command}»: программа не найдена",
  "engine.failed": "движок «{command}» отказал (код {code}): {said}",
  "engine.notJson": "движок «{command}» ответил на {what} не JSON: {said}",
  "build.noPage": "нет подложки: {path}",
  "build.noScene": "в этом ролике нет сцены «{id}»",
  "build.sceneCached": "[{at}/{of}] {id}: взята из кэша",
  "build.sceneRender": "[{at}/{of}] {id}: рисую {frames} кадров…",
  "build.sceneVideo": "[{at}/{of}] {id}: привожу вставку к кадру ролика…",
  "build.done": "готово: {out} — {secs} с, {w}×{h}, {fps} кадров, сцен {scenes}",
  "build.unknownVoice": "неизвестно",
  "build.legible": "сцена {id}: текст цели {target} имеет {px} px в кадре на {at} с при нужных для телефона {min} px; приблизьте цель (scale), пройдите вдоль широкой области (pan) или используйте лупу",
  "build.small": "сцена {id}: текст меньше читаемых на телефоне {min} px — {lines}; сократите его или дайте ему отдельную сцену с более крупным шрифтом",
  "build.cut": "сцена {id}: кадр обрезает текст цели {target} на {at} с — {text}; уменьшите масштаб, пройдите вдоль текста (pan) или выберите меньшую область",
  "build.overflow": "сцена {id}: слайд выходит за свою область на {px} px сетки даже при уменьшении до 72%; разделите его на две сцены или сократите пункты",
  "build.stills": "контрольных кадров: {count}; каталог: {path}",
  "build.failed": "сборка не удалась: {said}",
  "build.encodedPeakExceeded": "пиковый уровень готового AAC {measured} dBTP выше предела {limit} dBTP после коррекции",
  "build.auditIssue": "проверка готового MP4: {code} ({details})",
  "build.jobs": "AGENTIC_SCREENCAST_JOBS: требуется целое число от 1, получено «{raw}»",
  "build.voicePitch": "voice.pitch: укажите полутоны от -12 до 12 (понижение голоса — отрицательное число), но не 0",
  "build.sceneError": "сцена {id}: {why}",
  "build.speedHint": "; секунды speed считаются от начала куска (from: {from} с исходника), а не от начала исходного файла",
  "build.trimPast": "сцена {id}: from {from} с выходит за конец клипа ({whole} с)",
  "build.autoZoomCollision": "сцена {id}: autoZoom конфликтует с накладкой — {why}",
  "build.loupeTarget": "сцена {id}: лупа над клипом называет область или точку, а не CSS-селектор",
  "build.freezePast": "freezeAt выходит за конец клипа сцены {id}",
  "build.cameraEmpty": "сцена {id}: область камеры [{area}] почти пуста (контраст {contrast} < {minimum}); наведите её на предмет",
  "build.sfxTempo": "sfx в момент {at}: музыкальной доле нужен темп; ритм не найден, поэтому укажите music.bpm в шапке",
  "build.morphVideo": "сцена {id}: морф соединяет две нарисованные сцены (слайды или страницы), а не клип",
  "build.morphElement": "сцена {id}: элемент морфа {element}: {why}",
  "frames.source": "источник {path}: {why}",
  "frames.conflict": "--scene и --except нельзя использовать вместе",
  "frames.noScene": "нет сцены «{id}»; сцены: {scenes}",
  "frames.badAt": "--at {at}: укажите долю сцены (0.8 или 80%), секунды (2.4s) или момент речи (b2, b2+0.5, b2.end)",
  "frames.badOut": "--out: лист кадров должен быть PNG; назовите его с .png, например --out {example}",
  "frames.noFrame": "кадр не записан",
  "frames.empty": "ровная пустая полоса занимает {percent}% высоты кадра на {at} с: там нет предмета; заполните кадр продуктом или его доказательством либо растяните содержимое по высоте (align, правило 58)",
  "frames.emptyLine": "frames: сцена {id}: {message}",
  "frames.sheetClip": "клип {at} с",
  "frames.sheetEstimated": "такты оценены по тексту",
  "speech.noRules": "нет набора правил чтения «{name}»: ни среди поставляемых, ни по пути {path}",
  "record.notBuilt": "страница записи не собрана: выполните npm run build в каталоге инструмента",
  "record.noScene": "нет сцены {id}",
  "record.noRecording": "записи нет",
  "record.unreadable": "запись не читается: {why}",
  "record.noDuration": "у записи не определяется длительность",
  "record.noFile": "нет такого файла",
  "record.started": "интерфейс записи: {url}",
  "record.store": "хранилище записей: {path}",
  "record.stop": "остановить: Ctrl+C",
  "lint.overloadedLine": "такт {beat} содержит {chars} знаков — больше двух строк субтитров ({limit}); разделите его на два такта",
  "lint.untranslatedFilm": "у названия ролика нет перевода на {lang}; добавьте title.{lang}: в шапку",
  "lint.untranslatedScene": "строка {line}: поле {field} видно в кадре, но у него нет перевода на {lang}; добавьте {field}.{lang}:",
  "lint.cardCaption": "карточка «{title}» в момент {at} с накладывается на подпись; удержите её во время наезда камеры или перенесите слова в озвучку",
  "lint.titleCard": "титр «{title}» и карточка «{card}» одновременно видны в кадре; разведите их по времени",
  "lint.titleOverInterface": "титр «{title}» стоит поверх шапки интерфейса; поместите его в центре, где кадр затемняется под текстом",
  "lint.speedRangeSource": "переигрывание заканчивается в {end} с, но показанный кусок длится {piece} с; секунды speed отсчитываются от начала куска (с {from} с исходника), поэтому укажите {local} с вместо {end} с",
  "lint.speedRange": "переигрывание заканчивается в {end} с, но показанный кусок длится {piece} с; завершите speed не позже {piece} с либо удлините кусок полем to",
  "lint.captionsTopProgress": "субтитры и полоса хода с названием части стоят сверху; перенесите один из них вниз (progress.position или captions)",
  "lint.takeSmallRecorded": "клип имеет размер {clip} и увеличивается в {scale} раза до кадра {frame}, поэтому становится размытым; запишите его в размере кадра — recordTake({ viewport, scale }) снимает телефонную вёрстку в пикселях устройства",
  "lint.takeSmallExternal": "клип имеет размер {clip} и увеличивается в {scale} раза до кадра {frame}, поэтому становится размытым; возьмите исходный файл большего размера, если он есть",
  "lint.pieceCrossesMark": "кусок дубля {from}–{end} с пересекает отметку @{mark} ({at} с), которую сцена не называет — там начинается следующий план; завершите кусок полем to: @{mark}",
  "lint.emptyArea": "в {percent}% кадров сцены не меньше трети изображения занимает ровная заливка — пустой заполнитель или уехавшая страница; заполните кадр предметом, а субтитры перенесите вместо добавления пустого поля (правило 53)",
  "lint.sceneJump": "экран резко меняется через {at} с после начала куска без отметки дубля — навигация внутри плана; завершите кусок у отметки перед ней (правило 54)",
  "lint.firstTransition": "у первой сцены нет предыдущей, поэтому её переход не воспроизводится; перенесите переход на вторую сцену или удалите",
  "lint.takeThemeOld": "дубль {file} записан до сохранения темы; его курсор, клики и карточки могут не совпадать с темой сцены {wanted}; для уверенности переснимите его с theme: {hint}",
  "lint.takeThemeMismatch": "дубль {file} записан в теме {recorded}, а сцена использует {wanted}; переснимите его с theme: {hint}",
  "lint.pushCrop": "наезд в момент {at} увеличивает кадр в {scale} раза, но его область помещается целиком только до {fit}; уменьшите масштаб или задайте меньшую область",
  "lint.loupeScale": "лупа в момент {at} с увеличивает в {actual} раза вместо {asked}: область не помещается в линзу предельного размера; задайте меньшую область",
  "lint.stillPage": "страница неподвижна {duration} с; добавьте движение камеры или фокус, следующий за озвучкой",
  "lint.stillVideo": "замороженный кадр без движения камеры или подсветки выглядит паузой; приблизьте предмет, названный в озвучке",
  "lint.stillHold": "spotlight[{index}] удерживает фокус с {from} с в течение {hold} с, пока клип неподвижен {still} с; пройдите этот участок быстрее через speed: [{\"from\":{from},\"to\":{to},\"rate\":2}] или закончите фокус раньше через until",
  "lint.typingTooFast": "поле {field} ({chars} знаков) набирается с {from} с и должно завершиться до конца сцены в {end} с — {pace}; продлите сцену хотя бы до {fits} с или сократите {field}",
  "lint.typingNoTime": "времени не осталось",
  "lint.typingRate": "{rate} знаков в секунду — слишком быстро для чтения",
  "lint.numberSource": "слайд {kind} показывает числа без источника и даты; добавьте note: <источник>, <дата или месяц и год> (правила 12 и 56)",
  "lint.longScene": "около {duration} с в одной сцене; разделите её на планы с одной мыслью каждый (после {limit} с нить объяснения теряется)",
  "lint.clicheHit": "в ролике без жанра трейлера есть вспышка или встряска: удар без жанрового основания выглядит шумом (правило 63)",
  "lint.clicheGrain": "плёночное зерно в ролике без жанра трейлера увеличивает размер файла; используйте его для снятого материала трейлера (правило 63)",
  "lint.clicheSparkles": "{count} всплесков и бликов: больше двух за ролик перестают означать успех",
  "lint.clicheTransitions": "{count} видов перехода ({kinds}): выберите один или два по смыслу склейки (правило 52)",
  "lint.clicheBackground": "северное сияние, сетка, боке или частицы без сюжетной причины выглядят шаблоном; используйте спокойный фон или покажите причину движения",
  "lint.clicheAddress": "браузерная рамка без настоящего адреса или с адресом-заглушкой: указывайте реальный адрес либо отмечайте изображение как макет (правило 60)",
  "lint.clicheKicker": "надзаголовок слайда написан заглавными буквами; оставьте такой набор карте трейлера или названию ролика",
  "lint.clicheEmoji": "эмодзи вместо различимых иконок возможностей выглядят шаблоном; покажите доказательство или отличающий факт для каждой карточки",
  "lint.clicheEntrance": "каждый слайд появляется одинаково ({enter}), поэтому значимый вход теряется среди остальных",
  "lint.clicheVerdict": "четыре и более признака шаблона: ролик выглядит обычным; обоснуйте каждый приём или уберите его (docs/visual-design.md)",
  "lint.spotUntilEarly": "spotlight[{index}]: until задан на {until} с до прихода камеры в {arrival} с; назовите более поздний момент или уберите until, чтобы держать фокус до конца такта",
  "lint.spotGap": "spotlight[{index}] начинается в {at} с, держится до {hold} с и возвращается в {back} с, а spotlight[{next}] начинается в {nextAt} с; между движениями камеры нужно 0,35 с — начните следующий фокус не раньше {start} с или уберите until для прямого перехода",
  "lint.spotCardOverlap": "spotlight[{index}] требует удержания до {until} с{card}, а следующий фокус начинается в {nextAt} с; сдвиньте его якорь, удлините такт или сократите карточку",
  "lint.spotCardReason": " для чтения карточки",
  "lint.spotCameraChained": "фокус пересекается с накладкой — overlay.camera: движение в {at} с начинается во время удержания предыдущего наезда, которое кончается в {end} с; продолженный наезд передаёт камеру после удержания",
  "lint.spotCameraBack": "фокус пересекается с накладкой — overlay.camera: движение в {at} с начинается до возврата предыдущего наезда в {end} с; между движениями нужно 0,35 с — начните его не раньше {start} с",
  "lint.themeUnnamed": "тема этой сцены",
  "lint.themeOther": "другая тема",
  "cli.fileSlides": "файл слайдов",
  "cli.fileScenes": "файл сцен",
  "cli.fileScene": "файл сцены",
  "cli.fileMissing": "{what} не найден: {path}",
  "cli.hintSource": "Вход инструмента — файл сценария: agentic-screencast {cmd} --source story.md",
  "cli.hintScene": "Укажите существующий файл: agentic-screencast {cmd} --scene scene.example.json",
  "schema.unknownKind": "неизвестный вид «{name}»; известны: {known}",
  "snapshot.noVariable": "нет переменной {name}: положите её в окружение или в .env проекта",
  "snapshot.duplicateId": "два экрана с одним id: {id} — второй снимок затёр бы первый",
  "snapshot.loginFailed": "вход не прошёл: HTTP {status} — снимать нечего",
  "verify.psnrFailed": "ffmpeg не посчитал PSNR: {why}",
  "verify.psnrMissing": "ffmpeg не сообщил PSNR: {why}",
  "fonts.missing": "в поставляемом наборе нет файла шрифта: {file}",
  "brand.colour": "ожидался цвет вида #ff5a1f, получено «{value}»",
  "brand.noImage": "картинка не найдена: {path}",
  "brand.unknownBase": "неизвестная базовая тема «{base}»; доступны: {available}",
  "brand.grey": "фирменный цвет не найден: картинка серая; назовите цвета ключом --colors",
  "mix.silentMusic": "music: в {file} не нашлось звука",
  "frames.usage": "frames.js <story.md> [--at 0.8|80%|2.4s|b2+0.5] [--scene id] [--out лист.png]",
  "assemble.shortScene": "сцена {id} короче своих переходов ({frames} кадров, занято {in}+{out})",
  "capture.webm": "файл записи Playwright должен кончаться на .webm",
  "capture.closed": "закрытую страницу не записать",
  "capture.viewport": "для записи нужен постоянный размер окна страницы или явный size",
  "capture.clickStyle": "click: ожидалось ripple | spot | echo",
  "capture.noBox": "у цели записи нет видимой рамки",
  "capture.disabled": "цель записи недоступна (disabled)",
  "capture.finished": "запись уже закончена",
  "capture.pageError": "ошибка страницы во время дубля: {why}",
  "capture.focusScale": "scale у focus — от 1.2 до 3",
  "capture.nearFocus": "near-focus требует withFocusCard(target, card, action)",
  "capture.clickOutside": "clickAt({x}, {y}) вне окна {width}×{height}",
  "capture.rangeFraction": "доля range — от 0 до 1",
  "capture.rangeInput": "range() работает только с input[type=range]",
  "capture.rangeBox": "у ползунка range нет видимой рамки",
  "capture.password": "ввод пароля не записывается: войдите до начала записи",
  "capture.cardBox": "у цели карточки фокуса нет видимой рамки",
  "capture.markName": "имя отметки «{name}»: буквы, цифры, - и _",
  "capture.markBox": "отметка {name}: у элемента нет видимой рамки",
  "capture.empty": "запись пуста: {path}",
  "capture.scale": "scale у recordTake: от 1 до 4 точек экрана на CSS-пиксель",
  "sheet.usage": "sheet.js <клип> [--count 12 | --every 2] [--from с --to с] [--out лист.png]",
  "sheet.unreadable": "sheet: {clip} не читается как видео",
  "sheet.noDuration": "sheet: у {clip} нет длительности",
  "sheet.range": "sheet: --to должен быть позже --from и внутри клипа длиной {length} с",
  "sheet.numbers": "sheet: --count и --every принимают числа",
  "providerCheck.usage": "provider-check.js <программа>\nпример: provider-check.js 'python3 /путь/provider.py'",
  "audit.vttHeader": "нет заголовка WEBVTT",
  "audit.vttCue": "глава {index} записана с ошибкой",
  "voiceCli.usage": "voice-cli.js voices|synth|probe|paths [--voice-json '{…}'] [--text …] [--out …]",
  "transition.colour": "цвет перехода «{value}» — не #rrggbb",
  "render.morphTarget": "цель morph {selector}: ожидался один видимый элемент, найдено {found}",
  "cli.unknownTopic": "нет такой темы справки: {topic}",
  "cli.newUsage": "agentic-screencast new <жанр> [--lang ru] [--format vertical|square] [--out story.md]\nжанры: {genres}",
  "cli.themeUsage": "agentic-screencast theme --from логотип.png [--base neutral] | --colors \"#ff5a1f,#1f6fff\"",
  "cli.unknownCommand": "нет такой команды: {cmd}",
  "orderCheck.usage": "order-check.js <файл-сцен.json>",
  "audio.ffmpegFailed": "закодированный звук: ffmpeg не справился: {why}",
  "audio.unreadable": "закодированный звук: громкость и истинный пик AAC в {file} не читаются",
  "audio.invalid": "закодированный звук: негодная громкость или истинный пик AAC в {file}",
  "theme.incomplete": "тема без названной основы обязана задать каждый токен договора; не хватает {count}: {missing}. Начните от названной темы: {\"preset\":\"neutral\",\"--acc\":\"#ff5a1f\"} (help themes)",
  "theme.unknown": "неизвестная тема «{name}»; доступны: {available}",
  "web.ssim": "SSIM у {file} не измерить: {why}",
  "web.none": "не записан ни один веб-формат",
  "sticker.notFound": "картинка стикера не найдена: {file}",
  "sticker.type": "картинка стикера {file}: нужен svg, png, jpg, webp, gif или webm",
  "sticker.noFrames": "картинка стикера {file}: кадры не читаются",
  "sticker.emojiFallback": "предупреждение: {hint}; вместо него стоит нейтральный кружок",
  "sticker.sceneError": "сцена {id}: {why}",
  "film.pipMissing": "pip.file не найден: {file}",
  "code.lines": "lines: ожидалось «3-14» или «7», получено «{value}»",
  "code.linesOutside": "lines: {value} вне {count} строк кода",
  "code.highlight": "highlight: ожидались номера строк вида «5 7-9», получено «{value}»",
  "recorded.unreadable": "запись не читается: {file}\n{why}",
  "recorded.noDuration": "длительность записи не измеряется: {file}\n{why}",
  "slides.usage": "slides.js <файл-слайдов.json> <каталог-вывода>",
  "speechkit.refused": "SpeechKit отказал ({status}): {detail}",
  "voice.noKey": "нет ключа {name}: положите его в окружение или в .env проекта",
  "stage.stickerImage": "у стикера нет картинки: {target}",
  "stage.primitiveTarget": "цель накладки не найдена на странице: {target}",
  "stage.cameraTarget": "цель камеры не найдена на странице: {target}",
};

export const DICTS: Record<Lang, Dict> = { en, ru };

/** Язык, на котором инструмент говорит в этом запуске. */
export function langOf(named?: string): Lang {
  const want = (named ?? process.env.AGENTIC_SCREENCAST_LANG ?? process.env.LANG ?? "")
    .toLowerCase().slice(0, 2);
  return want === "ru" ? "ru" : "en";
}

let current: Lang = langOf();

/** Назначить язык — например тот, что объявил ролик. */
export const useLang = (named?: string): void => { current = langOf(named); };

/**
 * Сообщение по ключу. Подстановки — пары в фигурных скобках. Ключ,
 * которого в словаре нет, возвращается как есть: это видно в выводе
 * и чинится, а молчание — нет.
 */
export function msg(key: string, vars: Record<string, string | number> = {}): string {
  const text = DICTS[current][key] ?? DICTS.en[key] ?? key;
  return text.replace(/\{(\w+)\}/g, (_, name: string) =>
    (Object.hasOwn(vars, name) ? String(vars[name]) : `{${name}}`));
}
