// Именованные темы оформления: один выбор вместо двух десятков переменных.
//
// Почему это живёт в продукте, а не в сценарии. Оформление ролика — это
// согласованный набор: фон, гамма текста, форма карточек, подписи, заставка,
// слой композиции. Набранный по одной переменной вручную, он расходится
// сам с собой — подпись из одной палитры, выноска из другой, — и кадр
// выглядит неряшливо, сколько бы времени на него ни потратили. Тема
// называется одним словом и задаёт весь набор сразу.
//
// Тема — это ПЕРЕМЕННЫЕ, а не правила: их толкует тот, кто рисует, —
// страница слайдов и слой композиции. Поэтому добавление темы не трогает
// ни разметку, ни рендер.

/** Переменные оформления: имя без ведущих дефисов допускается. */
export type ThemeVars = Record<string, string>;

/**
 * Договор темы: какие переменные она обязана задать.
 *
 * Список нужен не для красоты: тема, забывшая переменную, молча отдаёт
 * кадр с чужим цветом из умолчания правил, и заметно это только глазами
 * на готовом ролике. Проверка сверяет каждую тему с этим списком.
 */
export const THEME_KEYS = [
  // страница слайдов: палитра, шрифты, живой фон
  "--bg", "--glow", "--ink", "--body", "--mut", "--line", "--card", "--node", "--node-line", "--acc",
  "--acc2", "--bad", "--good", "--bad-line", "--sans", "--mono", "--display", "--display-weight", "--display-tracking", "--display-case", "--bg-motion",
  "--bg-intensity", "--kicker-case", "--kicker-tracking", "--sub-font", "--sub-weight",
  // формы и шкала отступов слайдов (сетка в точках)
  "--radius-sm", "--radius-md", "--radius-lg", "--radius-xl", "--radius-pill", "--hairline", "--rule-size",
  "--rail-size", "--ring-size", "--dot-ring", "--ring-width", "--chart-axis", "--chart-line-width",
  "--chart-dot-ring", "--ba-line-width", "--code-hl-bar", "--space-xs", "--space-s", "--space-m",
  "--space-l", "--space-xl", "--space-2xl", "--space-3xl", "--dv-url-pad", "--dv-rim-width",
  // блоки слайдов: код, «было/стало», тени, параллакс, призыв, перспектива
  "--code-name", "--code-gutter", "--code-kw", "--code-str", "--code-num", "--code-fn", "--code-type",
  "--code-com", "--code-pun", "--code-bg", "--code-bar", "--code-line", "--code-ink", "--ba-line",
  "--ba-knob-bg", "--ba-knob-ink", "--ba-label-bg", "--ba-label-ink", "--shadow-3", "--shadow-color",
  "--px-edge", "--px-dim", "--cta-sheen", "--pv-glint", "--pv-glint-strength", "--pv-reflection",
  "--pv-shade", "--orbit-glow", "--step-halo", "--dot-halo", "--code-caret", "--code-hl-shadow",
  "--cta-glow", "--ba-line-shadow",
  // рамки устройств и кнопки окна
  "--dv-shadow", "--dv-bar-tint", "--dv-bezel", "--dv-rim", "--dv-island", "--dv-browser-shadow",
  "--sc-traffic-1", "--sc-traffic-2", "--sc-traffic-3",
  // переходы между сценами
  "--tr-seam", "--tr-iris", "--tr-flash", "--tr-fill", "--tr-shade",
  // слой поверх кадра: формы (единицы кадра --u) и доли кадра для кода
  "--sc-glint-blend", "--sc-card-radius", "--sc-radius", "--sc-sub-radius", "--sc-hairline",
  "--sc-cap-bar-size", "--sc-spot-radius", "--sc-spot-width", "--sc-cursor-size", "--sc-keys-radius",
  "--sc-keys-size", "--sc-cursor-line-width", "--sc-sub-pad-y", "--sc-badge-pad-x", "--sc-badge-pad-y",
  "--sc-keys-pad", "--sc-pad-x", "--sc-pad-y", "--sc-edge", "--sc-mark-width", "--sc-mark-head",
  "--sc-mark-wobble", "--sc-arrow-width", "--sc-arrow-head", "--sc-spark-width", "--sc-ripple-size",
  "--sc-scrim-blur", "--sc-loupe-ring-width", "--sc-pip-ring-width", "--sc-progress-size",
  // слой поверх любого материала: цвета
  "--sc-spot", "--sc-dim", "--sc-accent-soft", "--sc-fade", "--sc-cap-bg", "--sc-cap-line", "--sc-cap-ink",
  "--sc-cap-bar", "--sc-card-bg", "--sc-card-line", "--sc-card-ink", "--sc-card-body", "--sc-card-accent",
  "--sc-card-shadow", "--sc-card-accent-solid", "--sc-lower-bar", "--sc-sub-ink", "--sc-sub-bg", "--sc-sub-outline-ink", "--sc-sub-outline", "--sc-sub-accent", "--sc-sub-outline-shadow",
  "--sc-karaoke-ink", "--sc-karaoke-bg", "--sc-badge-ink", "--sc-badge-bg", "--sc-badge-shadow",
  "--sc-scrim", "--sc-title-ink", "--sc-title-shadow", "--sc-cap-shadow", "--sc-sticker-shadow", "--sc-mark",
  "--sc-glint", "--sc-confetti", "--sc-spark", "--sc-spark-2", "--sc-loupe-ring", "--sc-cursor-fill",
  "--sc-cursor-line", "--sc-cursor-shadow", "--sc-ripple-ring", "--sc-ripple", "--sc-ripple-glint",
  "--sc-keys-ink", "--sc-keys-bg", "--sc-keys-line", "--sc-keys-shadow", "--sc-progress",
  "--sc-progress-track", "--sc-pip-ring", "--sc-letterbox", "--sc-spot-shadow", "--sc-karaoke-halo",
  "--sc-ripple-shadow",
] as const;

/** Токены договора по группам — для справки `help themes`. */
export const THEME_GROUPS: ReadonlyArray<readonly [string, readonly string[]]> = [
  ["slide page: palette, fonts, live background", [
    "--bg", "--glow", "--ink", "--body", "--mut", "--line", "--card", "--node", "--node-line", "--acc",
    "--acc2", "--bad", "--good", "--bad-line", "--sans", "--mono", "--display", "--display-weight", "--display-tracking", "--display-case", "--bg-motion",
    "--bg-intensity",
  ]],
  ["type of kickers and subtitles: the kicker's case and tracking, the subtitle face and weight", [
    "--kicker-case", "--kicker-tracking", "--sub-font", "--sub-weight",
  ]],
  ["slide shapes and spacing scale (grid points)", [
    "--radius-sm", "--radius-md", "--radius-lg", "--radius-xl", "--radius-pill", "--hairline", "--rule-size",
    "--rail-size", "--ring-size", "--dot-ring", "--ring-width", "--chart-axis", "--chart-line-width",
    "--chart-dot-ring", "--ba-line-width", "--code-hl-bar", "--space-xs", "--space-s", "--space-m",
    "--space-l", "--space-xl", "--space-2xl", "--space-3xl", "--dv-url-pad", "--dv-rim-width",
  ]],
  ["slide blocks: code, before/after, shadows, parallax, call to action, perspective", [
    "--code-name", "--code-gutter", "--code-kw", "--code-str", "--code-num", "--code-fn", "--code-type",
    "--code-com", "--code-pun", "--code-bg", "--code-bar", "--code-line", "--code-ink", "--ba-line",
    "--ba-knob-bg", "--ba-knob-ink", "--ba-label-bg", "--ba-label-ink", "--shadow-3", "--shadow-color",
    "--px-edge", "--px-dim", "--cta-sheen", "--pv-glint", "--pv-glint-strength", "--pv-reflection",
    "--pv-shade", "--orbit-glow", "--step-halo", "--dot-halo", "--code-caret", "--code-hl-shadow",
    "--cta-glow", "--ba-line-shadow",
  ]],
  ["device frames and window buttons", [
    "--dv-shadow", "--dv-bar-tint", "--dv-bezel", "--dv-rim", "--dv-island", "--dv-browser-shadow",
    "--sc-traffic-1", "--sc-traffic-2", "--sc-traffic-3",
  ]],
  ["transitions between scenes", [
    "--tr-seam", "--tr-iris", "--tr-flash", "--tr-fill", "--tr-shade",
  ]],
  ["overlay shapes (frame units --u) and frame fractions read by code", [
    "--sc-glint-blend", "--sc-card-radius", "--sc-radius", "--sc-sub-radius", "--sc-hairline",
    "--sc-cap-bar-size", "--sc-spot-radius", "--sc-spot-width", "--sc-cursor-size", "--sc-keys-radius",
    "--sc-keys-size", "--sc-cursor-line-width", "--sc-sub-pad-y", "--sc-badge-pad-x", "--sc-badge-pad-y",
    "--sc-keys-pad", "--sc-pad-x", "--sc-pad-y", "--sc-edge", "--sc-mark-width", "--sc-mark-head",
    "--sc-mark-wobble", "--sc-arrow-width", "--sc-arrow-head", "--sc-spark-width", "--sc-ripple-size",
    "--sc-scrim-blur", "--sc-loupe-ring-width", "--sc-pip-ring-width", "--sc-progress-size",
  ]],
  ["overlay colours: captions, titles, cards, spotlight, marks, cursor, keys, progress", [
    "--sc-spot", "--sc-dim", "--sc-accent-soft", "--sc-fade", "--sc-cap-bg", "--sc-cap-line", "--sc-cap-ink",
    "--sc-cap-bar", "--sc-card-bg", "--sc-card-line", "--sc-card-ink", "--sc-card-body", "--sc-card-accent",
    "--sc-card-shadow", "--sc-card-accent-solid", "--sc-lower-bar", "--sc-sub-ink", "--sc-sub-bg", "--sc-sub-outline-ink", "--sc-sub-outline", "--sc-sub-accent", "--sc-sub-outline-shadow",
    "--sc-karaoke-ink", "--sc-karaoke-bg", "--sc-badge-ink", "--sc-badge-bg", "--sc-badge-shadow",
    "--sc-scrim", "--sc-title-ink", "--sc-title-shadow", "--sc-cap-shadow", "--sc-sticker-shadow", "--sc-mark",
    "--sc-glint", "--sc-confetti", "--sc-spark", "--sc-spark-2", "--sc-loupe-ring", "--sc-cursor-fill",
    "--sc-cursor-line", "--sc-cursor-shadow", "--sc-ripple-ring", "--sc-ripple", "--sc-ripple-glint",
    "--sc-keys-ink", "--sc-keys-bg", "--sc-keys-line", "--sc-keys-shadow", "--sc-progress",
    "--sc-progress-track", "--sc-pip-ring", "--sc-letterbox", "--sc-spot-shadow", "--sc-karaoke-halo",
    "--sc-ripple-shadow",
  ]],
];

/**
 * Токены договора, которые не цвет: шрифты, режим и сила живого фона, формы (радиусы, толщины,
 * размеры, отступы), режим наложения блика и числа, которые код рисования читает как доли кадра.
 * Цвет в них не пишется; проверка формы хранения требует строкового значения в записи темы только
 * у цветовых токенов, а эти вправе быть и общей константой.
 */
export const NON_COLOUR_TOKENS: readonly string[] = [
  "--sc-sub-outline-shadow", "--sans", "--mono", "--kicker-case", "--kicker-tracking", "--sub-font", "--sub-weight", "--display", "--display-weight", "--display-tracking", "--display-case", "--bg-motion", "--bg-intensity", "--radius-sm", "--radius-md",
  "--radius-lg", "--radius-xl", "--radius-pill", "--space-xs", "--space-s", "--space-m", "--space-l",
  "--space-xl", "--space-2xl", "--space-3xl", "--dv-url-pad", "--dv-rim-width", "--hairline", "--rule-size",
  "--rail-size", "--ring-size", "--dot-ring", "--ring-width", "--chart-axis", "--chart-line-width",
  "--chart-dot-ring", "--ba-line-width", "--code-hl-bar", "--px-dim", "--pv-glint-strength",
  "--pv-reflection", "--pv-shade", "--tr-shade", "--sc-card-radius", "--sc-radius", "--sc-sub-radius",
  "--sc-hairline", "--sc-cap-bar-size", "--sc-spot-radius", "--sc-spot-width", "--sc-cursor-size",
  "--sc-cursor-line-width", "--sc-keys-radius", "--sc-keys-size", "--sc-keys-pad", "--sc-pad-x",
  "--sc-pad-y", "--sc-sub-pad-y", "--sc-badge-pad-x", "--sc-badge-pad-y", "--sc-edge", "--sc-mark-width",
  "--sc-mark-head", "--sc-mark-wobble", "--sc-arrow-width", "--sc-arrow-head", "--sc-spark-width",
  "--sc-ripple-size", "--sc-scrim-blur", "--sc-loupe-ring-width", "--sc-pip-ring-width",
  "--sc-progress-size", "--sc-glint-blend",
];

/**
 * Токены, которые читают проход ffmpeg и шейдеры: там цвет — числа, а не выражение CSS, поэтому
 * тема обязана писать их как `#rrggbb` или `#rrggbbaa` (у списка — через запятую). Другая запись —
 * ошибка разбора темы, а не молчаливая подмена цвета.
 */
export const HEX_TOKENS: readonly string[] = [
  "--sc-progress", "--sc-progress-track", "--sc-pip-ring", "--sc-loupe-ring", "--sc-letterbox", "--sc-confetti",
  "--sc-spark", "--sc-spark-2", "--tr-seam", "--tr-iris", "--tr-flash", "--tr-fill", "--pv-glint",
];

/**
 * Ночная тема: чернильная ночь, один синий сигнал и сталь для надзаголовков; бирюза прежней
 * версии осталась только серией графика (как `midnight` в agentic-report).
 * Каждая тема ниже — полный собственный набор: наследование от другой темы молча отдало бы
 * светлой теме тёмный цвет нового токена, и заметно это было бы только на готовом ролике.
 */
/**
 * Обводка субтитров контуром: кольцо из 16 теней в 0,08 кегля цветом --sc-sub-outline и мягкая тень
 * под буквами. Смещения — в em: они толкуются кеглем самих субтитров. Кольцо, а не -webkit-text-stroke:
 * тот в Chromium ложится поверх буквы и съедает её. Одно на все темы: тема меняет цвет обводки.
 */
const SUB_OUTLINE_SHADOW = "0.0800em 0.0000em 0 var(--sc-sub-outline),0.0739em 0.0306em 0 var(--sc-sub-outline),0.0566em 0.0566em 0 var(--sc-sub-outline),0.0306em 0.0739em 0 var(--sc-sub-outline),0.0000em 0.0800em 0 var(--sc-sub-outline),-0.0306em 0.0739em 0 var(--sc-sub-outline),-0.0566em 0.0566em 0 var(--sc-sub-outline),-0.0739em 0.0306em 0 var(--sc-sub-outline),-0.0800em 0.0000em 0 var(--sc-sub-outline),-0.0739em -0.0306em 0 var(--sc-sub-outline),-0.0566em -0.0566em 0 var(--sc-sub-outline),-0.0306em -0.0739em 0 var(--sc-sub-outline),-0.0000em -0.0800em 0 var(--sc-sub-outline),0.0306em -0.0739em 0 var(--sc-sub-outline),0.0566em -0.0566em 0 var(--sc-sub-outline),0.0739em -0.0306em 0 var(--sc-sub-outline),0 .06em .16em rgba(0,0,0,.55)";

const MIDNIGHT: ThemeVars = {
  "--bg": "#0b0e14",
  "--glow": "#16203a",
  "--ink": "#f2f5fb",
  "--body": "#c7cfdd",
  "--mut": "#8b97ad",
  "--line": "#2a3446",
  "--card": "#121826",
  "--node": "#141c2c",
  "--node-line": "#34405a",
  "--acc": "#7aa2ff",
  "--acc2": "#9fb2c8",
  "--bad": "#ff8a9b",
  "--good": "#7ee0a7",
  "--bad-line": "#5d3745",
  "--sans": '"IBM Plex Sans", system-ui, sans-serif',
  "--mono": '"JetBrains Mono", ui-monospace, monospace',
  "--display": '"Geologica", system-ui, sans-serif',
  "--display-weight": "680",
  "--display-tracking": "0em",
  "--display-case": "none",
  "--kicker-case": "none",
  "--kicker-tracking": ".02em",
  "--sub-font": '"IBM Plex Sans", system-ui, sans-serif',
  "--sub-weight": "600",
  "--bg-motion": "grid",
  "--bg-intensity": ".6",
  "--radius-sm": "12px",
  "--radius-md": "16px",
  "--radius-lg": "20px",
  "--radius-xl": "24px",
  "--radius-pill": "999px",
  "--hairline": "1px",
  "--rule-size": "3px",
  "--rail-size": "3px",
  "--ring-size": "2px",
  "--dot-ring": "4px",
  "--ring-width": "9",
  "--chart-axis": "2px",
  "--chart-line-width": "6",
  "--chart-dot-ring": "5px",
  "--ba-line-width": "4px",
  "--code-hl-bar": "4px",
  "--space-xs": "6px",
  "--space-s": "12px",
  "--space-m": "18px",
  "--space-l": "24px",
  "--space-xl": "30px",
  "--space-2xl": "36px",
  "--space-3xl": "46px",
  "--code-name": "#8b949e",
  "--code-gutter": "#78808c",
  "--code-kw": "#ff7b72",
  "--code-str": "#a5d6ff",
  "--code-num": "#79c0ff",
  "--code-fn": "#d2a8ff",
  "--code-type": "#ffa657",
  "--code-com": "#8b949e",
  "--code-pun": "#c9d1d9",
  "--code-bg": "#0d1117",
  "--code-bar": "#161b22",
  "--code-line": "#30363d",
  "--code-ink": "#e6edf3",
  "--ba-line": "#ffffff",
  "--ba-knob-bg": "#ffffff",
  "--ba-knob-ink": "#111111",
  "--ba-label-bg": "rgba(8,10,16,.72)",
  "--ba-label-ink": "#ffffff",
  "--shadow-3": "0 30px 80px rgba(0,0,0,.45)",
  "--shadow-color": "rgba(0,0,0,.6)",
  "--px-edge": "rgba(255,255,255,.14)",
  "--px-dim": "brightness(.45) saturate(.8)",
  "--cta-sheen": "rgba(255,255,255,.38)",
  "--pv-glint": "#ffffff",
  "--pv-glint-strength": ".5",
  "--pv-reflection": ".34",
  "--pv-shade": ".8",
  "--orbit-glow": "0 0 50px color-mix(in srgb,var(--acc2) 16%,transparent)",
  "--step-halo": "0 0 0 9px color-mix(in srgb,var(--acc) 22%,transparent)",
  "--dot-halo": "0 0 0 7px color-mix(in srgb,var(--acc) 20%,transparent)",
  "--code-caret": "3px 0 0 var(--acc2)",
  "--code-hl-shadow": "inset var(--code-hl-bar) 0 0 var(--acc)",
  "--cta-glow": "0 18px 50px color-mix(in srgb,var(--acc) 38%,transparent)",
  "--ba-line-shadow": "0 0 18px var(--shadow-color)",
  "--sc-spot": "rgba(122,162,255,.95)",
  "--sc-dim": "rgba(6,9,15,.55)",
  "--sc-accent-soft": "rgba(122,162,255,.5)",
  "--sc-fade": "#0d1017",
  "--sc-cap-bg": "linear-gradient(180deg,rgba(27,36,52,.97),rgba(18,24,34,.97))",
  "--sc-cap-line": "#3a4a6b",
  "--sc-cap-ink": "#eaeef7",
  "--sc-cap-bar": "#7aa2ff",
  "--sc-card-bg": "linear-gradient(135deg,rgba(18,24,38,.97),rgba(20,28,44,.95))",
  "--sc-card-line": "rgba(122,162,255,.42)",
  "--sc-card-ink": "#f6fbff",
  "--sc-card-body": "#c7cfdd",
  "--sc-card-accent": "#7aa2ff",
  "--sc-card-shadow": "0 18px 48px rgba(4,12,25,.42),inset 0 1px rgba(255,255,255,.08)",
  "--sc-card-accent-solid": "#7aa2ff",
  "--sc-lower-bar": "#7aa2ff",
  "--sc-sub-ink": "#ffffff",
  "--sc-sub-bg": "rgba(8,10,16,.9)",
  "--sc-sub-outline-ink": "#ffffff",
  "--sc-sub-outline": "#000000",
  "--sc-sub-accent": "#7aa2ff",
  "--sc-sub-outline-shadow": SUB_OUTLINE_SHADOW,
  "--sc-karaoke-ink": "#0b0e14",
  "--sc-karaoke-bg": "#7aa2ff",
  "--sc-badge-ink": "#0b0e14",
  "--sc-badge-bg": "#7aa2ff",
  "--sc-badge-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*1.2) rgba(0,0,0,.35)",
  "--sc-scrim": "radial-gradient(ellipse at 50% 50%,rgba(4,6,12,.86) 0%,rgba(4,6,12,.74) 60%,rgba(4,6,12,.8) 100%)",
  "--sc-title-ink": "#f6fbff",
  "--sc-title-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*2.4) rgba(0,0,0,.55)",
  "--sc-cap-shadow": "0 calc(var(--u)*1.2) calc(var(--u)*3.1) rgba(0,0,0,.65)",
  "--sc-sticker-shadow": "drop-shadow(0 calc(var(--u)*0.25) calc(var(--u)*0.6) rgba(0,0,0,.4))",
  "--sc-mark": "#7aa2ff",
  "--sc-glint": "linear-gradient(90deg,transparent,rgba(255,255,255,.18) 30%,rgba(255,255,255,.62) 50%,rgba(255,255,255,.18) 70%,transparent)",
  "--sc-glint-blend": "screen",
  "--sc-confetti": "#7aa2ff,#a9c3ff,#9fb2c8,#7ee0a7,#ffffff",
  "--sc-spark": "#fff6cf",
  "--sc-spark-2": "#ffd98a",
  "--sc-loupe-ring": "#7aa2ff",
  "--sc-cursor-fill": "#f7f9ff",
  "--sc-cursor-line": "#0d1017",
  "--sc-cursor-shadow": "drop-shadow(0 calc(var(--u)*0.16) calc(var(--u)*0.31) rgba(0,0,0,.55))",
  "--sc-ripple-ring": "#7aa2ff",
  "--sc-ripple": "rgba(122,162,255,0.22)",
  "--sc-ripple-glint": "rgba(255,255,255,.35)",
  "--sc-keys-ink": "#f6fbff",
  "--sc-keys-bg": "linear-gradient(180deg,#26324a,#141b2b)",
  "--sc-keys-line": "#3d5078",
  "--sc-keys-shadow": "0 6px 0 #0b1020,0 14px 30px rgba(0,0,0,.45)",
  "--sc-progress": "#7aa2ff",
  "--sc-progress-track": "#00000059",
  "--sc-pip-ring": "#7aa2ff",
  "--sc-letterbox": "#0d1017",
  "--dv-shadow": "0 34px 90px rgba(0,0,0,.42),0 10px 24px rgba(0,0,0,.25)",
  "--dv-bar-tint": "#ffffff",
  "--dv-bezel": "#0c0d11",
  "--dv-rim": "#3a3f4b",
  "--dv-island": "#07080b",
  "--dv-browser-shadow": "0 0 0 var(--hairline) var(--line),var(--dv-shadow)",
  "--dv-url-pad": "1.2em",
  "--dv-rim-width": "2px",
  "--sc-traffic-1": "#ff5f57",
  "--sc-traffic-2": "#febc2e",
  "--sc-traffic-3": "#28c840",
  "--tr-seam": "#547399",
  "--tr-iris": "#b3a17d",
  "--tr-flash": "#ffc780",
  "--tr-fill": "#0d1017",
  "--sc-card-radius": "calc(var(--u)*.94)",
  "--sc-radius": "calc(var(--u)*.6)",
  "--sc-sub-radius": "calc(var(--u)*.35)",
  "--sc-hairline": "1px",
  "--sc-cap-bar-size": "calc(var(--u)*0.16)",
  "--sc-spot-radius": "calc(var(--u)*0.73)",
  "--sc-spot-width": "calc(var(--u)*0.16)",
  "--sc-cursor-size": "calc(var(--u)*1.35)",
  "--sc-keys-radius": "12px",
  "--sc-keys-size": "26px",
  "--sc-cursor-line-width": "1.4",
  "--sc-sub-pad-y": "calc(var(--u)*0.12)",
  "--sc-badge-pad-x": "calc(var(--u)*0.9)",
  "--sc-badge-pad-y": "calc(var(--u)*0.35)",
  "--sc-spot-shadow": "0 0 0 var(--sc-spot-width) var(--sc-spot),0 0 0 9999px var(--sc-dim)",
  "--sc-karaoke-halo": "0 0 0 calc(var(--u)*0.12) var(--sc-karaoke-bg)",
  "--sc-ripple-shadow": "0 0 0 7px var(--sc-ripple),inset 0 0 0 3px var(--sc-ripple-glint)",
  "--sc-keys-pad": "10px 16px",
  "--sc-pad-x": "calc(var(--u)*1.7)",
  "--sc-pad-y": "calc(var(--u)*1.1)",
  "--sc-edge": "calc(var(--u)*2.3)",
  "--sc-mark-width": ".0042",
  "--sc-mark-head": ".016",
  "--sc-mark-wobble": ".0025",
  "--sc-arrow-width": ".0022",
  "--sc-arrow-head": ".009",
  "--sc-spark-width": ".0022",
  "--sc-ripple-size": ".0375",
  "--sc-scrim-blur": ".004",
  "--sc-loupe-ring-width": ".015",
  "--sc-pip-ring-width": ".02",
  "--sc-progress-size": ".006",
  "--tr-shade": ".55",
};

/**
 * Спокойная бумажная тема: тёплый светлый фон, тёмная типографика,
 * один глиняный акцент. Годится там, где ролик смотрят как документ,
 * а не как трейлер: длинное объяснение, разбор. Крем, антиква и терракота на продуктовом
 * ролике — модная эстетика 2026 года (docs/visual-design.md); продукту — `neutral`.
 */
const CALM_PAPER: ThemeVars = {
  "--bg": "#f4f1ea",
  "--glow": "#e8e2d5",
  "--ink": "#1b1a17",
  "--body": "#3c3a34",
  "--mut": "#66614f",
  "--line": "#ded7c8",
  "--card": "#fbf9f4",
  "--node": "#ffffff",
  "--node-line": "#ddd5c4",
  "--acc": "#c2643f",
  "--acc2": "#4b7a6a",
  "--bad": "#a8452f",
  "--good": "#3f7a57",
  "--bad-line": "#dbb5a9",
  "--sans": '"Literata", Georgia, serif',
  "--mono": '"PT Mono", ui-monospace, monospace',
  "--display": '"Playfair", Georgia, serif',
  "--display-weight": "600",
  "--display-tracking": ".02em",
  "--display-case": "none",
  "--kicker-case": "none",
  "--kicker-tracking": ".02em",
  "--sub-font": '"Golos Text", system-ui, sans-serif',
  "--sub-weight": "600",
  "--bg-motion": "grid",
  "--bg-intensity": ".6",
  "--radius-sm": "9px",
  "--radius-md": "12px",
  "--radius-lg": "16px",
  "--radius-xl": "19px",
  "--radius-pill": "999px",
  "--hairline": "1px",
  "--rule-size": "3px",
  "--rail-size": "3px",
  "--ring-size": "2px",
  "--dot-ring": "4px",
  "--ring-width": "9",
  "--chart-axis": "2px",
  "--chart-line-width": "6",
  "--chart-dot-ring": "5px",
  "--ba-line-width": "4px",
  "--code-hl-bar": "4px",
  "--space-xs": "6px",
  "--space-s": "12px",
  "--space-m": "18px",
  "--space-l": "24px",
  "--space-xl": "30px",
  "--space-2xl": "36px",
  "--space-3xl": "46px",
  "--code-name": "#6f6a5c",
  "--code-gutter": "#777366",
  "--code-kw": "#9c3d1f",
  "--code-str": "#3f6b4f",
  "--code-num": "#2f5f8a",
  "--code-fn": "#7a4b8c",
  "--code-type": "#8a5a00",
  "--code-com": "#6f6a5c",
  "--code-pun": "#3c3a34",
  "--code-bg": "#ffffff",
  "--code-bar": "#f6f8fa",
  "--code-line": "#d0d7de",
  "--code-ink": "#1f2328",
  "--ba-line": "#c2643f",
  "--ba-knob-bg": "#c2643f",
  "--ba-knob-ink": "#ffffff",
  "--ba-label-bg": "rgba(255,255,255,.88)",
  "--ba-label-ink": "#1b1a17",
  "--shadow-3": "0 30px 80px rgba(15,23,42,.16)",
  "--shadow-color": "rgba(15,23,42,.35)",
  "--px-edge": "rgba(15,23,42,.14)",
  "--px-dim": "brightness(.8) saturate(.85)",
  "--cta-sheen": "rgba(255,255,255,.55)",
  "--pv-glint": "#ffffff",
  "--pv-glint-strength": ".5",
  "--pv-reflection": ".34",
  "--pv-shade": ".8",
  "--orbit-glow": "0 0 50px color-mix(in srgb,var(--acc2) 16%,transparent)",
  "--step-halo": "0 0 0 9px color-mix(in srgb,var(--acc) 22%,transparent)",
  "--dot-halo": "0 0 0 7px color-mix(in srgb,var(--acc) 20%,transparent)",
  "--code-caret": "3px 0 0 var(--acc2)",
  "--code-hl-shadow": "inset var(--code-hl-bar) 0 0 var(--acc)",
  "--cta-glow": "0 18px 50px color-mix(in srgb,var(--acc) 38%,transparent)",
  "--ba-line-shadow": "0 0 18px var(--shadow-color)",
  "--sc-spot": "rgba(194,100,63,.95)",
  "--sc-dim": "rgba(28,24,18,.42)",
  "--sc-accent-soft": "rgba(194,100,63,.42)",
  "--sc-fade": "#f4f1ea",
  "--sc-cap-bg": "linear-gradient(180deg,rgba(251,249,244,.98),rgba(244,241,234,.98))",
  "--sc-cap-line": "#ded7c8",
  "--sc-cap-ink": "#1b1a17",
  "--sc-cap-bar": "#c2643f",
  "--sc-card-bg": "linear-gradient(135deg,rgba(255,253,248,.98),rgba(246,242,233,.97))",
  "--sc-card-line": "rgba(194,100,63,.42)",
  "--sc-card-ink": "#1b1a17",
  "--sc-card-body": "#4a473f",
  "--sc-card-accent": "#c2643f",
  "--sc-card-shadow": "0 16px 40px rgba(60,48,32,.16)",
  "--sc-card-accent-solid": "#c2643f",
  "--sc-lower-bar": "#c2643f",
  "--sc-sub-ink": "#1b1a17",
  "--sc-sub-bg": "rgba(255,255,255,.9)",
  "--sc-sub-outline-ink": "#ffffff",
  "--sc-sub-outline": "#000000",
  "--sc-sub-accent": "#f0b27a",
  "--sc-sub-outline-shadow": SUB_OUTLINE_SHADOW,
  "--sc-karaoke-ink": "#ffffff",
  "--sc-karaoke-bg": "#a8522f",
  "--sc-badge-ink": "#ffffff",
  "--sc-badge-bg": "#c2643f",
  "--sc-badge-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*1.2) rgba(15,23,42,.18)",
  "--sc-scrim": "radial-gradient(ellipse at 50% 50%,rgba(244,241,234,.9) 0%,rgba(244,241,234,.82) 60%,rgba(244,241,234,.86) 100%)",
  "--sc-title-ink": "#1b1a17",
  "--sc-title-shadow": "0 calc(var(--u)*0.2) calc(var(--u)*1.6) rgba(255,255,255,.7)",
  "--sc-cap-shadow": "0 calc(var(--u)*1.1) calc(var(--u)*3) rgba(40,40,60,.18)",
  "--sc-sticker-shadow": "drop-shadow(0 calc(var(--u)*0.25) calc(var(--u)*0.6) rgba(40,40,60,.22))",
  "--sc-mark": "#4b7a6a",
  "--sc-glint": "linear-gradient(90deg,transparent,rgba(194,100,63,0.14) 30%,rgba(194,100,63,0.38) 50%,rgba(194,100,63,0.14) 70%,transparent)",
  "--sc-glint-blend": "normal",
  "--sc-confetti": "#c2643f,#4b7a6a,#3f7a57,#a8452f,#1b1a17",
  "--sc-spark": "#e38b5c",
  "--sc-spark-2": "#c2643f",
  "--sc-loupe-ring": "#c2643f",
  "--sc-cursor-fill": "#111827",
  "--sc-cursor-line": "#ffffff",
  "--sc-cursor-shadow": "drop-shadow(0 calc(var(--u)*0.16) calc(var(--u)*0.31) rgba(0,0,0,.3))",
  "--sc-ripple-ring": "#4b7a6a",
  "--sc-ripple": "rgba(75,122,106,0.22)",
  "--sc-ripple-glint": "rgba(255,255,255,.6)",
  "--sc-keys-ink": "#1b1a17",
  "--sc-keys-bg": "linear-gradient(180deg,#ffffff,#eef1f6)",
  "--sc-keys-line": "#ded7c8",
  "--sc-keys-shadow": "0 6px 0 #d5dae3,0 14px 30px rgba(15,23,42,.18)",
  "--sc-progress": "#c2643f",
  "--sc-progress-track": "#0f172a33",
  "--sc-pip-ring": "#c2643f",
  "--sc-letterbox": "#f4f1ea",
  "--dv-shadow": "0 34px 90px rgba(15,23,42,.18),0 10px 24px rgba(15,23,42,.1)",
  "--dv-bar-tint": "#ffffff",
  "--dv-bezel": "#1f2937",
  "--dv-rim": "#9aa3b2",
  "--dv-island": "#07080b",
  "--dv-browser-shadow": "0 0 0 var(--hairline) var(--line),var(--dv-shadow)",
  "--dv-url-pad": "1.2em",
  "--dv-rim-width": "2px",
  "--sc-traffic-1": "#ff5f57",
  "--sc-traffic-2": "#febc2e",
  "--sc-traffic-3": "#28c840",
  "--tr-seam": "#815c4e",
  "--tr-iris": "#677a74",
  "--tr-flash": "#ffffff",
  "--tr-fill": "#f4f1ea",
  "--sc-card-radius": "calc(var(--u)*.731)",
  "--sc-radius": "calc(var(--u)*.467)",
  "--sc-sub-radius": "calc(var(--u)*.272)",
  "--sc-hairline": "1px",
  "--sc-cap-bar-size": "calc(var(--u)*0.16)",
  "--sc-spot-radius": "calc(var(--u)*0.73)",
  "--sc-spot-width": "calc(var(--u)*0.16)",
  "--sc-cursor-size": "calc(var(--u)*1.35)",
  "--sc-keys-radius": "12px",
  "--sc-keys-size": "26px",
  "--sc-cursor-line-width": "1.4",
  "--sc-sub-pad-y": "calc(var(--u)*0.12)",
  "--sc-badge-pad-x": "calc(var(--u)*0.9)",
  "--sc-badge-pad-y": "calc(var(--u)*0.35)",
  "--sc-spot-shadow": "0 0 0 var(--sc-spot-width) var(--sc-spot),0 0 0 9999px var(--sc-dim)",
  "--sc-karaoke-halo": "0 0 0 calc(var(--u)*0.12) var(--sc-karaoke-bg)",
  "--sc-ripple-shadow": "0 0 0 7px var(--sc-ripple),inset 0 0 0 3px var(--sc-ripple-glint)",
  "--sc-keys-pad": "10px 16px",
  "--sc-pad-x": "calc(var(--u)*1.7)",
  "--sc-pad-y": "calc(var(--u)*1.1)",
  "--sc-edge": "calc(var(--u)*2.3)",
  "--sc-mark-width": ".0042",
  "--sc-mark-head": ".016",
  "--sc-mark-wobble": ".0025",
  "--sc-arrow-width": ".0022",
  "--sc-arrow-head": ".009",
  "--sc-spark-width": ".0022",
  "--sc-ripple-size": ".0375",
  "--sc-scrim-blur": ".004",
  "--sc-loupe-ring-width": ".015",
  "--sc-pip-ring-width": ".02",
  "--sc-progress-size": ".006",
  "--tr-shade": ".55",
};

/**
 * Синтвейв — жанровая тема: густой фиолетовый фон, неоновые пурпур и бирюза, надзаголовки
 * капсом. Только для игр и музыки, где неон — жанр, а не облик продукта; контраст текста
 * остаётся светлым на тёмном, а не неон на неоне: подпись обязана
 * читаться, а не светиться.
 */
const SYNTHWAVE: ThemeVars = {
  "--bg": "#140b27",
  "--glow": "#3c1266",
  "--ink": "#fdf4ff",
  "--body": "#d9c8f0",
  "--mut": "#9b86c4",
  "--line": "#3e2a63",
  "--card": "#1d1036",
  "--node": "#241443",
  "--node-line": "#5a3597",
  "--acc": "#ff4fd8",
  "--acc2": "#37e0ff",
  "--bad": "#ff6b8a",
  "--good": "#6cf0c2",
  "--bad-line": "#733356",
  "--sans": '"Exo 2", system-ui, sans-serif',
  "--mono": '"JetBrains Mono", ui-monospace, monospace',
  "--display": '"Unbounded", system-ui, sans-serif',
  "--display-weight": "700",
  "--display-tracking": "-.01em",
  "--display-case": "none",
  "--kicker-case": "uppercase",
  "--kicker-tracking": ".16em",
  "--sub-font": '"Exo 2", system-ui, sans-serif',
  "--sub-weight": "600",
  "--bg-motion": "grid",
  "--bg-intensity": ".6",
  "--radius-sm": "11px",
  "--radius-md": "14px",
  "--radius-lg": "18px",
  "--radius-xl": "21px",
  "--radius-pill": "999px",
  "--hairline": "1px",
  "--rule-size": "3px",
  "--rail-size": "3px",
  "--ring-size": "2px",
  "--dot-ring": "4px",
  "--ring-width": "9",
  "--chart-axis": "2px",
  "--chart-line-width": "6",
  "--chart-dot-ring": "5px",
  "--ba-line-width": "4px",
  "--code-hl-bar": "4px",
  "--space-xs": "6px",
  "--space-s": "12px",
  "--space-m": "18px",
  "--space-l": "24px",
  "--space-xl": "30px",
  "--space-2xl": "36px",
  "--space-3xl": "46px",
  "--code-name": "#9b86c4",
  "--code-gutter": "#8372a7",
  "--code-kw": "#ff4fd8",
  "--code-str": "#6cf0c2",
  "--code-num": "#37e0ff",
  "--code-fn": "#c8a6ff",
  "--code-type": "#ffb86b",
  "--code-com": "#9b86c4",
  "--code-pun": "#d9c8f0",
  "--code-bg": "#0a0418",
  "--code-bar": "#1d1036",
  "--code-line": "#3e2a63",
  "--code-ink": "#fdf4ff",
  "--ba-line": "#ffffff",
  "--ba-knob-bg": "#ffffff",
  "--ba-knob-ink": "#111111",
  "--ba-label-bg": "rgba(8,10,16,.72)",
  "--ba-label-ink": "#ffffff",
  "--shadow-3": "0 30px 80px rgba(0,0,0,.45)",
  "--shadow-color": "rgba(0,0,0,.6)",
  "--px-edge": "rgba(255,255,255,.14)",
  "--px-dim": "brightness(.45) saturate(.8)",
  "--cta-sheen": "rgba(255,255,255,.38)",
  "--pv-glint": "#e7fbff",
  "--pv-glint-strength": ".5",
  "--pv-reflection": ".34",
  "--pv-shade": ".8",
  "--orbit-glow": "0 0 50px color-mix(in srgb,var(--acc2) 16%,transparent)",
  "--step-halo": "0 0 0 9px color-mix(in srgb,var(--acc) 22%,transparent)",
  "--dot-halo": "0 0 0 7px color-mix(in srgb,var(--acc) 20%,transparent)",
  "--code-caret": "3px 0 0 var(--acc2)",
  "--code-hl-shadow": "inset var(--code-hl-bar) 0 0 var(--acc)",
  "--cta-glow": "0 18px 50px color-mix(in srgb,var(--acc) 38%,transparent)",
  "--ba-line-shadow": "0 0 18px var(--shadow-color)",
  "--sc-spot": "rgba(255,79,216,.95)",
  "--sc-dim": "rgba(10,4,24,.6)",
  "--sc-accent-soft": "rgba(55,224,255,.5)",
  "--sc-fade": "#0a0418",
  "--sc-cap-bg": "linear-gradient(180deg,rgba(38,18,70,.96),rgba(22,10,44,.96))",
  "--sc-cap-line": "#6a3fb0",
  "--sc-cap-ink": "#fdf4ff",
  "--sc-cap-bar": "linear-gradient(90deg,#ff4fd8,#37e0ff)",
  "--sc-card-bg": "linear-gradient(135deg,rgba(44,16,82,.96),rgba(20,8,42,.94))",
  "--sc-card-line": "rgba(255,79,216,.6)",
  "--sc-card-ink": "#fdf4ff",
  "--sc-card-body": "#d6c2f2",
  "--sc-card-accent": "linear-gradient(90deg,#ff4fd8,#37e0ff)",
  "--sc-card-shadow": "0 20px 54px rgba(60,8,90,.55),inset 0 1px rgba(255,255,255,.1)",
  "--sc-card-accent-solid": "#ff4fd8",
  "--sc-lower-bar": "linear-gradient(180deg,#ff4fd8,#37e0ff)",
  "--sc-sub-ink": "#ffffff",
  "--sc-sub-bg": "rgba(10,4,24,.9)",
  "--sc-sub-outline-ink": "#ffffff",
  "--sc-sub-outline": "#000000",
  "--sc-sub-accent": "#ff6fe0",
  "--sc-sub-outline-shadow": SUB_OUTLINE_SHADOW,
  "--sc-karaoke-ink": "#140b27",
  "--sc-karaoke-bg": "#ff4fd8",
  "--sc-badge-ink": "#140b27",
  "--sc-badge-bg": "#ff4fd8",
  "--sc-badge-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*1.2) rgba(0,0,0,.35)",
  "--sc-scrim": "radial-gradient(ellipse at 50% 50%,rgba(10,4,24,.86) 0%,rgba(10,4,24,.74) 60%,rgba(10,4,24,.8) 100%)",
  "--sc-title-ink": "#fdf4ff",
  "--sc-title-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*2.4) rgba(0,0,0,.55)",
  "--sc-cap-shadow": "0 calc(var(--u)*1.2) calc(var(--u)*3.1) rgba(0,0,0,.65)",
  "--sc-sticker-shadow": "drop-shadow(0 calc(var(--u)*0.25) calc(var(--u)*0.6) rgba(0,0,0,.4))",
  "--sc-mark": "#37e0ff",
  "--sc-glint": "linear-gradient(90deg,transparent,rgba(255,255,255,.18) 30%,rgba(255,255,255,.62) 50%,rgba(255,255,255,.18) 70%,transparent)",
  "--sc-glint-blend": "screen",
  "--sc-confetti": "#ff4fd8,#37e0ff,#6cf0c2,#ff6b8a,#ffffff",
  "--sc-spark": "#ffe3fb",
  "--sc-spark-2": "#9ff3ff",
  "--sc-loupe-ring": "#ff4fd8",
  "--sc-cursor-fill": "#f7f9ff",
  "--sc-cursor-line": "#0d1017",
  "--sc-cursor-shadow": "drop-shadow(0 calc(var(--u)*0.16) calc(var(--u)*0.31) rgba(0,0,0,.55))",
  "--sc-ripple-ring": "#37e0ff",
  "--sc-ripple": "rgba(55,224,255,0.22)",
  "--sc-ripple-glint": "rgba(255,255,255,.35)",
  "--sc-keys-ink": "#fdf4ff",
  "--sc-keys-bg": "linear-gradient(180deg,#34284a,#1d1036)",
  "--sc-keys-line": "#6a3fb0",
  "--sc-keys-shadow": "0 6px 0 #0e081b,0 14px 30px rgba(0,0,0,.45)",
  "--sc-progress": "#ff4fd8",
  "--sc-progress-track": "#00000059",
  "--sc-pip-ring": "#ff4fd8",
  "--sc-letterbox": "#0a0418",
  "--dv-shadow": "0 34px 90px rgba(0,0,0,.42),0 10px 24px rgba(0,0,0,.25)",
  "--dv-bar-tint": "#ffffff",
  "--dv-bezel": "#0c0d11",
  "--dv-rim": "#3a3f4b",
  "--dv-island": "#07080b",
  "--dv-browser-shadow": "0 0 0 var(--hairline) var(--line),var(--dv-shadow)",
  "--dv-url-pad": "1.2em",
  "--dv-rim-width": "2px",
  "--sc-traffic-1": "#ff5f57",
  "--sc-traffic-2": "#febc2e",
  "--sc-traffic-3": "#28c840",
  "--tr-seam": "#99558a",
  "--tr-iris": "#5ea5b2",
  "--tr-flash": "#ffa7ec",
  "--tr-fill": "#0a0418",
  "--sc-card-radius": "calc(var(--u)*.836)",
  "--sc-radius": "calc(var(--u)*.533)",
  "--sc-sub-radius": "calc(var(--u)*.311)",
  "--sc-hairline": "1px",
  "--sc-cap-bar-size": "calc(var(--u)*0.16)",
  "--sc-spot-radius": "calc(var(--u)*0.73)",
  "--sc-spot-width": "calc(var(--u)*0.16)",
  "--sc-cursor-size": "calc(var(--u)*1.35)",
  "--sc-keys-radius": "12px",
  "--sc-keys-size": "26px",
  "--sc-cursor-line-width": "1.4",
  "--sc-sub-pad-y": "calc(var(--u)*0.12)",
  "--sc-badge-pad-x": "calc(var(--u)*0.9)",
  "--sc-badge-pad-y": "calc(var(--u)*0.35)",
  "--sc-spot-shadow": "0 0 0 var(--sc-spot-width) var(--sc-spot),0 0 0 9999px var(--sc-dim)",
  "--sc-karaoke-halo": "0 0 0 calc(var(--u)*0.12) var(--sc-karaoke-bg)",
  "--sc-ripple-shadow": "0 0 0 7px var(--sc-ripple),inset 0 0 0 3px var(--sc-ripple-glint)",
  "--sc-keys-pad": "10px 16px",
  "--sc-pad-x": "calc(var(--u)*1.7)",
  "--sc-pad-y": "calc(var(--u)*1.1)",
  "--sc-edge": "calc(var(--u)*2.3)",
  "--sc-mark-width": ".0042",
  "--sc-mark-head": ".016",
  "--sc-mark-wobble": ".0025",
  "--sc-arrow-width": ".0022",
  "--sc-arrow-head": ".009",
  "--sc-spark-width": ".0022",
  "--sc-ripple-size": ".0375",
  "--sc-scrim-blur": ".004",
  "--sc-loupe-ring-width": ".015",
  "--sc-pip-ring-width": ".02",
  "--sc-progress-size": ".006",
  "--tr-shade": ".55",
};

/**
 * Деловой мрачный: почти чёрный фон, холодный серый текст, один
 * сдержанный янтарный акцент. Для показов, где важен предмет,
 * а не оформление.
 */
const NOIR: ThemeVars = {
  "--bg": "#0a0a0b",
  "--glow": "#17181c",
  "--ink": "#f4f4f5",
  "--body": "#bcbcc2",
  "--mut": "#7c7c85",
  "--line": "#26272c",
  "--card": "#121316",
  "--node": "#141518",
  "--node-line": "#2e2f36",
  "--acc": "#e0a458",
  "--acc2": "#9fb2c8",
  "--bad": "#d4726a",
  "--good": "#8fb996",
  "--bad-line": "#5c3736",
  "--sans": '"Jost", system-ui, sans-serif',
  "--mono": '"PT Mono", ui-monospace, monospace',
  "--display": '"Cormorant Garamond", Georgia, serif',
  "--display-weight": "600",
  "--display-tracking": ".1em",
  "--display-case": "uppercase",
  "--kicker-case": "none",
  "--kicker-tracking": ".02em",
  "--sub-font": '"Jost", system-ui, sans-serif',
  "--sub-weight": "600",
  "--bg-motion": "grid",
  "--bg-intensity": ".6",
  "--radius-sm": "7px",
  "--radius-md": "9px",
  "--radius-lg": "11px",
  "--radius-xl": "13px",
  "--radius-pill": "999px",
  "--hairline": "1px",
  "--rule-size": "3px",
  "--rail-size": "3px",
  "--ring-size": "2px",
  "--dot-ring": "4px",
  "--ring-width": "9",
  "--chart-axis": "2px",
  "--chart-line-width": "6",
  "--chart-dot-ring": "5px",
  "--ba-line-width": "4px",
  "--code-hl-bar": "4px",
  "--space-xs": "6px",
  "--space-s": "12px",
  "--space-m": "18px",
  "--space-l": "24px",
  "--space-xl": "30px",
  "--space-2xl": "36px",
  "--space-3xl": "46px",
  "--code-name": "#7c7c85",
  "--code-gutter": "#777781",
  "--code-kw": "#e0a458",
  "--code-str": "#8fb996",
  "--code-num": "#9fb2c8",
  "--code-fn": "#e8c79a",
  "--code-type": "#d4726a",
  "--code-com": "#7c7c85",
  "--code-pun": "#bcbcc2",
  "--code-bg": "#000000",
  "--code-bar": "#121316",
  "--code-line": "#26272c",
  "--code-ink": "#f4f4f5",
  "--ba-line": "#ffffff",
  "--ba-knob-bg": "#ffffff",
  "--ba-knob-ink": "#111111",
  "--ba-label-bg": "rgba(8,10,16,.72)",
  "--ba-label-ink": "#ffffff",
  "--shadow-3": "0 30px 80px rgba(0,0,0,.45)",
  "--shadow-color": "rgba(0,0,0,.6)",
  "--px-edge": "rgba(255,255,255,.14)",
  "--px-dim": "brightness(.45) saturate(.8)",
  "--cta-sheen": "rgba(255,255,255,.38)",
  "--pv-glint": "#f3f6f8",
  "--pv-glint-strength": ".5",
  "--pv-reflection": ".34",
  "--pv-shade": ".8",
  "--orbit-glow": "0 0 50px color-mix(in srgb,var(--acc2) 16%,transparent)",
  "--step-halo": "0 0 0 9px color-mix(in srgb,var(--acc) 22%,transparent)",
  "--dot-halo": "0 0 0 7px color-mix(in srgb,var(--acc) 20%,transparent)",
  "--code-caret": "3px 0 0 var(--acc2)",
  "--code-hl-shadow": "inset var(--code-hl-bar) 0 0 var(--acc)",
  "--cta-glow": "0 18px 50px color-mix(in srgb,var(--acc) 38%,transparent)",
  "--ba-line-shadow": "0 0 18px var(--shadow-color)",
  "--sc-spot": "rgba(224,164,88,.95)",
  "--sc-dim": "rgba(0,0,0,.62)",
  "--sc-accent-soft": "rgba(224,164,88,.4)",
  "--sc-fade": "#000000",
  "--sc-cap-bg": "linear-gradient(180deg,rgba(20,21,24,.97),rgba(11,11,13,.97))",
  "--sc-cap-line": "#33343a",
  "--sc-cap-ink": "#f4f4f5",
  "--sc-cap-bar": "#e0a458",
  "--sc-card-bg": "linear-gradient(135deg,rgba(23,24,28,.97),rgba(12,12,14,.95))",
  "--sc-card-line": "rgba(224,164,88,.45)",
  "--sc-card-ink": "#f4f4f5",
  "--sc-card-body": "#b6b6be",
  "--sc-card-accent": "#e0a458",
  "--sc-card-shadow": "0 18px 44px rgba(0,0,0,.6)",
  "--sc-card-accent-solid": "#e0a458",
  "--sc-lower-bar": "#e0a458",
  "--sc-sub-ink": "#ffffff",
  "--sc-sub-bg": "rgba(0,0,0,.9)",
  "--sc-sub-outline-ink": "#ffffff",
  "--sc-sub-outline": "#000000",
  "--sc-sub-accent": "#e0a458",
  "--sc-sub-outline-shadow": SUB_OUTLINE_SHADOW,
  "--sc-karaoke-ink": "#0a0a0b",
  "--sc-karaoke-bg": "#e0a458",
  "--sc-badge-ink": "#0a0a0b",
  "--sc-badge-bg": "#e0a458",
  "--sc-badge-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*1.2) rgba(0,0,0,.35)",
  "--sc-scrim": "radial-gradient(ellipse at 50% 50%,rgba(0,0,0,.86) 0%,rgba(0,0,0,.74) 60%,rgba(0,0,0,.8) 100%)",
  "--sc-title-ink": "#f4f4f5",
  "--sc-title-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*2.4) rgba(0,0,0,.55)",
  "--sc-cap-shadow": "0 calc(var(--u)*1.2) calc(var(--u)*3.1) rgba(0,0,0,.65)",
  "--sc-sticker-shadow": "drop-shadow(0 calc(var(--u)*0.25) calc(var(--u)*0.6) rgba(0,0,0,.4))",
  "--sc-mark": "#9fb2c8",
  "--sc-glint": "linear-gradient(90deg,transparent,rgba(255,255,255,.18) 30%,rgba(255,255,255,.62) 50%,rgba(255,255,255,.18) 70%,transparent)",
  "--sc-glint-blend": "screen",
  "--sc-confetti": "#e0a458,#9fb2c8,#8fb996,#d4726a,#ffffff",
  "--sc-spark": "#fff1dc",
  "--sc-spark-2": "#e0a458",
  "--sc-loupe-ring": "#e0a458",
  "--sc-cursor-fill": "#f7f9ff",
  "--sc-cursor-line": "#0d1017",
  "--sc-cursor-shadow": "drop-shadow(0 calc(var(--u)*0.16) calc(var(--u)*0.31) rgba(0,0,0,.55))",
  "--sc-ripple-ring": "#9fb2c8",
  "--sc-ripple": "rgba(159,178,200,0.22)",
  "--sc-ripple-glint": "rgba(255,255,255,.35)",
  "--sc-keys-ink": "#f4f4f5",
  "--sc-keys-bg": "linear-gradient(180deg,#2a2b2d,#121316)",
  "--sc-keys-line": "#33343a",
  "--sc-keys-shadow": "0 6px 0 #070708,0 14px 30px rgba(0,0,0,.45)",
  "--sc-progress": "#e0a458",
  "--sc-progress-track": "#00000059",
  "--sc-pip-ring": "#e0a458",
  "--sc-letterbox": "#000000",
  "--dv-shadow": "0 34px 90px rgba(0,0,0,.42),0 10px 24px rgba(0,0,0,.25)",
  "--dv-bar-tint": "#ffffff",
  "--dv-bezel": "#0c0d11",
  "--dv-rim": "#3a3f4b",
  "--dv-island": "#07080b",
  "--dv-browser-shadow": "0 0 0 var(--hairline) var(--line),var(--dv-shadow)",
  "--dv-url-pad": "1.2em",
  "--dv-rim-width": "2px",
  "--sc-traffic-1": "#ff5f57",
  "--sc-traffic-2": "#febc2e",
  "--sc-traffic-3": "#28c840",
  "--tr-seam": "#8d7658",
  "--tr-iris": "#8a929b",
  "--tr-flash": "#f0d2ac",
  "--tr-fill": "#000000",
  "--sc-card-radius": "calc(var(--u)*.522)",
  "--sc-radius": "calc(var(--u)*.333)",
  "--sc-sub-radius": "calc(var(--u)*.194)",
  "--sc-hairline": "1px",
  "--sc-cap-bar-size": "calc(var(--u)*0.16)",
  "--sc-spot-radius": "calc(var(--u)*0.73)",
  "--sc-spot-width": "calc(var(--u)*0.16)",
  "--sc-cursor-size": "calc(var(--u)*1.35)",
  "--sc-keys-radius": "12px",
  "--sc-keys-size": "26px",
  "--sc-cursor-line-width": "1.4",
  "--sc-sub-pad-y": "calc(var(--u)*0.12)",
  "--sc-badge-pad-x": "calc(var(--u)*0.9)",
  "--sc-badge-pad-y": "calc(var(--u)*0.35)",
  "--sc-spot-shadow": "0 0 0 var(--sc-spot-width) var(--sc-spot),0 0 0 9999px var(--sc-dim)",
  "--sc-karaoke-halo": "0 0 0 calc(var(--u)*0.12) var(--sc-karaoke-bg)",
  "--sc-ripple-shadow": "0 0 0 7px var(--sc-ripple),inset 0 0 0 3px var(--sc-ripple-glint)",
  "--sc-keys-pad": "10px 16px",
  "--sc-pad-x": "calc(var(--u)*1.7)",
  "--sc-pad-y": "calc(var(--u)*1.1)",
  "--sc-edge": "calc(var(--u)*2.3)",
  "--sc-mark-width": ".0042",
  "--sc-mark-head": ".016",
  "--sc-mark-wobble": ".0025",
  "--sc-arrow-width": ".0022",
  "--sc-arrow-head": ".009",
  "--sc-spark-width": ".0022",
  "--sc-ripple-size": ".0375",
  "--sc-scrim-blur": ".004",
  "--sc-loupe-ring-width": ".015",
  "--sc-pip-ring-width": ".02",
  "--sc-progress-size": ".006",
  "--tr-shade": ".55",
};

/**
 * Северное сияние: глубокая синяя ночь, один мятный сигнал, песок для надзаголовков, тонкий
 * Raleway. Для спокойного исследования; живой фон — тихая сетка, занавеси сияния (`aurora`)
 * остаются выбором сцены.
 */
const AURORA: ThemeVars = {
  "--bg": "#070b16",
  "--glow": "#0f2a3a",
  "--ink": "#eefaf7",
  "--body": "#c0d7d6",
  "--mut": "#819ea7",
  "--line": "#1d3340",
  "--card": "#0c1622",
  "--node": "#0f1c2a",
  "--node-line": "#26445a",
  "--acc": "#6fd6c4",
  "--acc2": "#d9c7a0",
  "--bad": "#f0907a",
  "--good": "#8fcfa6",
  "--bad-line": "#673948",
  "--sans": '"Commissioner", system-ui, sans-serif',
  "--mono": '"Victor Mono", ui-monospace, monospace',
  "--display": '"Raleway", system-ui, sans-serif',
  "--display-weight": "400",
  "--display-tracking": ".01em",
  "--display-case": "none",
  "--kicker-case": "none",
  "--kicker-tracking": ".02em",
  "--sub-font": '"Commissioner", system-ui, sans-serif',
  "--sub-weight": "600",
  "--bg-motion": "grid",
  "--bg-intensity": ".7",
  "--radius-sm": "12px",
  "--radius-md": "16px",
  "--radius-lg": "20px",
  "--radius-xl": "24px",
  "--radius-pill": "999px",
  "--hairline": "1px",
  "--rule-size": "3px",
  "--rail-size": "3px",
  "--ring-size": "2px",
  "--dot-ring": "4px",
  "--ring-width": "9",
  "--chart-axis": "2px",
  "--chart-line-width": "6",
  "--chart-dot-ring": "5px",
  "--ba-line-width": "4px",
  "--code-hl-bar": "4px",
  "--space-xs": "6px",
  "--space-s": "12px",
  "--space-m": "18px",
  "--space-l": "24px",
  "--space-xl": "30px",
  "--space-2xl": "36px",
  "--space-3xl": "46px",
  "--code-name": "#819ea7",
  "--code-gutter": "#658089",
  "--code-kw": "#6fd6c4",
  "--code-str": "#8fcfa6",
  "--code-num": "#d9c7a0",
  "--code-fn": "#8fb4de",
  "--code-type": "#f0a08a",
  "--code-com": "#819ea7",
  "--code-pun": "#c0d7d6",
  "--code-bg": "#05080f",
  "--code-bar": "#0c1622",
  "--code-line": "#1d3340",
  "--code-ink": "#eefaf7",
  "--ba-line": "#ffffff",
  "--ba-knob-bg": "#ffffff",
  "--ba-knob-ink": "#111111",
  "--ba-label-bg": "rgba(8,10,16,.72)",
  "--ba-label-ink": "#ffffff",
  "--shadow-3": "0 30px 80px rgba(0,0,0,.45)",
  "--shadow-color": "rgba(0,0,0,.6)",
  "--px-edge": "rgba(255,255,255,.14)",
  "--px-dim": "brightness(.45) saturate(.8)",
  "--cta-sheen": "rgba(255,255,255,.38)",
  "--pv-glint": "#f3fffc",
  "--pv-glint-strength": ".5",
  "--pv-reflection": ".34",
  "--pv-shade": ".8",
  "--orbit-glow": "0 0 50px color-mix(in srgb,var(--acc2) 16%,transparent)",
  "--step-halo": "0 0 0 9px color-mix(in srgb,var(--acc) 22%,transparent)",
  "--dot-halo": "0 0 0 7px color-mix(in srgb,var(--acc) 20%,transparent)",
  "--code-caret": "3px 0 0 var(--acc2)",
  "--code-hl-shadow": "inset var(--code-hl-bar) 0 0 var(--acc)",
  "--cta-glow": "0 18px 50px color-mix(in srgb,var(--acc) 38%,transparent)",
  "--ba-line-shadow": "0 0 18px var(--shadow-color)",
  "--sc-spot": "rgba(111,214,196,.95)",
  "--sc-dim": "rgba(3,6,14,.6)",
  "--sc-accent-soft": "rgba(111,214,196,.42)",
  "--sc-fade": "#05080f",
  "--sc-cap-bg": "linear-gradient(180deg,rgba(14,32,44,.96),rgba(8,18,28,.96))",
  "--sc-cap-line": "#24506a",
  "--sc-cap-ink": "#eefaf7",
  "--sc-cap-bar": "#6fd6c4",
  "--sc-card-bg": "linear-gradient(135deg,rgba(12,22,34,.97),rgba(15,28,42,.95))",
  "--sc-card-line": "rgba(111,214,196,.5)",
  "--sc-card-ink": "#f2fffc",
  "--sc-card-body": "#c3dcdc",
  "--sc-card-accent": "#6fd6c4",
  "--sc-card-shadow": "0 20px 54px rgba(0,10,20,.55),inset 0 1px rgba(255,255,255,.08)",
  "--sc-card-accent-solid": "#6fd6c4",
  "--sc-lower-bar": "#6fd6c4",
  "--sc-sub-ink": "#ffffff",
  "--sc-sub-bg": "rgba(5,8,15,.9)",
  "--sc-sub-outline-ink": "#ffffff",
  "--sc-sub-outline": "#000000",
  "--sc-sub-accent": "#6fd6c4",
  "--sc-sub-outline-shadow": SUB_OUTLINE_SHADOW,
  "--sc-karaoke-ink": "#070b16",
  "--sc-karaoke-bg": "#6fd6c4",
  "--sc-badge-ink": "#070b16",
  "--sc-badge-bg": "#6fd6c4",
  "--sc-badge-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*1.2) rgba(0,0,0,.35)",
  "--sc-scrim": "radial-gradient(ellipse at 50% 50%,rgba(5,8,15,.86) 0%,rgba(5,8,15,.74) 60%,rgba(5,8,15,.8) 100%)",
  "--sc-title-ink": "#f2fffc",
  "--sc-title-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*2.4) rgba(0,0,0,.55)",
  "--sc-cap-shadow": "0 calc(var(--u)*1.2) calc(var(--u)*3.1) rgba(0,0,0,.65)",
  "--sc-sticker-shadow": "drop-shadow(0 calc(var(--u)*0.25) calc(var(--u)*0.6) rgba(0,0,0,.4))",
  "--sc-mark": "#6fd6c4",
  "--sc-glint": "linear-gradient(90deg,transparent,rgba(255,255,255,.18) 30%,rgba(255,255,255,.62) 50%,rgba(255,255,255,.18) 70%,transparent)",
  "--sc-glint-blend": "screen",
  "--sc-confetti": "#6fd6c4,#a8ebe0,#d9c7a0,#8fcfa6,#ffffff",
  "--sc-spark": "#eafffb",
  "--sc-spark-2": "#efe3c8",
  "--sc-loupe-ring": "#6fd6c4",
  "--sc-cursor-fill": "#f7f9ff",
  "--sc-cursor-line": "#0d1017",
  "--sc-cursor-shadow": "drop-shadow(0 calc(var(--u)*0.16) calc(var(--u)*0.31) rgba(0,0,0,.55))",
  "--sc-ripple-ring": "#6fd6c4",
  "--sc-ripple": "rgba(111,214,196,0.22)",
  "--sc-ripple-glint": "rgba(255,255,255,.35)",
  "--sc-keys-ink": "#f2fffc",
  "--sc-keys-bg": "linear-gradient(180deg,#242d38,#0c1622)",
  "--sc-keys-line": "#24506a",
  "--sc-keys-shadow": "0 6px 0 #05080f,0 14px 30px rgba(0,0,0,.45)",
  "--sc-progress": "#6fd6c4",
  "--sc-progress-track": "#00000059",
  "--sc-pip-ring": "#6fd6c4",
  "--sc-letterbox": "#05080f",
  "--dv-shadow": "0 34px 90px rgba(0,0,0,.42),0 10px 24px rgba(0,0,0,.25)",
  "--dv-bar-tint": "#ffffff",
  "--dv-bezel": "#0c0d11",
  "--dv-rim": "#3a3f4b",
  "--dv-island": "#07080b",
  "--dv-browser-shadow": "0 0 0 var(--hairline) var(--line),var(--dv-shadow)",
  "--dv-url-pad": "1.2em",
  "--dv-rim-width": "2px",
  "--sc-traffic-1": "#ff5f57",
  "--sc-traffic-2": "#febc2e",
  "--sc-traffic-3": "#28c840",
  "--tr-seam": "#5a9188",
  "--tr-iris": "#a89a7a",
  "--tr-flash": "#aef4ea",
  "--tr-fill": "#05080f",
  "--sc-card-radius": "calc(var(--u)*.94)",
  "--sc-radius": "calc(var(--u)*.6)",
  "--sc-sub-radius": "calc(var(--u)*.35)",
  "--sc-hairline": "1px",
  "--sc-cap-bar-size": "calc(var(--u)*0.16)",
  "--sc-spot-radius": "calc(var(--u)*0.73)",
  "--sc-spot-width": "calc(var(--u)*0.16)",
  "--sc-cursor-size": "calc(var(--u)*1.35)",
  "--sc-keys-radius": "12px",
  "--sc-keys-size": "26px",
  "--sc-cursor-line-width": "1.4",
  "--sc-sub-pad-y": "calc(var(--u)*0.12)",
  "--sc-badge-pad-x": "calc(var(--u)*0.9)",
  "--sc-badge-pad-y": "calc(var(--u)*0.35)",
  "--sc-spot-shadow": "0 0 0 var(--sc-spot-width) var(--sc-spot),0 0 0 9999px var(--sc-dim)",
  "--sc-karaoke-halo": "0 0 0 calc(var(--u)*0.12) var(--sc-karaoke-bg)",
  "--sc-ripple-shadow": "0 0 0 7px var(--sc-ripple),inset 0 0 0 3px var(--sc-ripple-glint)",
  "--sc-keys-pad": "10px 16px",
  "--sc-pad-x": "calc(var(--u)*1.7)",
  "--sc-pad-y": "calc(var(--u)*1.1)",
  "--sc-edge": "calc(var(--u)*2.3)",
  "--sc-mark-width": ".0042",
  "--sc-mark-head": ".016",
  "--sc-mark-wobble": ".0025",
  "--sc-arrow-width": ".0022",
  "--sc-arrow-head": ".009",
  "--sc-spark-width": ".0022",
  "--sc-ripple-size": ".0375",
  "--sc-scrim-blur": ".004",
  "--sc-loupe-ring-width": ".015",
  "--sc-pip-ring-width": ".02",
  "--sc-progress-size": ".006",
  "--tr-shade": ".55",
};

/**
 * Нейтральная — тема по умолчанию: серая бумага, тушь и один охристый акцент, заголовки Literata над
 * текстом Onest, код Martian Mono (как `neutral` в agentic-report). Без крема и терракоты, без
 * ночной синевы и без живого фона: ролик без решения об облике не носит ни одной модной эстетики.
 */
const NEUTRAL: ThemeVars = {
  "--bg": "#f5f5f3",
  "--glow": "#ebebe7",
  "--ink": "#16171a",
  "--body": "#2d2f33",
  "--mut": "#5b5e65",
  "--line": "#dededa",
  "--card": "#fbfbfa",
  "--node": "#fbfbfa",
  "--node-line": "#aeafaa",
  "--acc": "#8a5c00",
  "--acc2": "#4a5561",
  "--bad": "#b3402a",
  "--good": "#3f7a4f",
  "--bad-line": "#e8b4a8",
  "--sans": '"Onest", system-ui, sans-serif',
  "--mono": '"Martian Mono", ui-monospace, monospace',
  "--display": '"Literata", Georgia, serif',
  "--display-weight": "600",
  "--display-tracking": ".01em",
  "--display-case": "none",
  "--kicker-case": "none",
  "--kicker-tracking": ".02em",
  "--sub-font": '"Onest", system-ui, sans-serif',
  "--sub-weight": "600",
  "--bg-motion": "none",
  "--bg-intensity": ".35",
  "--radius-sm": "4px",
  "--radius-md": "6px",
  "--radius-lg": "8px",
  "--radius-xl": "10px",
  "--radius-pill": "999px",
  "--hairline": "1px",
  "--rule-size": "3px",
  "--rail-size": "3px",
  "--ring-size": "2px",
  "--dot-ring": "4px",
  "--ring-width": "9",
  "--chart-axis": "2px",
  "--chart-line-width": "6",
  "--chart-dot-ring": "5px",
  "--ba-line-width": "4px",
  "--code-hl-bar": "4px",
  "--space-xs": "6px",
  "--space-s": "12px",
  "--space-m": "18px",
  "--space-l": "24px",
  "--space-xl": "30px",
  "--space-2xl": "36px",
  "--space-3xl": "46px",
  "--code-name": "#5b5e65",
  "--code-gutter": "#62635e",
  "--code-kw": "#6d4800",
  "--code-str": "#3f6b4f",
  "--code-num": "#2f5f8a",
  "--code-fn": "#6b4a8c",
  "--code-type": "#8a4a2a",
  "--code-com": "#5b5e65",
  "--code-pun": "#2d2f33",
  "--code-bg": "#f0f0ed",
  "--code-bar": "#e8e8e4",
  "--code-line": "#dededa",
  "--code-ink": "#1f2126",
  "--ba-line": "#8a5c00",
  "--ba-knob-bg": "#8a5c00",
  "--ba-knob-ink": "#ffffff",
  "--ba-label-bg": "rgba(255,255,255,.88)",
  "--ba-label-ink": "#16171a",
  "--shadow-3": "0 30px 80px rgba(22,23,26,.16)",
  "--shadow-color": "rgba(22,23,26,.35)",
  "--px-edge": "rgba(22,23,26,.14)",
  "--px-dim": "brightness(.8) saturate(.85)",
  "--cta-sheen": "rgba(255,255,255,.55)",
  "--pv-glint": "#ffffff",
  "--pv-glint-strength": ".5",
  "--pv-reflection": ".34",
  "--pv-shade": ".8",
  "--orbit-glow": "0 0 50px color-mix(in srgb,var(--acc2) 16%,transparent)",
  "--step-halo": "0 0 0 9px color-mix(in srgb,var(--acc) 22%,transparent)",
  "--dot-halo": "0 0 0 7px color-mix(in srgb,var(--acc) 20%,transparent)",
  "--code-caret": "3px 0 0 var(--acc2)",
  "--code-hl-shadow": "inset var(--code-hl-bar) 0 0 var(--acc)",
  "--cta-glow": "0 18px 50px color-mix(in srgb,var(--acc) 38%,transparent)",
  "--ba-line-shadow": "0 0 18px var(--shadow-color)",
  "--sc-spot": "rgba(138,92,0,.95)",
  "--sc-dim": "rgba(22,23,26,.38)",
  "--sc-accent-soft": "rgba(138,92,0,.32)",
  "--sc-fade": "#f5f5f3",
  "--sc-cap-bg": "rgba(251,251,250,.98)",
  "--sc-cap-line": "#dededa",
  "--sc-cap-ink": "#16171a",
  "--sc-cap-bar": "#8a5c00",
  "--sc-card-bg": "rgba(251,251,250,.98)",
  "--sc-card-line": "#d6d6d1",
  "--sc-card-ink": "#16171a",
  "--sc-card-body": "#3d3f44",
  "--sc-card-accent": "#8a5c00",
  "--sc-card-shadow": "0 1px 0 rgba(22,23,26,.06),0 10px 28px rgba(22,23,26,.08)",
  "--sc-card-accent-solid": "#8a5c00",
  "--sc-lower-bar": "#8a5c00",
  "--sc-sub-ink": "#16171a",
  "--sc-sub-bg": "rgba(255,255,255,.9)",
  "--sc-sub-outline-ink": "#ffffff",
  "--sc-sub-outline": "#000000",
  "--sc-sub-accent": "#e2b556",
  "--sc-sub-outline-shadow": SUB_OUTLINE_SHADOW,
  "--sc-karaoke-ink": "#ffffff",
  "--sc-karaoke-bg": "#8a5c00",
  "--sc-badge-ink": "#ffffff",
  "--sc-badge-bg": "#8a5c00",
  "--sc-badge-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*1.2) rgba(22,23,26,.18)",
  "--sc-scrim": "radial-gradient(ellipse at 50% 50%,rgba(245,245,243,.9) 0%,rgba(245,245,243,.82) 60%,rgba(245,245,243,.86) 100%)",
  "--sc-title-ink": "#16171a",
  "--sc-title-shadow": "0 calc(var(--u)*0.2) calc(var(--u)*1.6) rgba(255,255,255,.7)",
  "--sc-cap-shadow": "0 calc(var(--u)*1.1) calc(var(--u)*3) rgba(40,40,60,.18)",
  "--sc-sticker-shadow": "drop-shadow(0 calc(var(--u)*0.25) calc(var(--u)*0.6) rgba(40,40,60,.22))",
  "--sc-mark": "#8a5c00",
  "--sc-glint": "linear-gradient(90deg,transparent,rgba(138,92,0,0.14) 30%,rgba(138,92,0,0.38) 50%,rgba(138,92,0,0.14) 70%,transparent)",
  "--sc-glint-blend": "normal",
  "--sc-confetti": "#8a5c00,#4a5561,#3f7a4f,#b3402a,#16171a",
  "--sc-spark": "#8a5c00",
  "--sc-spark-2": "#e2b556",
  "--sc-loupe-ring": "#8a5c00",
  "--sc-cursor-fill": "#16171a",
  "--sc-cursor-line": "#ffffff",
  "--sc-cursor-shadow": "drop-shadow(0 calc(var(--u)*0.16) calc(var(--u)*0.31) rgba(0,0,0,.3))",
  "--sc-ripple-ring": "#8a5c00",
  "--sc-ripple": "rgba(138,92,0,0.22)",
  "--sc-ripple-glint": "rgba(255,255,255,.6)",
  "--sc-keys-ink": "#16171a",
  "--sc-keys-bg": "linear-gradient(180deg,#ffffff,#eeeeeb)",
  "--sc-keys-line": "#dededa",
  "--sc-keys-shadow": "0 6px 0 #d6d6d1,0 14px 30px rgba(22,23,26,.18)",
  "--sc-progress": "#8a5c00",
  "--sc-progress-track": "#16171a33",
  "--sc-pip-ring": "#8a5c00",
  "--sc-letterbox": "#f5f5f3",
  "--dv-shadow": "0 34px 90px rgba(22,23,26,.18),0 10px 24px rgba(22,23,26,.1)",
  "--dv-bar-tint": "#ffffff",
  "--dv-bezel": "#1c1c1a",
  "--dv-rim": "#aeafaa",
  "--dv-island": "#07080b",
  "--dv-browser-shadow": "0 0 0 var(--hairline) var(--line),var(--dv-shadow)",
  "--dv-url-pad": "1.2em",
  "--dv-rim-width": "2px",
  "--sc-traffic-1": "#ff5f57",
  "--sc-traffic-2": "#febc2e",
  "--sc-traffic-3": "#28c840",
  "--tr-seam": "#6b6a64",
  "--tr-iris": "#8a7a55",
  "--tr-flash": "#ffffff",
  "--tr-fill": "#f5f5f3",
  "--sc-card-radius": "calc(var(--u)*.3)",
  "--sc-radius": "calc(var(--u)*.2)",
  "--sc-sub-radius": "calc(var(--u)*.15)",
  "--sc-hairline": "1px",
  "--sc-cap-bar-size": "calc(var(--u)*0.16)",
  "--sc-spot-radius": "calc(var(--u)*0.73)",
  "--sc-spot-width": "calc(var(--u)*0.16)",
  "--sc-cursor-size": "calc(var(--u)*1.35)",
  "--sc-keys-radius": "12px",
  "--sc-keys-size": "26px",
  "--sc-cursor-line-width": "1.4",
  "--sc-sub-pad-y": "calc(var(--u)*0.12)",
  "--sc-badge-pad-x": "calc(var(--u)*0.9)",
  "--sc-badge-pad-y": "calc(var(--u)*0.35)",
  "--sc-spot-shadow": "0 0 0 var(--sc-spot-width) var(--sc-spot),0 0 0 9999px var(--sc-dim)",
  "--sc-karaoke-halo": "0 0 0 calc(var(--u)*0.12) var(--sc-karaoke-bg)",
  "--sc-ripple-shadow": "0 0 0 7px var(--sc-ripple),inset 0 0 0 3px var(--sc-ripple-glint)",
  "--sc-keys-pad": "10px 16px",
  "--sc-pad-x": "calc(var(--u)*1.7)",
  "--sc-pad-y": "calc(var(--u)*1.1)",
  "--sc-edge": "calc(var(--u)*2.3)",
  "--sc-mark-width": ".0042",
  "--sc-mark-head": ".016",
  "--sc-mark-wobble": ".0025",
  "--sc-arrow-width": ".0022",
  "--sc-arrow-head": ".009",
  "--sc-spark-width": ".0022",
  "--sc-ripple-size": ".0375",
  "--sc-scrim-blur": ".004",
  "--sc-loupe-ring-width": ".015",
  "--sc-pip-ring-width": ".02",
  "--sc-progress-size": ".006",
  "--tr-shade": ".55",
};

/**
 * Иней: две краски и один материал — светлый камень и графит, заголовки Onest над IBM Plex Sans.
 * Акцент — сам графит, поэтому цвет остаётся статусам (успех, риск) и слову караоке — стали
 * `#9fb2c8`; как `frost` в agentic-report.
 */
const FROST: ThemeVars = {
  "--bg": "#eef0f3",
  "--glow": "#dfe3ea",
  "--ink": "#262b37",
  "--body": "#383e4e",
  "--mut": "#565d6e",
  "--line": "#d6dae1",
  "--card": "#f7f8fa",
  "--node": "#f7f8fa",
  "--node-line": "#a3a9b6",
  "--acc": "#383e4e",
  "--acc2": "#565d6e",
  "--bad": "#b2362f",
  "--good": "#2f7250",
  "--bad-line": "#e6b1ac",
  "--sans": '"IBM Plex Sans", system-ui, sans-serif',
  "--mono": '"Geist Mono", ui-monospace, monospace',
  "--display": '"Onest", system-ui, sans-serif',
  "--display-weight": "600",
  "--display-tracking": ".005em",
  "--display-case": "none",
  "--kicker-case": "none",
  "--kicker-tracking": ".02em",
  "--sub-font": '"IBM Plex Sans", system-ui, sans-serif',
  "--sub-weight": "600",
  "--bg-motion": "none",
  "--bg-intensity": ".35",
  "--radius-sm": "4px",
  "--radius-md": "6px",
  "--radius-lg": "8px",
  "--radius-xl": "10px",
  "--radius-pill": "999px",
  "--hairline": "1px",
  "--rule-size": "3px",
  "--rail-size": "3px",
  "--ring-size": "2px",
  "--dot-ring": "4px",
  "--ring-width": "9",
  "--chart-axis": "2px",
  "--chart-line-width": "6",
  "--chart-dot-ring": "5px",
  "--ba-line-width": "4px",
  "--code-hl-bar": "4px",
  "--space-xs": "6px",
  "--space-s": "12px",
  "--space-m": "18px",
  "--space-l": "24px",
  "--space-xl": "30px",
  "--space-2xl": "36px",
  "--space-3xl": "46px",
  "--code-name": "#565d6e",
  "--code-gutter": "#5d6372",
  "--code-kw": "#8a3a2f",
  "--code-str": "#2f6b4f",
  "--code-num": "#3f5670",
  "--code-fn": "#5a4a7a",
  "--code-type": "#7a5200",
  "--code-com": "#565d6e",
  "--code-pun": "#383e4e",
  "--code-bg": "#e8ebef",
  "--code-bar": "#e1e5ea",
  "--code-line": "#d6dae1",
  "--code-ink": "#262b37",
  "--ba-line": "#383e4e",
  "--ba-knob-bg": "#383e4e",
  "--ba-knob-ink": "#ffffff",
  "--ba-label-bg": "rgba(255,255,255,.88)",
  "--ba-label-ink": "#262b37",
  "--shadow-3": "0 30px 80px rgba(38,43,55,.16)",
  "--shadow-color": "rgba(38,43,55,.35)",
  "--px-edge": "rgba(38,43,55,.14)",
  "--px-dim": "brightness(.8) saturate(.85)",
  "--cta-sheen": "rgba(255,255,255,.55)",
  "--pv-glint": "#ffffff",
  "--pv-glint-strength": ".5",
  "--pv-reflection": ".34",
  "--pv-shade": ".8",
  "--orbit-glow": "0 0 50px color-mix(in srgb,var(--acc2) 16%,transparent)",
  "--step-halo": "0 0 0 9px color-mix(in srgb,var(--acc) 22%,transparent)",
  "--dot-halo": "0 0 0 7px color-mix(in srgb,var(--acc) 20%,transparent)",
  "--code-caret": "3px 0 0 var(--acc2)",
  "--code-hl-shadow": "inset var(--code-hl-bar) 0 0 var(--acc)",
  "--cta-glow": "0 18px 50px color-mix(in srgb,var(--acc) 38%,transparent)",
  "--ba-line-shadow": "0 0 18px var(--shadow-color)",
  "--sc-spot": "rgba(56,62,78,.95)",
  "--sc-dim": "rgba(38,43,55,.38)",
  "--sc-accent-soft": "rgba(56,62,78,.32)",
  "--sc-fade": "#eef0f3",
  "--sc-cap-bg": "rgba(247,248,250,.98)",
  "--sc-cap-line": "#d6dae1",
  "--sc-cap-ink": "#262b37",
  "--sc-cap-bar": "#383e4e",
  "--sc-card-bg": "rgba(247,248,250,.98)",
  "--sc-card-line": "#c9ced6",
  "--sc-card-ink": "#262b37",
  "--sc-card-body": "#3a4050",
  "--sc-card-accent": "#383e4e",
  "--sc-card-shadow": "0 1px 0 rgba(38,43,55,.06),0 10px 28px rgba(38,43,55,.08)",
  "--sc-card-accent-solid": "#383e4e",
  "--sc-lower-bar": "#383e4e",
  "--sc-sub-ink": "#262b37",
  "--sc-sub-bg": "rgba(255,255,255,.9)",
  "--sc-sub-outline-ink": "#ffffff",
  "--sc-sub-outline": "#000000",
  "--sc-sub-accent": "#9fb2c8",
  "--sc-sub-outline-shadow": SUB_OUTLINE_SHADOW,
  "--sc-karaoke-ink": "#ffffff",
  "--sc-karaoke-bg": "#383e4e",
  "--sc-badge-ink": "#ffffff",
  "--sc-badge-bg": "#383e4e",
  "--sc-badge-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*1.2) rgba(38,43,55,.18)",
  "--sc-scrim": "radial-gradient(ellipse at 50% 50%,rgba(238,240,243,.9) 0%,rgba(238,240,243,.82) 60%,rgba(238,240,243,.86) 100%)",
  "--sc-title-ink": "#262b37",
  "--sc-title-shadow": "0 calc(var(--u)*0.2) calc(var(--u)*1.6) rgba(255,255,255,.7)",
  "--sc-cap-shadow": "0 calc(var(--u)*1.1) calc(var(--u)*3) rgba(40,40,60,.18)",
  "--sc-sticker-shadow": "drop-shadow(0 calc(var(--u)*0.25) calc(var(--u)*0.6) rgba(40,40,60,.22))",
  "--sc-mark": "#383e4e",
  "--sc-glint": "linear-gradient(90deg,transparent,rgba(159,178,200,0.24) 30%,rgba(159,178,200,0.7) 50%,rgba(159,178,200,0.24) 70%,transparent)",
  "--sc-glint-blend": "normal",
  "--sc-confetti": "#383e4e,#565d6e,#2f7250,#b2362f,#262b37",
  "--sc-spark": "#383e4e",
  "--sc-spark-2": "#9fb2c8",
  "--sc-loupe-ring": "#383e4e",
  "--sc-cursor-fill": "#262b37",
  "--sc-cursor-line": "#ffffff",
  "--sc-cursor-shadow": "drop-shadow(0 calc(var(--u)*0.16) calc(var(--u)*0.31) rgba(0,0,0,.3))",
  "--sc-ripple-ring": "#383e4e",
  "--sc-ripple": "rgba(56,62,78,0.22)",
  "--sc-ripple-glint": "rgba(255,255,255,.6)",
  "--sc-keys-ink": "#262b37",
  "--sc-keys-bg": "linear-gradient(180deg,#ffffff,#e6e9ed)",
  "--sc-keys-line": "#d6dae1",
  "--sc-keys-shadow": "0 6px 0 #c9ced6,0 14px 30px rgba(38,43,55,.18)",
  "--sc-progress": "#383e4e",
  "--sc-progress-track": "#262b3733",
  "--sc-pip-ring": "#383e4e",
  "--sc-letterbox": "#eef0f3",
  "--dv-shadow": "0 34px 90px rgba(38,43,55,.18),0 10px 24px rgba(38,43,55,.1)",
  "--dv-bar-tint": "#ffffff",
  "--dv-bezel": "#1b1e25",
  "--dv-rim": "#a3a9b6",
  "--dv-island": "#07080b",
  "--dv-browser-shadow": "0 0 0 var(--hairline) var(--line),var(--dv-shadow)",
  "--dv-url-pad": "1.2em",
  "--dv-rim-width": "2px",
  "--sc-traffic-1": "#ff5f57",
  "--sc-traffic-2": "#febc2e",
  "--sc-traffic-3": "#28c840",
  "--tr-seam": "#565d6e",
  "--tr-iris": "#7d8494",
  "--tr-flash": "#ffffff",
  "--tr-fill": "#eef0f3",
  "--sc-card-radius": "calc(var(--u)*.3)",
  "--sc-radius": "calc(var(--u)*.2)",
  "--sc-sub-radius": "calc(var(--u)*.15)",
  "--sc-hairline": "1px",
  "--sc-cap-bar-size": "calc(var(--u)*0.16)",
  "--sc-spot-radius": "calc(var(--u)*0.73)",
  "--sc-spot-width": "calc(var(--u)*0.16)",
  "--sc-cursor-size": "calc(var(--u)*1.35)",
  "--sc-keys-radius": "12px",
  "--sc-keys-size": "26px",
  "--sc-cursor-line-width": "1.4",
  "--sc-sub-pad-y": "calc(var(--u)*0.12)",
  "--sc-badge-pad-x": "calc(var(--u)*0.9)",
  "--sc-badge-pad-y": "calc(var(--u)*0.35)",
  "--sc-spot-shadow": "0 0 0 var(--sc-spot-width) var(--sc-spot),0 0 0 9999px var(--sc-dim)",
  "--sc-karaoke-halo": "0 0 0 calc(var(--u)*0.12) var(--sc-karaoke-bg)",
  "--sc-ripple-shadow": "0 0 0 7px var(--sc-ripple),inset 0 0 0 3px var(--sc-ripple-glint)",
  "--sc-keys-pad": "10px 16px",
  "--sc-pad-x": "calc(var(--u)*1.7)",
  "--sc-pad-y": "calc(var(--u)*1.1)",
  "--sc-edge": "calc(var(--u)*2.3)",
  "--sc-mark-width": ".0042",
  "--sc-mark-head": ".016",
  "--sc-mark-wobble": ".0025",
  "--sc-arrow-width": ".0022",
  "--sc-arrow-head": ".009",
  "--sc-spark-width": ".0022",
  "--sc-ripple-size": ".0375",
  "--sc-scrim-blur": ".004",
  "--sc-loupe-ring-width": ".015",
  "--sc-pip-ring-width": ".02",
  "--sc-progress-size": ".006",
  "--tr-shade": ".55",
};

/**
 * Дневная: светлый интерфейсный фон, графитовый текст, кобальт и петроль вместо индиго и
 * бирюзы палитры Tailwind, заголовки Onest. Для продуктовой документации и релизов.
 */
const DAYLIGHT: ThemeVars = {
  "--bg": "#f7f8fa",
  "--glow": "#e3ecfa",
  "--ink": "#121620",
  "--body": "#313846",
  "--mut": "#555d6c",
  "--line": "#e2e5ea",
  "--card": "#ffffff",
  "--node": "#ffffff",
  "--node-line": "#d6dae1",
  "--acc": "#1f5bb8",
  "--acc2": "#0e6f82",
  "--bad": "#b8362f",
  "--good": "#2f7a4f",
  "--bad-line": "#eab0aa",
  "--sans": '"Golos Text", system-ui, sans-serif',
  "--mono": '"Geist Mono", ui-monospace, monospace',
  "--display": '"Onest", system-ui, sans-serif',
  "--display-weight": "680",
  "--display-tracking": "0em",
  "--display-case": "none",
  "--kicker-case": "none",
  "--kicker-tracking": ".02em",
  "--sub-font": '"Golos Text", system-ui, sans-serif',
  "--sub-weight": "600",
  "--bg-motion": "grid",
  "--bg-intensity": ".35",
  "--radius-sm": "11px",
  "--radius-md": "14px",
  "--radius-lg": "18px",
  "--radius-xl": "21px",
  "--radius-pill": "999px",
  "--hairline": "1px",
  "--rule-size": "3px",
  "--rail-size": "3px",
  "--ring-size": "2px",
  "--dot-ring": "4px",
  "--ring-width": "9",
  "--chart-axis": "2px",
  "--chart-line-width": "6",
  "--chart-dot-ring": "5px",
  "--ba-line-width": "4px",
  "--code-hl-bar": "4px",
  "--space-xs": "6px",
  "--space-s": "12px",
  "--space-m": "18px",
  "--space-l": "24px",
  "--space-xl": "30px",
  "--space-2xl": "36px",
  "--space-3xl": "46px",
  "--code-name": "#5a6170",
  "--code-gutter": "#69707e",
  "--code-kw": "#a2352a",
  "--code-str": "#2f6b4f",
  "--code-num": "#1f5bb8",
  "--code-fn": "#6b4a8c",
  "--code-type": "#8a5c00",
  "--code-com": "#5a6170",
  "--code-pun": "#2a303b",
  "--code-bg": "#f3f5f8",
  "--code-bar": "#eceff3",
  "--code-line": "#d6dae1",
  "--code-ink": "#1c2029",
  "--ba-line": "#1f5bb8",
  "--ba-knob-bg": "#1f5bb8",
  "--ba-knob-ink": "#ffffff",
  "--ba-label-bg": "rgba(255,255,255,.88)",
  "--ba-label-ink": "#121620",
  "--shadow-3": "0 30px 80px rgba(18,22,32,.16)",
  "--shadow-color": "rgba(18,22,32,.35)",
  "--px-edge": "rgba(18,22,32,.14)",
  "--px-dim": "brightness(.8) saturate(.85)",
  "--cta-sheen": "rgba(255,255,255,.55)",
  "--pv-glint": "#ffffff",
  "--pv-glint-strength": ".5",
  "--pv-reflection": ".34",
  "--pv-shade": ".8",
  "--orbit-glow": "0 0 50px color-mix(in srgb,var(--acc2) 16%,transparent)",
  "--step-halo": "0 0 0 9px color-mix(in srgb,var(--acc) 22%,transparent)",
  "--dot-halo": "0 0 0 7px color-mix(in srgb,var(--acc) 20%,transparent)",
  "--code-caret": "3px 0 0 var(--acc2)",
  "--code-hl-shadow": "inset var(--code-hl-bar) 0 0 var(--acc)",
  "--cta-glow": "0 18px 50px color-mix(in srgb,var(--acc) 38%,transparent)",
  "--ba-line-shadow": "0 0 18px var(--shadow-color)",
  "--sc-spot": "rgba(31,91,184,.95)",
  "--sc-dim": "rgba(18,22,32,.38)",
  "--sc-accent-soft": "rgba(31,91,184,.32)",
  "--sc-fade": "#f7f8fa",
  "--sc-cap-bg": "linear-gradient(180deg,rgba(255,255,255,.98),rgba(243,245,248,.98))",
  "--sc-cap-line": "#e2e5ea",
  "--sc-cap-ink": "#121620",
  "--sc-cap-bar": "#1f5bb8",
  "--sc-card-bg": "linear-gradient(135deg,rgba(255,255,255,.99),rgba(243,245,248,.98))",
  "--sc-card-line": "rgba(31,91,184,.3)",
  "--sc-card-ink": "#121620",
  "--sc-card-body": "#3d4452",
  "--sc-card-accent": "#1f5bb8",
  "--sc-card-shadow": "0 18px 44px rgba(18,22,32,.14),0 2px 6px rgba(18,22,32,.06)",
  "--sc-card-accent-solid": "#1f5bb8",
  "--sc-lower-bar": "#1f5bb8",
  "--sc-sub-ink": "#121620",
  "--sc-sub-bg": "rgba(255,255,255,.9)",
  "--sc-sub-outline-ink": "#ffffff",
  "--sc-sub-outline": "#000000",
  "--sc-sub-accent": "#86b4f5",
  "--sc-sub-outline-shadow": SUB_OUTLINE_SHADOW,
  "--sc-karaoke-ink": "#ffffff",
  "--sc-karaoke-bg": "#1f5bb8",
  "--sc-badge-ink": "#ffffff",
  "--sc-badge-bg": "#1f5bb8",
  "--sc-badge-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*1.2) rgba(18,22,32,.18)",
  "--sc-scrim": "radial-gradient(ellipse at 50% 50%,rgba(247,248,250,.9) 0%,rgba(247,248,250,.82) 60%,rgba(247,248,250,.86) 100%)",
  "--sc-title-ink": "#121620",
  "--sc-title-shadow": "0 calc(var(--u)*0.2) calc(var(--u)*1.6) rgba(255,255,255,.7)",
  "--sc-cap-shadow": "0 calc(var(--u)*1.1) calc(var(--u)*3) rgba(40,40,60,.18)",
  "--sc-sticker-shadow": "drop-shadow(0 calc(var(--u)*0.25) calc(var(--u)*0.6) rgba(40,40,60,.22))",
  "--sc-mark": "#1f5bb8",
  "--sc-glint": "linear-gradient(90deg,transparent,rgba(31,91,184,0.22) 30%,rgba(31,91,184,0.55) 50%,rgba(31,91,184,0.22) 70%,transparent)",
  "--sc-glint-blend": "normal",
  "--sc-confetti": "#1f5bb8,#0e6f82,#2f7a4f,#b8362f,#121620",
  "--sc-spark": "#1f5bb8",
  "--sc-spark-2": "#0e6f82",
  "--sc-loupe-ring": "#1f5bb8",
  "--sc-cursor-fill": "#121620",
  "--sc-cursor-line": "#ffffff",
  "--sc-cursor-shadow": "drop-shadow(0 calc(var(--u)*0.16) calc(var(--u)*0.31) rgba(0,0,0,.3))",
  "--sc-ripple-ring": "#1f5bb8",
  "--sc-ripple": "rgba(31,91,184,0.22)",
  "--sc-ripple-glint": "rgba(255,255,255,.6)",
  "--sc-keys-ink": "#121620",
  "--sc-keys-bg": "linear-gradient(180deg,#ffffff,#eef1f6)",
  "--sc-keys-line": "#e2e5ea",
  "--sc-keys-shadow": "0 6px 0 #d5dae3,0 14px 30px rgba(18,22,32,.18)",
  "--sc-progress": "#1f5bb8",
  "--sc-progress-track": "#12162033",
  "--sc-pip-ring": "#1f5bb8",
  "--sc-letterbox": "#f7f8fa",
  "--dv-shadow": "0 34px 90px rgba(18,22,32,.18),0 10px 24px rgba(18,22,32,.1)",
  "--dv-bar-tint": "#ffffff",
  "--dv-bezel": "#22262e",
  "--dv-rim": "#9aa3b2",
  "--dv-island": "#07080b",
  "--dv-browser-shadow": "0 0 0 var(--hairline) var(--line),var(--dv-shadow)",
  "--dv-url-pad": "1.2em",
  "--dv-rim-width": "2px",
  "--sc-traffic-1": "#ff5f57",
  "--sc-traffic-2": "#febc2e",
  "--sc-traffic-3": "#28c840",
  "--tr-seam": "#3d5a85",
  "--tr-iris": "#4d7884",
  "--tr-flash": "#ffffff",
  "--tr-fill": "#f7f8fa",
  "--sc-card-radius": "calc(var(--u)*.836)",
  "--sc-radius": "calc(var(--u)*.533)",
  "--sc-sub-radius": "calc(var(--u)*.311)",
  "--sc-hairline": "1px",
  "--sc-cap-bar-size": "calc(var(--u)*0.16)",
  "--sc-spot-radius": "calc(var(--u)*0.73)",
  "--sc-spot-width": "calc(var(--u)*0.16)",
  "--sc-cursor-size": "calc(var(--u)*1.35)",
  "--sc-keys-radius": "12px",
  "--sc-keys-size": "26px",
  "--sc-cursor-line-width": "1.4",
  "--sc-sub-pad-y": "calc(var(--u)*0.12)",
  "--sc-badge-pad-x": "calc(var(--u)*0.9)",
  "--sc-badge-pad-y": "calc(var(--u)*0.35)",
  "--sc-spot-shadow": "0 0 0 var(--sc-spot-width) var(--sc-spot),0 0 0 9999px var(--sc-dim)",
  "--sc-karaoke-halo": "0 0 0 calc(var(--u)*0.12) var(--sc-karaoke-bg)",
  "--sc-ripple-shadow": "0 0 0 7px var(--sc-ripple),inset 0 0 0 3px var(--sc-ripple-glint)",
  "--sc-keys-pad": "10px 16px",
  "--sc-pad-x": "calc(var(--u)*1.7)",
  "--sc-pad-y": "calc(var(--u)*1.1)",
  "--sc-edge": "calc(var(--u)*2.3)",
  "--sc-mark-width": ".0042",
  "--sc-mark-head": ".016",
  "--sc-mark-wobble": ".0025",
  "--sc-arrow-width": ".0022",
  "--sc-arrow-head": ".009",
  "--sc-spark-width": ".0022",
  "--sc-ripple-size": ".0375",
  "--sc-scrim-blur": ".004",
  "--sc-loupe-ring-width": ".015",
  "--sc-pip-ring-width": ".02",
  "--sc-progress-size": ".006",
  "--tr-shade": ".55",
};

/**
 * Угли: почти чёрный тёплый фон, один оранжевый сигнал и тёплый серый для надзаголовков,
 * заголовки Oswald капсом. Для анонсов и запусков.
 */
const EMBER: ThemeVars = {
  "--bg": "#0e0907",
  "--glow": "#2a120a",
  "--ink": "#fff4ec",
  "--body": "#e3cdbf",
  "--mut": "#ad907f",
  "--line": "#3a2419",
  "--card": "#170f0b",
  "--node": "#1c120d",
  "--node-line": "#4a2c1e",
  "--acc": "#ff7a3d",
  "--acc2": "#c9b8a8",
  "--bad": "#ff6b6b",
  "--good": "#9be38b",
  "--bad-line": "#6f322f",
  "--sans": '"Rubik", system-ui, sans-serif',
  "--mono": '"JetBrains Mono", ui-monospace, monospace',
  "--display": '"Oswald", system-ui, sans-serif',
  "--display-weight": "600",
  "--display-tracking": ".05em",
  "--display-case": "uppercase",
  "--kicker-case": "none",
  "--kicker-tracking": ".02em",
  "--sub-font": '"Rubik", system-ui, sans-serif',
  "--sub-weight": "600",
  "--bg-motion": "grid",
  "--bg-intensity": ".75",
  "--radius-sm": "9px",
  "--radius-md": "12px",
  "--radius-lg": "16px",
  "--radius-xl": "19px",
  "--radius-pill": "999px",
  "--hairline": "1px",
  "--rule-size": "3px",
  "--rail-size": "3px",
  "--ring-size": "2px",
  "--dot-ring": "4px",
  "--ring-width": "9",
  "--chart-axis": "2px",
  "--chart-line-width": "6",
  "--chart-dot-ring": "5px",
  "--ba-line-width": "4px",
  "--code-hl-bar": "4px",
  "--space-xs": "6px",
  "--space-s": "12px",
  "--space-m": "18px",
  "--space-l": "24px",
  "--space-xl": "30px",
  "--space-2xl": "36px",
  "--space-3xl": "46px",
  "--code-name": "#ad907f",
  "--code-gutter": "#8f7465",
  "--code-kw": "#ff7a3d",
  "--code-str": "#9be38b",
  "--code-num": "#ffc15e",
  "--code-fn": "#ffd9b3",
  "--code-type": "#ff6b6b",
  "--code-com": "#ad907f",
  "--code-pun": "#e3cdbf",
  "--code-bg": "#070403",
  "--code-bar": "#170f0b",
  "--code-line": "#3a2419",
  "--code-ink": "#fff4ec",
  "--ba-line": "#ffffff",
  "--ba-knob-bg": "#ffffff",
  "--ba-knob-ink": "#111111",
  "--ba-label-bg": "rgba(8,10,16,.72)",
  "--ba-label-ink": "#ffffff",
  "--shadow-3": "0 30px 80px rgba(0,0,0,.45)",
  "--shadow-color": "rgba(0,0,0,.6)",
  "--px-edge": "rgba(255,255,255,.14)",
  "--px-dim": "brightness(.45) saturate(.8)",
  "--cta-sheen": "rgba(255,255,255,.38)",
  "--pv-glint": "#fff8ec",
  "--pv-glint-strength": ".5",
  "--pv-reflection": ".34",
  "--pv-shade": ".8",
  "--orbit-glow": "0 0 50px color-mix(in srgb,var(--acc2) 16%,transparent)",
  "--step-halo": "0 0 0 9px color-mix(in srgb,var(--acc) 22%,transparent)",
  "--dot-halo": "0 0 0 7px color-mix(in srgb,var(--acc) 20%,transparent)",
  "--code-caret": "3px 0 0 var(--acc2)",
  "--code-hl-shadow": "inset var(--code-hl-bar) 0 0 var(--acc)",
  "--cta-glow": "0 18px 50px color-mix(in srgb,var(--acc) 38%,transparent)",
  "--ba-line-shadow": "0 0 18px var(--shadow-color)",
  "--sc-spot": "rgba(255,122,61,.95)",
  "--sc-dim": "rgba(8,4,2,.62)",
  "--sc-accent-soft": "rgba(255,122,61,.42)",
  "--sc-fade": "#070403",
  "--sc-cap-bg": "linear-gradient(180deg,rgba(38,20,12,.96),rgba(22,12,8,.96))",
  "--sc-cap-line": "#5a3320",
  "--sc-cap-ink": "#fff4ec",
  "--sc-cap-bar": "#ff7a3d",
  "--sc-card-bg": "linear-gradient(135deg,rgba(40,20,12,.96),rgba(20,11,7,.95))",
  "--sc-card-line": "rgba(255,122,61,.5)",
  "--sc-card-ink": "#fff4ec",
  "--sc-card-body": "#e6cdbd",
  "--sc-card-accent": "#ff7a3d",
  "--sc-card-shadow": "0 20px 54px rgba(20,6,0,.6),inset 0 1px rgba(255,255,255,.07)",
  "--sc-card-accent-solid": "#ff7a3d",
  "--sc-lower-bar": "#ff7a3d",
  "--sc-sub-ink": "#ffffff",
  "--sc-sub-bg": "rgba(7,4,3,.9)",
  "--sc-sub-outline-ink": "#ffffff",
  "--sc-sub-outline": "#000000",
  "--sc-sub-accent": "#ff9a5c",
  "--sc-sub-outline-shadow": SUB_OUTLINE_SHADOW,
  "--sc-karaoke-ink": "#0e0907",
  "--sc-karaoke-bg": "#ff7a3d",
  "--sc-badge-ink": "#0e0907",
  "--sc-badge-bg": "#ff7a3d",
  "--sc-badge-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*1.2) rgba(0,0,0,.35)",
  "--sc-scrim": "radial-gradient(ellipse at 50% 50%,rgba(7,4,3,.86) 0%,rgba(7,4,3,.74) 60%,rgba(7,4,3,.8) 100%)",
  "--sc-title-ink": "#fff4ec",
  "--sc-title-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*2.4) rgba(0,0,0,.55)",
  "--sc-cap-shadow": "0 calc(var(--u)*1.2) calc(var(--u)*3.1) rgba(0,0,0,.65)",
  "--sc-sticker-shadow": "drop-shadow(0 calc(var(--u)*0.25) calc(var(--u)*0.6) rgba(0,0,0,.4))",
  "--sc-mark": "#ff7a3d",
  "--sc-glint": "linear-gradient(90deg,transparent,rgba(255,255,255,.18) 30%,rgba(255,255,255,.62) 50%,rgba(255,255,255,.18) 70%,transparent)",
  "--sc-glint-blend": "screen",
  "--sc-confetti": "#ff7a3d,#ffa577,#c9b8a8,#9be38b,#ffffff",
  "--sc-spark": "#fff1d6",
  "--sc-spark-2": "#ffd9b3",
  "--sc-loupe-ring": "#ff7a3d",
  "--sc-cursor-fill": "#f7f9ff",
  "--sc-cursor-line": "#0d1017",
  "--sc-cursor-shadow": "drop-shadow(0 calc(var(--u)*0.16) calc(var(--u)*0.31) rgba(0,0,0,.55))",
  "--sc-ripple-ring": "#ff7a3d",
  "--sc-ripple": "rgba(255,122,61,0.22)",
  "--sc-ripple-glint": "rgba(255,255,255,.35)",
  "--sc-keys-ink": "#fff4ec",
  "--sc-keys-bg": "linear-gradient(180deg,#2e2723,#170f0b)",
  "--sc-keys-line": "#5a3320",
  "--sc-keys-shadow": "0 6px 0 #0a0605,0 14px 30px rgba(0,0,0,.45)",
  "--sc-progress": "#ff7a3d",
  "--sc-progress-track": "#00000059",
  "--sc-pip-ring": "#ff7a3d",
  "--sc-letterbox": "#070403",
  "--dv-shadow": "0 34px 90px rgba(0,0,0,.42),0 10px 24px rgba(0,0,0,.25)",
  "--dv-bar-tint": "#ffffff",
  "--dv-bezel": "#0c0d11",
  "--dv-rim": "#3a3f4b",
  "--dv-island": "#07080b",
  "--dv-browser-shadow": "0 0 0 var(--hairline) var(--line),var(--dv-shadow)",
  "--dv-url-pad": "1.2em",
  "--dv-rim-width": "2px",
  "--sc-traffic-1": "#ff5f57",
  "--sc-traffic-2": "#febc2e",
  "--sc-traffic-3": "#28c840",
  "--tr-seam": "#99654d",
  "--tr-iris": "#b2996f",
  "--tr-flash": "#ffbc9e",
  "--tr-fill": "#070403",
  "--sc-card-radius": "calc(var(--u)*.731)",
  "--sc-radius": "calc(var(--u)*.467)",
  "--sc-sub-radius": "calc(var(--u)*.272)",
  "--sc-hairline": "1px",
  "--sc-cap-bar-size": "calc(var(--u)*0.16)",
  "--sc-spot-radius": "calc(var(--u)*0.73)",
  "--sc-spot-width": "calc(var(--u)*0.16)",
  "--sc-cursor-size": "calc(var(--u)*1.35)",
  "--sc-keys-radius": "12px",
  "--sc-keys-size": "26px",
  "--sc-cursor-line-width": "1.4",
  "--sc-sub-pad-y": "calc(var(--u)*0.12)",
  "--sc-badge-pad-x": "calc(var(--u)*0.9)",
  "--sc-badge-pad-y": "calc(var(--u)*0.35)",
  "--sc-spot-shadow": "0 0 0 var(--sc-spot-width) var(--sc-spot),0 0 0 9999px var(--sc-dim)",
  "--sc-karaoke-halo": "0 0 0 calc(var(--u)*0.12) var(--sc-karaoke-bg)",
  "--sc-ripple-shadow": "0 0 0 7px var(--sc-ripple),inset 0 0 0 3px var(--sc-ripple-glint)",
  "--sc-keys-pad": "10px 16px",
  "--sc-pad-x": "calc(var(--u)*1.7)",
  "--sc-pad-y": "calc(var(--u)*1.1)",
  "--sc-edge": "calc(var(--u)*2.3)",
  "--sc-mark-width": ".0042",
  "--sc-mark-head": ".016",
  "--sc-mark-wobble": ".0025",
  "--sc-arrow-width": ".0022",
  "--sc-arrow-head": ".009",
  "--sc-spark-width": ".0022",
  "--sc-ripple-size": ".0375",
  "--sc-scrim-blur": ".004",
  "--sc-loupe-ring-width": ".015",
  "--sc-pip-ring-width": ".02",
  "--sc-progress-size": ".006",
  "--tr-shade": ".55",
};

/**
 * Блокбастер: почти чёрный фон, хромовые заголовки римской капителью (Forum, в духе Trajan — шрифта
 * киноафиш), золото и огонь акцентов, искры. Жанровая: только трейлер-боевик и его пародия.
 */
const BLOCKBUSTER: ThemeVars = {
  "--bg": "#060607",
  "--glow": "#1b140c",
  "--ink": "#f3efe8",
  "--body": "#d6cfc4",
  "--mut": "#8f887e",
  "--line": "#2a2622",
  "--card": "#111010",
  "--node": "#151413",
  "--node-line": "#3a342d",
  "--acc": "#e8a54b",
  "--acc2": "#ff7a2a",
  "--bad": "#ff6b6b",
  "--good": "#9be38b",
  "--bad-line": "#6f322f",
  "--sans": '"Oswald", system-ui, sans-serif',
  "--mono": '"JetBrains Mono", ui-monospace, monospace',
  "--display": '"Forum", ui-serif, serif',
  "--display-weight": "400",
  "--display-tracking": ".08em",
  "--display-case": "uppercase",
  "--kicker-case": "uppercase",
  "--kicker-tracking": ".16em",
  "--sub-font": '"Fira Sans", system-ui, sans-serif',
  "--sub-weight": "600",
  "--bg-motion": "particles",
  "--bg-intensity": ".75",
  "--radius-sm": "9px",
  "--radius-md": "12px",
  "--radius-lg": "16px",
  "--radius-xl": "19px",
  "--radius-pill": "999px",
  "--hairline": "1px",
  "--rule-size": "3px",
  "--rail-size": "3px",
  "--ring-size": "2px",
  "--dot-ring": "4px",
  "--ring-width": "9",
  "--chart-axis": "2px",
  "--chart-line-width": "6",
  "--chart-dot-ring": "5px",
  "--ba-line-width": "4px",
  "--code-hl-bar": "4px",
  "--space-xs": "6px",
  "--space-s": "12px",
  "--space-m": "18px",
  "--space-l": "24px",
  "--space-xl": "30px",
  "--space-2xl": "36px",
  "--space-3xl": "46px",
  "--code-name": "#8f887e",
  "--code-gutter": "#7f776d",
  "--code-kw": "#e8a54b",
  "--code-str": "#9be38b",
  "--code-num": "#ff7a2a",
  "--code-fn": "#ffe0b0",
  "--code-type": "#ff6b6b",
  "--code-com": "#8f887e",
  "--code-pun": "#d6cfc4",
  "--code-bg": "#030303",
  "--code-bar": "#111010",
  "--code-line": "#2a2622",
  "--code-ink": "#f3efe8",
  "--ba-line": "#ffffff",
  "--ba-knob-bg": "#ffffff",
  "--ba-knob-ink": "#111111",
  "--ba-label-bg": "rgba(8,10,16,.72)",
  "--ba-label-ink": "#ffffff",
  "--shadow-3": "0 30px 80px rgba(0,0,0,.45)",
  "--shadow-color": "rgba(0,0,0,.6)",
  "--px-edge": "rgba(255,255,255,.14)",
  "--px-dim": "brightness(.45) saturate(.8)",
  "--cta-sheen": "rgba(255,255,255,.38)",
  "--pv-glint": "#fffaf0",
  "--pv-glint-strength": ".5",
  "--pv-reflection": ".34",
  "--pv-shade": ".8",
  "--orbit-glow": "0 0 50px color-mix(in srgb,var(--acc2) 16%,transparent)",
  "--step-halo": "0 0 0 9px color-mix(in srgb,var(--acc) 22%,transparent)",
  "--dot-halo": "0 0 0 7px color-mix(in srgb,var(--acc) 20%,transparent)",
  "--code-caret": "3px 0 0 var(--acc2)",
  "--code-hl-shadow": "inset var(--code-hl-bar) 0 0 var(--acc)",
  "--cta-glow": "0 18px 50px color-mix(in srgb,var(--acc) 38%,transparent)",
  "--ba-line-shadow": "0 0 18px var(--shadow-color)",
  "--sc-spot": "rgba(232,165,75,.95)",
  "--sc-dim": "rgba(3,3,4,.62)",
  "--sc-accent-soft": "rgba(232,165,75,.42)",
  "--sc-fade": "#030303",
  "--sc-cap-bg": "linear-gradient(180deg,rgba(24,22,20,.96),rgba(14,13,12,.96))",
  "--sc-cap-line": "#4a4036",
  "--sc-cap-ink": "#f3efe8",
  "--sc-cap-bar": "linear-gradient(90deg,#e8a54b,#ff7a2a)",
  "--sc-card-bg": "linear-gradient(135deg,rgba(26,24,21,.96),rgba(12,11,10,.95))",
  "--sc-card-line": "rgba(232,165,75,.5)",
  "--sc-card-ink": "#f3efe8",
  "--sc-card-body": "#d9d2c7",
  "--sc-card-accent": "linear-gradient(90deg,#e8a54b,#ff7a2a)",
  "--sc-card-shadow": "0 20px 54px rgba(0,0,0,.6),inset 0 1px rgba(255,255,255,.07)",
  "--sc-card-accent-solid": "#e8a54b",
  "--sc-lower-bar": "linear-gradient(180deg,#e8a54b,#ff7a2a)",
  "--sc-sub-ink": "#ffffff",
  "--sc-sub-bg": "rgba(3,3,3,.9)",
  "--sc-sub-outline-ink": "#ffffff",
  "--sc-sub-outline": "#000000",
  "--sc-sub-accent": "#f0b35a",
  "--sc-sub-outline-shadow": SUB_OUTLINE_SHADOW,
  "--sc-karaoke-ink": "#060607",
  "--sc-karaoke-bg": "#e8a54b",
  "--sc-badge-ink": "#060607",
  "--sc-badge-bg": "#e8a54b",
  "--sc-badge-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*1.2) rgba(0,0,0,.35)",
  "--sc-scrim": "radial-gradient(ellipse at 50% 50%,rgba(3,3,3,.86) 0%,rgba(3,3,3,.74) 60%,rgba(3,3,3,.8) 100%)",
  "--sc-title-ink": "#f3efe8",
  "--sc-title-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*2.4) rgba(0,0,0,.55)",
  "--sc-cap-shadow": "0 calc(var(--u)*1.2) calc(var(--u)*3.1) rgba(0,0,0,.65)",
  "--sc-sticker-shadow": "drop-shadow(0 calc(var(--u)*0.25) calc(var(--u)*0.6) rgba(0,0,0,.4))",
  "--sc-mark": "#ff7a2a",
  "--sc-glint": "linear-gradient(90deg,transparent,rgba(255,255,255,.18) 30%,rgba(255,255,255,.62) 50%,rgba(255,255,255,.18) 70%,transparent)",
  "--sc-glint-blend": "screen",
  "--sc-confetti": "#e8a54b,#ff7a2a,#9be38b,#ff6b6b,#ffffff",
  "--sc-spark": "#ffe4b0",
  "--sc-spark-2": "#ff7a2a",
  "--sc-loupe-ring": "#e8a54b",
  "--sc-cursor-fill": "#f7f9ff",
  "--sc-cursor-line": "#0d1017",
  "--sc-cursor-shadow": "drop-shadow(0 calc(var(--u)*0.16) calc(var(--u)*0.31) rgba(0,0,0,.55))",
  "--sc-ripple-ring": "#ff7a2a",
  "--sc-ripple": "rgba(255,122,42,0.22)",
  "--sc-ripple-glint": "rgba(255,255,255,.35)",
  "--sc-keys-ink": "#f3efe8",
  "--sc-keys-bg": "linear-gradient(180deg,#262422,#111010)",
  "--sc-keys-line": "#4a4036",
  "--sc-keys-shadow": "0 6px 0 #050505,0 14px 30px rgba(0,0,0,.45)",
  "--sc-progress": "#e8a54b",
  "--sc-progress-track": "#00000059",
  "--sc-pip-ring": "#e8a54b",
  "--sc-letterbox": "#030303",
  "--dv-shadow": "0 34px 90px rgba(0,0,0,.42),0 10px 24px rgba(0,0,0,.25)",
  "--dv-bar-tint": "#ffffff",
  "--dv-bezel": "#0c0d11",
  "--dv-rim": "#3a3f4b",
  "--dv-island": "#07080b",
  "--dv-browser-shadow": "0 0 0 var(--hairline) var(--line),var(--dv-shadow)",
  "--dv-url-pad": "1.2em",
  "--dv-rim-width": "2px",
  "--sc-traffic-1": "#ff5f57",
  "--sc-traffic-2": "#febc2e",
  "--sc-traffic-3": "#28c840",
  "--tr-seam": "#8a7a62",
  "--tr-iris": "#c8a86a",
  "--tr-flash": "#ffd9a8",
  "--tr-fill": "#030303",
  "--sc-card-radius": "calc(var(--u)*.731)",
  "--sc-radius": "calc(var(--u)*.467)",
  "--sc-sub-radius": "calc(var(--u)*.272)",
  "--sc-hairline": "1px",
  "--sc-cap-bar-size": "calc(var(--u)*0.16)",
  "--sc-spot-radius": "calc(var(--u)*0.73)",
  "--sc-spot-width": "calc(var(--u)*0.16)",
  "--sc-cursor-size": "calc(var(--u)*1.35)",
  "--sc-keys-radius": "12px",
  "--sc-keys-size": "26px",
  "--sc-cursor-line-width": "1.4",
  "--sc-sub-pad-y": "calc(var(--u)*0.12)",
  "--sc-badge-pad-x": "calc(var(--u)*0.9)",
  "--sc-badge-pad-y": "calc(var(--u)*0.35)",
  "--sc-spot-shadow": "0 0 0 var(--sc-spot-width) var(--sc-spot),0 0 0 9999px var(--sc-dim)",
  "--sc-karaoke-halo": "0 0 0 calc(var(--u)*0.12) var(--sc-karaoke-bg)",
  "--sc-ripple-shadow": "0 0 0 7px var(--sc-ripple),inset 0 0 0 3px var(--sc-ripple-glint)",
  "--sc-keys-pad": "10px 16px",
  "--sc-pad-x": "calc(var(--u)*1.7)",
  "--sc-pad-y": "calc(var(--u)*1.1)",
  "--sc-edge": "calc(var(--u)*2.3)",
  "--sc-mark-width": ".0042",
  "--sc-mark-head": ".016",
  "--sc-mark-wobble": ".0025",
  "--sc-arrow-width": ".0022",
  "--sc-arrow-head": ".009",
  "--sc-spark-width": ".0022",
  "--sc-ripple-size": ".0375",
  "--sc-scrim-blur": ".004",
  "--sc-loupe-ring-width": ".015",
  "--sc-pip-ring-width": ".02",
  "--sc-progress-size": ".006",
  "--tr-shade": ".55",
};

/**
 * Чертёж: тёмно-синее поле, голубой и жёлтый, моноширинные заголовки,
 * фон — тихая сетка чертежа. Для технических объяснений и схем.
 */
const BLUEPRINT: ThemeVars = {
  "--bg": "#0a1a33",
  "--glow": "#0f2d57",
  "--ink": "#eaf4ff",
  "--body": "#b9d0ea",
  "--mut": "#7f9cc0",
  "--line": "#1f3f6b",
  "--card": "#0d2140",
  "--node": "#0f2548",
  "--node-line": "#2c5690",
  "--acc": "#4cc9f0",
  "--acc2": "#f9c74f",
  "--bad": "#ff8fa3",
  "--good": "#80ed99",
  "--bad-line": "#694b66",
  "--sans": '"Fira Sans", system-ui, sans-serif',
  "--mono": '"Martian Mono", ui-monospace, monospace',
  "--display": '"Tektur", system-ui, sans-serif',
  "--display-weight": "700",
  "--display-tracking": "0em",
  "--display-case": "none",
  "--kicker-case": "none",
  "--kicker-tracking": ".02em",
  "--sub-font": '"Fira Sans", system-ui, sans-serif',
  "--sub-weight": "600",
  "--bg-motion": "grid",
  "--bg-intensity": ".6",
  "--radius-sm": "5px",
  "--radius-md": "7px",
  "--radius-lg": "9px",
  "--radius-xl": "11px",
  "--radius-pill": "999px",
  "--hairline": "1px",
  "--rule-size": "3px",
  "--rail-size": "3px",
  "--ring-size": "2px",
  "--dot-ring": "4px",
  "--ring-width": "9",
  "--chart-axis": "2px",
  "--chart-line-width": "6",
  "--chart-dot-ring": "5px",
  "--ba-line-width": "4px",
  "--code-hl-bar": "4px",
  "--space-xs": "6px",
  "--space-s": "12px",
  "--space-m": "18px",
  "--space-l": "24px",
  "--space-xl": "30px",
  "--space-2xl": "36px",
  "--space-3xl": "46px",
  "--code-name": "#7f9cc0",
  "--code-gutter": "#647fa1",
  "--code-kw": "#4cc9f0",
  "--code-str": "#80ed99",
  "--code-num": "#f9c74f",
  "--code-fn": "#a5d8ff",
  "--code-type": "#ff8fa3",
  "--code-com": "#7f9cc0",
  "--code-pun": "#b9d0ea",
  "--code-bg": "#06101f",
  "--code-bar": "#0d2140",
  "--code-line": "#1f3f6b",
  "--code-ink": "#eaf4ff",
  "--ba-line": "#ffffff",
  "--ba-knob-bg": "#ffffff",
  "--ba-knob-ink": "#111111",
  "--ba-label-bg": "rgba(8,10,16,.72)",
  "--ba-label-ink": "#ffffff",
  "--shadow-3": "0 30px 80px rgba(0,0,0,.45)",
  "--shadow-color": "rgba(0,0,0,.6)",
  "--px-edge": "rgba(255,255,255,.14)",
  "--px-dim": "brightness(.45) saturate(.8)",
  "--cta-sheen": "rgba(255,255,255,.38)",
  "--pv-glint": "#fef8ea",
  "--pv-glint-strength": ".5",
  "--pv-reflection": ".34",
  "--pv-shade": ".8",
  "--orbit-glow": "0 0 50px color-mix(in srgb,var(--acc2) 16%,transparent)",
  "--step-halo": "0 0 0 9px color-mix(in srgb,var(--acc) 22%,transparent)",
  "--dot-halo": "0 0 0 7px color-mix(in srgb,var(--acc) 20%,transparent)",
  "--code-caret": "3px 0 0 var(--acc2)",
  "--code-hl-shadow": "inset var(--code-hl-bar) 0 0 var(--acc)",
  "--cta-glow": "0 18px 50px color-mix(in srgb,var(--acc) 38%,transparent)",
  "--ba-line-shadow": "0 0 18px var(--shadow-color)",
  "--sc-spot": "rgba(76,201,240,.95)",
  "--sc-dim": "rgba(4,12,26,.6)",
  "--sc-accent-soft": "rgba(76,201,240,.42)",
  "--sc-fade": "#06101f",
  "--sc-cap-bg": "linear-gradient(180deg,rgba(16,40,76,.96),rgba(10,26,51,.96))",
  "--sc-cap-line": "#2c5690",
  "--sc-cap-ink": "#eaf4ff",
  "--sc-cap-bar": "#4cc9f0",
  "--sc-card-bg": "linear-gradient(135deg,rgba(14,38,72,.96),rgba(10,26,51,.95))",
  "--sc-card-line": "rgba(76,201,240,.5)",
  "--sc-card-ink": "#f2f8ff",
  "--sc-card-body": "#bcd3ec",
  "--sc-card-accent": "#4cc9f0",
  "--sc-card-shadow": "0 18px 44px rgba(2,10,24,.55),inset 0 1px rgba(255,255,255,.07)",
  "--sc-card-accent-solid": "#4cc9f0",
  "--sc-lower-bar": "#4cc9f0",
  "--sc-sub-ink": "#ffffff",
  "--sc-sub-bg": "rgba(6,16,31,.9)",
  "--sc-sub-outline-ink": "#ffffff",
  "--sc-sub-outline": "#000000",
  "--sc-sub-accent": "#f9c74f",
  "--sc-sub-outline-shadow": SUB_OUTLINE_SHADOW,
  "--sc-karaoke-ink": "#0a1a33",
  "--sc-karaoke-bg": "#4cc9f0",
  "--sc-badge-ink": "#0a1a33",
  "--sc-badge-bg": "#4cc9f0",
  "--sc-badge-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*1.2) rgba(0,0,0,.35)",
  "--sc-scrim": "radial-gradient(ellipse at 50% 50%,rgba(6,16,31,.86) 0%,rgba(6,16,31,.74) 60%,rgba(6,16,31,.8) 100%)",
  "--sc-title-ink": "#f2f8ff",
  "--sc-title-shadow": "0 calc(var(--u)*0.3) calc(var(--u)*2.4) rgba(0,0,0,.55)",
  "--sc-cap-shadow": "0 calc(var(--u)*1.2) calc(var(--u)*3.1) rgba(0,0,0,.65)",
  "--sc-sticker-shadow": "drop-shadow(0 calc(var(--u)*0.25) calc(var(--u)*0.6) rgba(0,0,0,.4))",
  "--sc-mark": "#f9c74f",
  "--sc-glint": "linear-gradient(90deg,transparent,rgba(255,255,255,.18) 30%,rgba(255,255,255,.62) 50%,rgba(255,255,255,.18) 70%,transparent)",
  "--sc-glint-blend": "screen",
  "--sc-confetti": "#4cc9f0,#f9c74f,#80ed99,#ff8fa3,#ffffff",
  "--sc-spark": "#fff6d1",
  "--sc-spark-2": "#f9c74f",
  "--sc-loupe-ring": "#4cc9f0",
  "--sc-cursor-fill": "#f7f9ff",
  "--sc-cursor-line": "#0d1017",
  "--sc-cursor-shadow": "drop-shadow(0 calc(var(--u)*0.16) calc(var(--u)*0.31) rgba(0,0,0,.55))",
  "--sc-ripple-ring": "#f9c74f",
  "--sc-ripple": "rgba(249,199,79,0.22)",
  "--sc-ripple-glint": "rgba(255,255,255,.35)",
  "--sc-keys-ink": "#f2f8ff",
  "--sc-keys-bg": "linear-gradient(180deg,#253753,#0d2140)",
  "--sc-keys-line": "#2c5690",
  "--sc-keys-shadow": "0 6px 0 #071224,0 14px 30px rgba(0,0,0,.45)",
  "--sc-progress": "#4cc9f0",
  "--sc-progress-track": "#00000059",
  "--sc-pip-ring": "#4cc9f0",
  "--sc-letterbox": "#06101f",
  "--dv-shadow": "0 34px 90px rgba(0,0,0,.42),0 10px 24px rgba(0,0,0,.25)",
  "--dv-bar-tint": "#ffffff",
  "--dv-bezel": "#0c0d11",
  "--dv-rim": "#3a3f4b",
  "--dv-island": "#07080b",
  "--dv-browser-shadow": "0 0 0 var(--hairline) var(--line),var(--dv-shadow)",
  "--dv-url-pad": "1.2em",
  "--dv-rim-width": "2px",
  "--sc-traffic-1": "#ff5f57",
  "--sc-traffic-2": "#febc2e",
  "--sc-traffic-3": "#28c840",
  "--tr-seam": "#538493",
  "--tr-iris": "#b09b68",
  "--tr-flash": "#a6e4f8",
  "--tr-fill": "#06101f",
  "--sc-card-radius": "calc(var(--u)*.418)",
  "--sc-radius": "calc(var(--u)*.27)",
  "--sc-sub-radius": "calc(var(--u)*.158)",
  "--sc-hairline": "1px",
  "--sc-cap-bar-size": "calc(var(--u)*0.16)",
  "--sc-spot-radius": "calc(var(--u)*0.73)",
  "--sc-spot-width": "calc(var(--u)*0.16)",
  "--sc-cursor-size": "calc(var(--u)*1.35)",
  "--sc-keys-radius": "12px",
  "--sc-keys-size": "26px",
  "--sc-cursor-line-width": "1.4",
  "--sc-sub-pad-y": "calc(var(--u)*0.12)",
  "--sc-badge-pad-x": "calc(var(--u)*0.9)",
  "--sc-badge-pad-y": "calc(var(--u)*0.35)",
  "--sc-spot-shadow": "0 0 0 var(--sc-spot-width) var(--sc-spot),0 0 0 9999px var(--sc-dim)",
  "--sc-karaoke-halo": "0 0 0 calc(var(--u)*0.12) var(--sc-karaoke-bg)",
  "--sc-ripple-shadow": "0 0 0 7px var(--sc-ripple),inset 0 0 0 3px var(--sc-ripple-glint)",
  "--sc-keys-pad": "10px 16px",
  "--sc-pad-x": "calc(var(--u)*1.7)",
  "--sc-pad-y": "calc(var(--u)*1.1)",
  "--sc-edge": "calc(var(--u)*2.3)",
  "--sc-mark-width": ".0042",
  "--sc-mark-head": ".016",
  "--sc-mark-wobble": ".0025",
  "--sc-arrow-width": ".0022",
  "--sc-arrow-head": ".009",
  "--sc-spark-width": ".0022",
  "--sc-ripple-size": ".0375",
  "--sc-scrim-blur": ".004",
  "--sc-loupe-ring-width": ".015",
  "--sc-pip-ring-width": ".02",
  "--sc-progress-size": ".006",
  "--tr-shade": ".55",
};

/** Поставляемые темы: имя → полный набор переменных. */
export const THEMES: Record<string, ThemeVars> = {
  neutral: NEUTRAL,
  frost: FROST,
  midnight: MIDNIGHT,
  "calm-paper": CALM_PAPER,
  synthwave: SYNTHWAVE,
  noir: NOIR,
  aurora: AURORA,
  daylight: DAYLIGHT,
  ember: EMBER,
  blueprint: BLUEPRINT,
  blockbuster: BLOCKBUSTER,
};

export const THEME_NAMES: string[] = Object.keys(THEMES);

/**
 * Тема ролика в том виде, в каком её пишут в шапке источника: имя темы,
 * свой набор переменных или имя вместе с точечными правками.
 */
export type ThemeInput = string | (ThemeVars & { preset?: string });

export class ThemeError extends Error {}

/** Имя переменной приводится к виду `--имя`: в шапке пишут и так, и так. */
const dashed = (key: string): string => (key.startsWith("--") ? key : `--${key}`);

/**
 * Тема → плоский набор переменных.
 *
 * Имя темы разрешается в её набор, свои переменные кладутся ПОВЕРХ него:
 * точечная правка одного цвета не должна означать, что автор обязан
 * переписать всю тему руками.
 */
export function resolveTheme(input: ThemeInput | undefined, over?: ThemeVars): ThemeVars {
  if (input === undefined) return checked({ ...(over ?? THEMES.neutral!) });
  if (typeof input === "string") return preset(input);
  const { preset: name, ...own } = input;
  // Основа: названная тема, иначе тема, поверх которой ложатся правки (тема ролика для сцены).
  // Без того и другого набор обязан быть полным: дыру в нём заполнить нечем, кроме догадки.
  const base = name !== undefined ? preset(name) : over ? { ...over } : {};
  const vars: ThemeVars = { ...base };
  for (const [key, value] of Object.entries(own)) vars[dashed(key)] = value;
  if (name === undefined && !over) {
    const missing = THEME_KEYS.filter((k) => !vars[k]);
    if (missing.length) {
      throw new ThemeError(`a theme without a named base must write every token of the contract; missing ${missing.length}: `
        + `${missing.slice(0, 12).join(", ")}${missing.length > 12 ? ", …" : ""}. Start from a named theme instead: `
        + `{"preset":"neutral","--acc":"#ff5a1f"} (help themes)`);
    }
  }
  return checked(vars);
}

/** Токены прохода ffmpeg и шейдеров — только `#rrggbb` или `#rrggbbaa` (список — через запятую). */
function checked(vars: ThemeVars): ThemeVars {
  for (const key of HEX_TOKENS) {
    const v = vars[key];
    if (v !== undefined && !v.split(",").every((c) => /^#[0-9a-f]{6}(?:[0-9a-f]{2})?$/i.test(c.trim()))) {
      throw new ThemeError(`${key}: «${v}» — ffmpeg and the shaders read this colour as numbers; write it as #rrggbb or #rrggbbaa`);
    }
  }
  return vars;
}

function preset(name: string): ThemeVars {
  const found = THEMES[name.trim()];
  if (!found) {
    throw new ThemeError(`unknown theme «${name}»; available: ${THEME_NAMES.join(", ")}`);
  }
  return { ...found };
}

/**
 * Токены, которые живая съёмка впекает в пиксели дубля: курсор, клик, клавиши, подсветка цели
 * (слой `capture-overlay.ts`) и карточка (`capture.ts`). Список сверяет тест с самими слоями.
 */
export const BAKED_TOKENS = ["--display", "--display-weight", "--sans", "--sc-card-bg", "--sc-card-body", "--sc-card-ink", "--sc-card-line",
  "--sc-card-radius", "--sc-card-shadow", "--sc-cursor-fill", "--sc-cursor-line", "--sc-cursor-line-width", "--sc-cursor-shadow",
  "--sc-cursor-size", "--sc-edge", "--sc-hairline", "--sc-keys-bg", "--sc-keys-ink", "--sc-keys-line", "--sc-keys-pad",
  "--sc-keys-radius", "--sc-keys-shadow", "--sc-keys-size", "--sc-pad-x", "--sc-pad-y", "--sc-ripple-ring", "--sc-ripple-shadow",
  "--sc-spot-radius", "--sc-spot-shadow", "--sc-spot-width"] as const;

/** Впекаемая часть темы: токены дубля и всё, на что их значения ссылаются через `var()`. */
function bakedPart(vars: ThemeVars): Array<[string, string | undefined]> {
  const seen = new Set<string>();
  const walk = (k: string): void => {
    if (seen.has(k)) return;
    seen.add(k);
    for (const m of String(vars[k] ?? "").matchAll(/var\((--[\w-]+)/g)) walk(m[1]!);
  };
  for (const k of BAKED_TOKENS) walk(k);
  return [...seen].sort().map((k) => [k, vars[k]]);
}

const fnv = (text: string): string => {
  let h = 2166136261;
  for (let i = 0; i < text.length; i++) { h ^= text.charCodeAt(i); h = Math.imul(h, 16777619) >>> 0; }
  return h.toString(16).padStart(8, "0");
};

/**
 * Отпечаток темы: по нему дубль живой съёмки помнит, в какой теме записан его слой (курсор,
 * клик, клавиши, карточка), а `lint` сверяет его с темой сцены, которая дубль показывает.
 * Считается только по впекаемой части: правка субтитров или слайдов в шапке дубль чужим не
 * делает — его пиксели от неё не меняются. Имя — тема, чья впекаемая часть та же.
 */
export function themeFingerprint(vars: ThemeVars): { id: string; name?: string; of: "baked" } {
  const part = JSON.stringify(bakedPart(vars));
  const name = THEME_NAMES.find((n) => JSON.stringify(bakedPart(THEMES[n]!)) === part);
  return { id: fnv(part), ...(name ? { name } : {}), of: "baked" };
}

/** Прежний отпечаток — по всей теме; им записаны дубли, снятые до `of: "baked"`. */
export function wholeThemeFingerprint(vars: ThemeVars): string {
  return fnv(JSON.stringify(Object.keys(vars).sort().map((k) => [k, vars[k]])));
}

/**
 * Цвет темы в записи ffmpeg: `#rrggbb` → `0xRRGGBB`, `#rrggbbaa` → `0xRRGGBB@a`. Токены, которые
 * читает ffmpeg, разбор темы уже проверил на эту запись, поэтому умолчания здесь нет.
 */
export function ffmpegColour(css: string): string {
  const m = /^#([0-9a-f]{6})([0-9a-f]{2})?$/i.exec(css.trim());
  if (!m) throw new ThemeError(`«${css}» is not #rrggbb or #rrggbbaa`);
  return m[2] ? `0x${m[1]}@${(Number.parseInt(m[2], 16) / 255).toFixed(3)}` : `0x${m[1]}`;
}
